// Code generated by ent, DO NOT EDIT.

package noteconnectionjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the noteconnectionjob type in the database.
	Label = "note_connection_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldNoteID holds the string denoting the note_id field in the database.
	FieldNoteID = "note_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTotalCount holds the string denoting the total_count field in the database.
	FieldTotalCount = "total_count"
	// FieldImportedCount holds the string denoting the imported_count field in the database.
	FieldImportedCount = "imported_count"
	// FieldPushedCount holds the string denoting the pushed_count field in the database.
	FieldPushedCount = "pushed_count"
	// FieldSkippedCount holds the string denoting the skipped_count field in the database.
	FieldSkippedCount = "skipped_count"
	// FieldFailedCount holds the string denoting the failed_count field in the database.
	FieldFailedCount = "failed_count"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldOptionsJSON holds the string denoting the options_json field in the database.
	FieldOptionsJSON = "options_json"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeNote holds the string denoting the note edge name in mutations.
	EdgeNote = "note"
	// Table holds the table name of the noteconnectionjob in the database.
	Table = "note_connection_jobs"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "note_connection_jobs"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "note_connection_jobs"
	// AccountInverseTable is the table name for the NoteConnectionAccount entity.
	// It exists in this package in order to avoid circular dependency with the "noteconnectionaccount" package.
	AccountInverseTable = "note_connection_accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
	// NoteTable is the table that holds the note relation/edge.
	NoteTable = "note_connection_jobs"
	// NoteInverseTable is the table name for the Note entity.
	// It exists in this package in order to avoid circular dependency with the "note" package.
	NoteInverseTable = "notes"
	// NoteColumn is the table column denoting the note relation/edge.
	NoteColumn = "note_id"
)

// Columns holds all SQL columns for noteconnectionjob fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldOperation,
	FieldUserID,
	FieldAccountID,
	FieldNoteID,
	FieldStatus,
	FieldTotalCount,
	FieldImportedCount,
	FieldPushedCount,
	FieldSkippedCount,
	FieldFailedCount,
	FieldMessage,
	FieldOptionsJSON,
	FieldStartedAt,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultTotalCount holds the default value on creation for the "total_count" field.
	DefaultTotalCount int
	// DefaultImportedCount holds the default value on creation for the "imported_count" field.
	DefaultImportedCount int
	// DefaultPushedCount holds the default value on creation for the "pushed_count" field.
	DefaultPushedCount int
	// DefaultSkippedCount holds the default value on creation for the "skipped_count" field.
	DefaultSkippedCount int
	// DefaultFailedCount holds the default value on creation for the "failed_count" field.
	DefaultFailedCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the NoteConnectionJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByNoteID orders the results by the note_id field.
func ByNoteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoteID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTotalCount orders the results by the total_count field.
func ByTotalCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCount, opts...).ToFunc()
}

// ByImportedCount orders the results by the imported_count field.
func ByImportedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportedCount, opts...).ToFunc()
}

// ByPushedCount orders the results by the pushed_count field.
func ByPushedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPushedCount, opts...).ToFunc()
}

// BySkippedCount orders the results by the skipped_count field.
func BySkippedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkippedCount, opts...).ToFunc()
}

// ByFailedCount orders the results by the failed_count field.
func ByFailedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedCount, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByOptionsJSON orders the results by the options_json field.
func ByOptionsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOptionsJSON, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByNoteField orders the results by note field.
func ByNoteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNoteStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
func newNoteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NoteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NoteTable, NoteColumn),
	)
}
