// Code generated by ent, DO NOT EDIT.

package note

import (
	"smarticky/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldContent, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldColor, v))
}

// ProtectionPasswordHash applies equality check predicate on the "protection_password_hash" field. It's identical to ProtectionPasswordHashEQ.
func ProtectionPasswordHash(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldProtectionPasswordHash, v))
}

// EncryptedContent applies equality check predicate on the "encrypted_content" field. It's identical to EncryptedContentEQ.
func EncryptedContent(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptedContent, v))
}

// EncryptionAlg applies equality check predicate on the "encryption_alg" field. It's identical to EncryptionAlgEQ.
func EncryptionAlg(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptionAlg, v))
}

// EncryptionKdf applies equality check predicate on the "encryption_kdf" field. It's identical to EncryptionKdfEQ.
func EncryptionKdf(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptionKdf, v))
}

// EncryptionSalt applies equality check predicate on the "encryption_salt" field. It's identical to EncryptionSaltEQ.
func EncryptionSalt(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptionSalt, v))
}

// EncryptionNonce applies equality check predicate on the "encryption_nonce" field. It's identical to EncryptionNonceEQ.
func EncryptionNonce(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptionNonce, v))
}

// IsStarred applies equality check predicate on the "is_starred" field. It's identical to IsStarredEQ.
func IsStarred(v bool) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldIsStarred, v))
}

// IsDeleted applies equality check predicate on the "is_deleted" field. It's identical to IsDeletedEQ.
func IsDeleted(v bool) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldIsDeleted, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldContent, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldColor, v))
}

// ColorIsNil applies the IsNil predicate on the "color" field.
func ColorIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldColor))
}

// ColorNotNil applies the NotNil predicate on the "color" field.
func ColorNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldColor))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldColor, v))
}

// ProtectionModeEQ applies the EQ predicate on the "protection_mode" field.
func ProtectionModeEQ(v ProtectionMode) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldProtectionMode, v))
}

// ProtectionModeNEQ applies the NEQ predicate on the "protection_mode" field.
func ProtectionModeNEQ(v ProtectionMode) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldProtectionMode, v))
}

// ProtectionModeIn applies the In predicate on the "protection_mode" field.
func ProtectionModeIn(vs ...ProtectionMode) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldProtectionMode, vs...))
}

// ProtectionModeNotIn applies the NotIn predicate on the "protection_mode" field.
func ProtectionModeNotIn(vs ...ProtectionMode) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldProtectionMode, vs...))
}

// ProtectionPasswordHashEQ applies the EQ predicate on the "protection_password_hash" field.
func ProtectionPasswordHashEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashNEQ applies the NEQ predicate on the "protection_password_hash" field.
func ProtectionPasswordHashNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashIn applies the In predicate on the "protection_password_hash" field.
func ProtectionPasswordHashIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldProtectionPasswordHash, vs...))
}

// ProtectionPasswordHashNotIn applies the NotIn predicate on the "protection_password_hash" field.
func ProtectionPasswordHashNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldProtectionPasswordHash, vs...))
}

// ProtectionPasswordHashGT applies the GT predicate on the "protection_password_hash" field.
func ProtectionPasswordHashGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashGTE applies the GTE predicate on the "protection_password_hash" field.
func ProtectionPasswordHashGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashLT applies the LT predicate on the "protection_password_hash" field.
func ProtectionPasswordHashLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashLTE applies the LTE predicate on the "protection_password_hash" field.
func ProtectionPasswordHashLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashContains applies the Contains predicate on the "protection_password_hash" field.
func ProtectionPasswordHashContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashHasPrefix applies the HasPrefix predicate on the "protection_password_hash" field.
func ProtectionPasswordHashHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashHasSuffix applies the HasSuffix predicate on the "protection_password_hash" field.
func ProtectionPasswordHashHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashIsNil applies the IsNil predicate on the "protection_password_hash" field.
func ProtectionPasswordHashIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldProtectionPasswordHash))
}

// ProtectionPasswordHashNotNil applies the NotNil predicate on the "protection_password_hash" field.
func ProtectionPasswordHashNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldProtectionPasswordHash))
}

// ProtectionPasswordHashEqualFold applies the EqualFold predicate on the "protection_password_hash" field.
func ProtectionPasswordHashEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldProtectionPasswordHash, v))
}

// ProtectionPasswordHashContainsFold applies the ContainsFold predicate on the "protection_password_hash" field.
func ProtectionPasswordHashContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldProtectionPasswordHash, v))
}

// EncryptedContentEQ applies the EQ predicate on the "encrypted_content" field.
func EncryptedContentEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptedContent, v))
}

// EncryptedContentNEQ applies the NEQ predicate on the "encrypted_content" field.
func EncryptedContentNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldEncryptedContent, v))
}

// EncryptedContentIn applies the In predicate on the "encrypted_content" field.
func EncryptedContentIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldEncryptedContent, vs...))
}

// EncryptedContentNotIn applies the NotIn predicate on the "encrypted_content" field.
func EncryptedContentNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldEncryptedContent, vs...))
}

// EncryptedContentGT applies the GT predicate on the "encrypted_content" field.
func EncryptedContentGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldEncryptedContent, v))
}

// EncryptedContentGTE applies the GTE predicate on the "encrypted_content" field.
func EncryptedContentGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldEncryptedContent, v))
}

// EncryptedContentLT applies the LT predicate on the "encrypted_content" field.
func EncryptedContentLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldEncryptedContent, v))
}

// EncryptedContentLTE applies the LTE predicate on the "encrypted_content" field.
func EncryptedContentLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldEncryptedContent, v))
}

// EncryptedContentContains applies the Contains predicate on the "encrypted_content" field.
func EncryptedContentContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldEncryptedContent, v))
}

// EncryptedContentHasPrefix applies the HasPrefix predicate on the "encrypted_content" field.
func EncryptedContentHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldEncryptedContent, v))
}

// EncryptedContentHasSuffix applies the HasSuffix predicate on the "encrypted_content" field.
func EncryptedContentHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldEncryptedContent, v))
}

// EncryptedContentIsNil applies the IsNil predicate on the "encrypted_content" field.
func EncryptedContentIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldEncryptedContent))
}

// EncryptedContentNotNil applies the NotNil predicate on the "encrypted_content" field.
func EncryptedContentNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldEncryptedContent))
}

// EncryptedContentEqualFold applies the EqualFold predicate on the "encrypted_content" field.
func EncryptedContentEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldEncryptedContent, v))
}

// EncryptedContentContainsFold applies the ContainsFold predicate on the "encrypted_content" field.
func EncryptedContentContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldEncryptedContent, v))
}

// EncryptionAlgEQ applies the EQ predicate on the "encryption_alg" field.
func EncryptionAlgEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptionAlg, v))
}

// EncryptionAlgNEQ applies the NEQ predicate on the "encryption_alg" field.
func EncryptionAlgNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldEncryptionAlg, v))
}

// EncryptionAlgIn applies the In predicate on the "encryption_alg" field.
func EncryptionAlgIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldEncryptionAlg, vs...))
}

// EncryptionAlgNotIn applies the NotIn predicate on the "encryption_alg" field.
func EncryptionAlgNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldEncryptionAlg, vs...))
}

// EncryptionAlgGT applies the GT predicate on the "encryption_alg" field.
func EncryptionAlgGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldEncryptionAlg, v))
}

// EncryptionAlgGTE applies the GTE predicate on the "encryption_alg" field.
func EncryptionAlgGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldEncryptionAlg, v))
}

// EncryptionAlgLT applies the LT predicate on the "encryption_alg" field.
func EncryptionAlgLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldEncryptionAlg, v))
}

// EncryptionAlgLTE applies the LTE predicate on the "encryption_alg" field.
func EncryptionAlgLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldEncryptionAlg, v))
}

// EncryptionAlgContains applies the Contains predicate on the "encryption_alg" field.
func EncryptionAlgContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldEncryptionAlg, v))
}

// EncryptionAlgHasPrefix applies the HasPrefix predicate on the "encryption_alg" field.
func EncryptionAlgHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldEncryptionAlg, v))
}

// EncryptionAlgHasSuffix applies the HasSuffix predicate on the "encryption_alg" field.
func EncryptionAlgHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldEncryptionAlg, v))
}

// EncryptionAlgIsNil applies the IsNil predicate on the "encryption_alg" field.
func EncryptionAlgIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldEncryptionAlg))
}

// EncryptionAlgNotNil applies the NotNil predicate on the "encryption_alg" field.
func EncryptionAlgNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldEncryptionAlg))
}

// EncryptionAlgEqualFold applies the EqualFold predicate on the "encryption_alg" field.
func EncryptionAlgEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldEncryptionAlg, v))
}

// EncryptionAlgContainsFold applies the ContainsFold predicate on the "encryption_alg" field.
func EncryptionAlgContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldEncryptionAlg, v))
}

// EncryptionKdfEQ applies the EQ predicate on the "encryption_kdf" field.
func EncryptionKdfEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptionKdf, v))
}

// EncryptionKdfNEQ applies the NEQ predicate on the "encryption_kdf" field.
func EncryptionKdfNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldEncryptionKdf, v))
}

// EncryptionKdfIn applies the In predicate on the "encryption_kdf" field.
func EncryptionKdfIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldEncryptionKdf, vs...))
}

// EncryptionKdfNotIn applies the NotIn predicate on the "encryption_kdf" field.
func EncryptionKdfNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldEncryptionKdf, vs...))
}

// EncryptionKdfGT applies the GT predicate on the "encryption_kdf" field.
func EncryptionKdfGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldEncryptionKdf, v))
}

// EncryptionKdfGTE applies the GTE predicate on the "encryption_kdf" field.
func EncryptionKdfGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldEncryptionKdf, v))
}

// EncryptionKdfLT applies the LT predicate on the "encryption_kdf" field.
func EncryptionKdfLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldEncryptionKdf, v))
}

// EncryptionKdfLTE applies the LTE predicate on the "encryption_kdf" field.
func EncryptionKdfLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldEncryptionKdf, v))
}

// EncryptionKdfContains applies the Contains predicate on the "encryption_kdf" field.
func EncryptionKdfContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldEncryptionKdf, v))
}

// EncryptionKdfHasPrefix applies the HasPrefix predicate on the "encryption_kdf" field.
func EncryptionKdfHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldEncryptionKdf, v))
}

// EncryptionKdfHasSuffix applies the HasSuffix predicate on the "encryption_kdf" field.
func EncryptionKdfHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldEncryptionKdf, v))
}

// EncryptionKdfIsNil applies the IsNil predicate on the "encryption_kdf" field.
func EncryptionKdfIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldEncryptionKdf))
}

// EncryptionKdfNotNil applies the NotNil predicate on the "encryption_kdf" field.
func EncryptionKdfNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldEncryptionKdf))
}

// EncryptionKdfEqualFold applies the EqualFold predicate on the "encryption_kdf" field.
func EncryptionKdfEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldEncryptionKdf, v))
}

// EncryptionKdfContainsFold applies the ContainsFold predicate on the "encryption_kdf" field.
func EncryptionKdfContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldEncryptionKdf, v))
}

// EncryptionSaltEQ applies the EQ predicate on the "encryption_salt" field.
func EncryptionSaltEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptionSalt, v))
}

// EncryptionSaltNEQ applies the NEQ predicate on the "encryption_salt" field.
func EncryptionSaltNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldEncryptionSalt, v))
}

// EncryptionSaltIn applies the In predicate on the "encryption_salt" field.
func EncryptionSaltIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldEncryptionSalt, vs...))
}

// EncryptionSaltNotIn applies the NotIn predicate on the "encryption_salt" field.
func EncryptionSaltNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldEncryptionSalt, vs...))
}

// EncryptionSaltGT applies the GT predicate on the "encryption_salt" field.
func EncryptionSaltGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldEncryptionSalt, v))
}

// EncryptionSaltGTE applies the GTE predicate on the "encryption_salt" field.
func EncryptionSaltGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldEncryptionSalt, v))
}

// EncryptionSaltLT applies the LT predicate on the "encryption_salt" field.
func EncryptionSaltLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldEncryptionSalt, v))
}

// EncryptionSaltLTE applies the LTE predicate on the "encryption_salt" field.
func EncryptionSaltLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldEncryptionSalt, v))
}

// EncryptionSaltContains applies the Contains predicate on the "encryption_salt" field.
func EncryptionSaltContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldEncryptionSalt, v))
}

// EncryptionSaltHasPrefix applies the HasPrefix predicate on the "encryption_salt" field.
func EncryptionSaltHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldEncryptionSalt, v))
}

// EncryptionSaltHasSuffix applies the HasSuffix predicate on the "encryption_salt" field.
func EncryptionSaltHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldEncryptionSalt, v))
}

// EncryptionSaltIsNil applies the IsNil predicate on the "encryption_salt" field.
func EncryptionSaltIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldEncryptionSalt))
}

// EncryptionSaltNotNil applies the NotNil predicate on the "encryption_salt" field.
func EncryptionSaltNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldEncryptionSalt))
}

// EncryptionSaltEqualFold applies the EqualFold predicate on the "encryption_salt" field.
func EncryptionSaltEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldEncryptionSalt, v))
}

// EncryptionSaltContainsFold applies the ContainsFold predicate on the "encryption_salt" field.
func EncryptionSaltContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldEncryptionSalt, v))
}

// EncryptionNonceEQ applies the EQ predicate on the "encryption_nonce" field.
func EncryptionNonceEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldEncryptionNonce, v))
}

// EncryptionNonceNEQ applies the NEQ predicate on the "encryption_nonce" field.
func EncryptionNonceNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldEncryptionNonce, v))
}

// EncryptionNonceIn applies the In predicate on the "encryption_nonce" field.
func EncryptionNonceIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldEncryptionNonce, vs...))
}

// EncryptionNonceNotIn applies the NotIn predicate on the "encryption_nonce" field.
func EncryptionNonceNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldEncryptionNonce, vs...))
}

// EncryptionNonceGT applies the GT predicate on the "encryption_nonce" field.
func EncryptionNonceGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldEncryptionNonce, v))
}

// EncryptionNonceGTE applies the GTE predicate on the "encryption_nonce" field.
func EncryptionNonceGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldEncryptionNonce, v))
}

// EncryptionNonceLT applies the LT predicate on the "encryption_nonce" field.
func EncryptionNonceLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldEncryptionNonce, v))
}

// EncryptionNonceLTE applies the LTE predicate on the "encryption_nonce" field.
func EncryptionNonceLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldEncryptionNonce, v))
}

// EncryptionNonceContains applies the Contains predicate on the "encryption_nonce" field.
func EncryptionNonceContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldEncryptionNonce, v))
}

// EncryptionNonceHasPrefix applies the HasPrefix predicate on the "encryption_nonce" field.
func EncryptionNonceHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldEncryptionNonce, v))
}

// EncryptionNonceHasSuffix applies the HasSuffix predicate on the "encryption_nonce" field.
func EncryptionNonceHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldEncryptionNonce, v))
}

// EncryptionNonceIsNil applies the IsNil predicate on the "encryption_nonce" field.
func EncryptionNonceIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldEncryptionNonce))
}

// EncryptionNonceNotNil applies the NotNil predicate on the "encryption_nonce" field.
func EncryptionNonceNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldEncryptionNonce))
}

// EncryptionNonceEqualFold applies the EqualFold predicate on the "encryption_nonce" field.
func EncryptionNonceEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldEncryptionNonce, v))
}

// EncryptionNonceContainsFold applies the ContainsFold predicate on the "encryption_nonce" field.
func EncryptionNonceContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldEncryptionNonce, v))
}

// IsStarredEQ applies the EQ predicate on the "is_starred" field.
func IsStarredEQ(v bool) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldIsStarred, v))
}

// IsStarredNEQ applies the NEQ predicate on the "is_starred" field.
func IsStarredNEQ(v bool) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldIsStarred, v))
}

// IsDeletedEQ applies the EQ predicate on the "is_deleted" field.
func IsDeletedEQ(v bool) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldIsDeleted, v))
}

// IsDeletedNEQ applies the NEQ predicate on the "is_deleted" field.
func IsDeletedNEQ(v bool) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldIsDeleted, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFolder applies the HasEdge predicate on the "folder" edge.
func HasFolder() predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FolderTable, FolderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFolderWith applies the HasEdge predicate on the "folder" edge with a given conditions (other predicates).
func HasFolderWith(preds ...predicate.Folder) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := newFolderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.Attachment) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWhiteboards applies the HasEdge predicate on the "whiteboards" edge.
func HasWhiteboards() predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WhiteboardsTable, WhiteboardsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWhiteboardsWith applies the HasEdge predicate on the "whiteboards" edge with a given conditions (other predicates).
func HasWhiteboardsWith(preds ...predicate.Whiteboard) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := newWhiteboardsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOutgoingLinks applies the HasEdge predicate on the "outgoing_links" edge.
func HasOutgoingLinks() predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OutgoingLinksTable, OutgoingLinksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOutgoingLinksWith applies the HasEdge predicate on the "outgoing_links" edge with a given conditions (other predicates).
func HasOutgoingLinksWith(preds ...predicate.NoteLink) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := newOutgoingLinksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBacklinks applies the HasEdge predicate on the "backlinks" edge.
func HasBacklinks() predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BacklinksTable, BacklinksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBacklinksWith applies the HasEdge predicate on the "backlinks" edge with a given conditions (other predicates).
func HasBacklinksWith(preds ...predicate.NoteLink) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := newBacklinksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.Tag) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Note) predicate.Note {
	return predicate.Note(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Note) predicate.Note {
	return predicate.Note(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Note) predicate.Note {
	return predicate.Note(sql.NotPredicates(p))
}
