// Code generated by ent, DO NOT EDIT.

package backuptarget

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the backuptarget type in the database.
	Label = "backup_target"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldLastBackupStatus holds the string denoting the last_backup_status field in the database.
	FieldLastBackupStatus = "last_backup_status"
	// FieldLastBackupError holds the string denoting the last_backup_error field in the database.
	FieldLastBackupError = "last_backup_error"
	// FieldLastBackupAt holds the string denoting the last_backup_at field in the database.
	FieldLastBackupAt = "last_backup_at"
	// FieldLastTestStatus holds the string denoting the last_test_status field in the database.
	FieldLastTestStatus = "last_test_status"
	// FieldLastTestError holds the string denoting the last_test_error field in the database.
	FieldLastTestError = "last_test_error"
	// FieldLastTestAt holds the string denoting the last_test_at field in the database.
	FieldLastTestAt = "last_test_at"
	// FieldWebdavURL holds the string denoting the webdav_url field in the database.
	FieldWebdavURL = "webdav_url"
	// FieldWebdavUser holds the string denoting the webdav_user field in the database.
	FieldWebdavUser = "webdav_user"
	// FieldWebdavPassword holds the string denoting the webdav_password field in the database.
	FieldWebdavPassword = "webdav_password"
	// FieldS3Endpoint holds the string denoting the s3_endpoint field in the database.
	FieldS3Endpoint = "s3_endpoint"
	// FieldS3Region holds the string denoting the s3_region field in the database.
	FieldS3Region = "s3_region"
	// FieldS3Bucket holds the string denoting the s3_bucket field in the database.
	FieldS3Bucket = "s3_bucket"
	// FieldS3AccessKey holds the string denoting the s3_access_key field in the database.
	FieldS3AccessKey = "s3_access_key"
	// FieldS3SecretKey holds the string denoting the s3_secret_key field in the database.
	FieldS3SecretKey = "s3_secret_key"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// Table holds the table name of the backuptarget in the database.
	Table = "backup_targets"
	// TasksTable is the table that holds the tasks relation/edge. The primary key declared below.
	TasksTable = "backup_task_targets"
	// TasksInverseTable is the table name for the BackupTask entity.
	// It exists in this package in order to avoid circular dependency with the "backuptask" package.
	TasksInverseTable = "backup_tasks"
)

// Columns holds all SQL columns for backuptarget fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldType,
	FieldEnabled,
	FieldLastBackupStatus,
	FieldLastBackupError,
	FieldLastBackupAt,
	FieldLastTestStatus,
	FieldLastTestError,
	FieldLastTestAt,
	FieldWebdavURL,
	FieldWebdavUser,
	FieldWebdavPassword,
	FieldS3Endpoint,
	FieldS3Region,
	FieldS3Bucket,
	FieldS3AccessKey,
	FieldS3SecretKey,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// TasksPrimaryKey and TasksColumn2 are the table columns denoting the
	// primary key for the tasks relation (M2M).
	TasksPrimaryKey = []string{"backup_task_id", "backup_target_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultLastBackupStatus holds the default value on creation for the "last_backup_status" field.
	DefaultLastBackupStatus string
	// DefaultLastTestStatus holds the default value on creation for the "last_test_status" field.
	DefaultLastTestStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the BackupTarget queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByLastBackupStatus orders the results by the last_backup_status field.
func ByLastBackupStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastBackupStatus, opts...).ToFunc()
}

// ByLastBackupError orders the results by the last_backup_error field.
func ByLastBackupError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastBackupError, opts...).ToFunc()
}

// ByLastBackupAt orders the results by the last_backup_at field.
func ByLastBackupAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastBackupAt, opts...).ToFunc()
}

// ByLastTestStatus orders the results by the last_test_status field.
func ByLastTestStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTestStatus, opts...).ToFunc()
}

// ByLastTestError orders the results by the last_test_error field.
func ByLastTestError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTestError, opts...).ToFunc()
}

// ByLastTestAt orders the results by the last_test_at field.
func ByLastTestAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTestAt, opts...).ToFunc()
}

// ByWebdavURL orders the results by the webdav_url field.
func ByWebdavURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavURL, opts...).ToFunc()
}

// ByWebdavUser orders the results by the webdav_user field.
func ByWebdavUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavUser, opts...).ToFunc()
}

// ByWebdavPassword orders the results by the webdav_password field.
func ByWebdavPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebdavPassword, opts...).ToFunc()
}

// ByS3Endpoint orders the results by the s3_endpoint field.
func ByS3Endpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3Endpoint, opts...).ToFunc()
}

// ByS3Region orders the results by the s3_region field.
func ByS3Region(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3Region, opts...).ToFunc()
}

// ByS3Bucket orders the results by the s3_bucket field.
func ByS3Bucket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3Bucket, opts...).ToFunc()
}

// ByS3AccessKey orders the results by the s3_access_key field.
func ByS3AccessKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3AccessKey, opts...).ToFunc()
}

// ByS3SecretKey orders the results by the s3_secret_key field.
func ByS3SecretKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3SecretKey, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, TasksTable, TasksPrimaryKey...),
	)
}
