// Code generated by ent, DO NOT EDIT.

package backuptarget

import (
	"smarticky/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldType, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldEnabled, v))
}

// LastBackupStatus applies equality check predicate on the "last_backup_status" field. It's identical to LastBackupStatusEQ.
func LastBackupStatus(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastBackupStatus, v))
}

// LastBackupError applies equality check predicate on the "last_backup_error" field. It's identical to LastBackupErrorEQ.
func LastBackupError(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastBackupError, v))
}

// LastBackupAt applies equality check predicate on the "last_backup_at" field. It's identical to LastBackupAtEQ.
func LastBackupAt(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastBackupAt, v))
}

// LastTestStatus applies equality check predicate on the "last_test_status" field. It's identical to LastTestStatusEQ.
func LastTestStatus(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastTestStatus, v))
}

// LastTestError applies equality check predicate on the "last_test_error" field. It's identical to LastTestErrorEQ.
func LastTestError(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastTestError, v))
}

// LastTestAt applies equality check predicate on the "last_test_at" field. It's identical to LastTestAtEQ.
func LastTestAt(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastTestAt, v))
}

// WebdavURL applies equality check predicate on the "webdav_url" field. It's identical to WebdavURLEQ.
func WebdavURL(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldWebdavURL, v))
}

// WebdavUser applies equality check predicate on the "webdav_user" field. It's identical to WebdavUserEQ.
func WebdavUser(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldWebdavUser, v))
}

// WebdavPassword applies equality check predicate on the "webdav_password" field. It's identical to WebdavPasswordEQ.
func WebdavPassword(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldWebdavPassword, v))
}

// S3Endpoint applies equality check predicate on the "s3_endpoint" field. It's identical to S3EndpointEQ.
func S3Endpoint(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3Endpoint, v))
}

// S3Region applies equality check predicate on the "s3_region" field. It's identical to S3RegionEQ.
func S3Region(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3Region, v))
}

// S3Bucket applies equality check predicate on the "s3_bucket" field. It's identical to S3BucketEQ.
func S3Bucket(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3Bucket, v))
}

// S3AccessKey applies equality check predicate on the "s3_access_key" field. It's identical to S3AccessKeyEQ.
func S3AccessKey(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3AccessKey, v))
}

// S3SecretKey applies equality check predicate on the "s3_secret_key" field. It's identical to S3SecretKeyEQ.
func S3SecretKey(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3SecretKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldType, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldEnabled, v))
}

// LastBackupStatusEQ applies the EQ predicate on the "last_backup_status" field.
func LastBackupStatusEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastBackupStatus, v))
}

// LastBackupStatusNEQ applies the NEQ predicate on the "last_backup_status" field.
func LastBackupStatusNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldLastBackupStatus, v))
}

// LastBackupStatusIn applies the In predicate on the "last_backup_status" field.
func LastBackupStatusIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldLastBackupStatus, vs...))
}

// LastBackupStatusNotIn applies the NotIn predicate on the "last_backup_status" field.
func LastBackupStatusNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldLastBackupStatus, vs...))
}

// LastBackupStatusGT applies the GT predicate on the "last_backup_status" field.
func LastBackupStatusGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldLastBackupStatus, v))
}

// LastBackupStatusGTE applies the GTE predicate on the "last_backup_status" field.
func LastBackupStatusGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldLastBackupStatus, v))
}

// LastBackupStatusLT applies the LT predicate on the "last_backup_status" field.
func LastBackupStatusLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldLastBackupStatus, v))
}

// LastBackupStatusLTE applies the LTE predicate on the "last_backup_status" field.
func LastBackupStatusLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldLastBackupStatus, v))
}

// LastBackupStatusContains applies the Contains predicate on the "last_backup_status" field.
func LastBackupStatusContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldLastBackupStatus, v))
}

// LastBackupStatusHasPrefix applies the HasPrefix predicate on the "last_backup_status" field.
func LastBackupStatusHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldLastBackupStatus, v))
}

// LastBackupStatusHasSuffix applies the HasSuffix predicate on the "last_backup_status" field.
func LastBackupStatusHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldLastBackupStatus, v))
}

// LastBackupStatusEqualFold applies the EqualFold predicate on the "last_backup_status" field.
func LastBackupStatusEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldLastBackupStatus, v))
}

// LastBackupStatusContainsFold applies the ContainsFold predicate on the "last_backup_status" field.
func LastBackupStatusContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldLastBackupStatus, v))
}

// LastBackupErrorEQ applies the EQ predicate on the "last_backup_error" field.
func LastBackupErrorEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastBackupError, v))
}

// LastBackupErrorNEQ applies the NEQ predicate on the "last_backup_error" field.
func LastBackupErrorNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldLastBackupError, v))
}

// LastBackupErrorIn applies the In predicate on the "last_backup_error" field.
func LastBackupErrorIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldLastBackupError, vs...))
}

// LastBackupErrorNotIn applies the NotIn predicate on the "last_backup_error" field.
func LastBackupErrorNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldLastBackupError, vs...))
}

// LastBackupErrorGT applies the GT predicate on the "last_backup_error" field.
func LastBackupErrorGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldLastBackupError, v))
}

// LastBackupErrorGTE applies the GTE predicate on the "last_backup_error" field.
func LastBackupErrorGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldLastBackupError, v))
}

// LastBackupErrorLT applies the LT predicate on the "last_backup_error" field.
func LastBackupErrorLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldLastBackupError, v))
}

// LastBackupErrorLTE applies the LTE predicate on the "last_backup_error" field.
func LastBackupErrorLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldLastBackupError, v))
}

// LastBackupErrorContains applies the Contains predicate on the "last_backup_error" field.
func LastBackupErrorContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldLastBackupError, v))
}

// LastBackupErrorHasPrefix applies the HasPrefix predicate on the "last_backup_error" field.
func LastBackupErrorHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldLastBackupError, v))
}

// LastBackupErrorHasSuffix applies the HasSuffix predicate on the "last_backup_error" field.
func LastBackupErrorHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldLastBackupError, v))
}

// LastBackupErrorIsNil applies the IsNil predicate on the "last_backup_error" field.
func LastBackupErrorIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldLastBackupError))
}

// LastBackupErrorNotNil applies the NotNil predicate on the "last_backup_error" field.
func LastBackupErrorNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldLastBackupError))
}

// LastBackupErrorEqualFold applies the EqualFold predicate on the "last_backup_error" field.
func LastBackupErrorEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldLastBackupError, v))
}

// LastBackupErrorContainsFold applies the ContainsFold predicate on the "last_backup_error" field.
func LastBackupErrorContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldLastBackupError, v))
}

// LastBackupAtEQ applies the EQ predicate on the "last_backup_at" field.
func LastBackupAtEQ(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastBackupAt, v))
}

// LastBackupAtNEQ applies the NEQ predicate on the "last_backup_at" field.
func LastBackupAtNEQ(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldLastBackupAt, v))
}

// LastBackupAtIn applies the In predicate on the "last_backup_at" field.
func LastBackupAtIn(vs ...time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldLastBackupAt, vs...))
}

// LastBackupAtNotIn applies the NotIn predicate on the "last_backup_at" field.
func LastBackupAtNotIn(vs ...time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldLastBackupAt, vs...))
}

// LastBackupAtGT applies the GT predicate on the "last_backup_at" field.
func LastBackupAtGT(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldLastBackupAt, v))
}

// LastBackupAtGTE applies the GTE predicate on the "last_backup_at" field.
func LastBackupAtGTE(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldLastBackupAt, v))
}

// LastBackupAtLT applies the LT predicate on the "last_backup_at" field.
func LastBackupAtLT(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldLastBackupAt, v))
}

// LastBackupAtLTE applies the LTE predicate on the "last_backup_at" field.
func LastBackupAtLTE(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldLastBackupAt, v))
}

// LastBackupAtIsNil applies the IsNil predicate on the "last_backup_at" field.
func LastBackupAtIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldLastBackupAt))
}

// LastBackupAtNotNil applies the NotNil predicate on the "last_backup_at" field.
func LastBackupAtNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldLastBackupAt))
}

// LastTestStatusEQ applies the EQ predicate on the "last_test_status" field.
func LastTestStatusEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastTestStatus, v))
}

// LastTestStatusNEQ applies the NEQ predicate on the "last_test_status" field.
func LastTestStatusNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldLastTestStatus, v))
}

// LastTestStatusIn applies the In predicate on the "last_test_status" field.
func LastTestStatusIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldLastTestStatus, vs...))
}

// LastTestStatusNotIn applies the NotIn predicate on the "last_test_status" field.
func LastTestStatusNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldLastTestStatus, vs...))
}

// LastTestStatusGT applies the GT predicate on the "last_test_status" field.
func LastTestStatusGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldLastTestStatus, v))
}

// LastTestStatusGTE applies the GTE predicate on the "last_test_status" field.
func LastTestStatusGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldLastTestStatus, v))
}

// LastTestStatusLT applies the LT predicate on the "last_test_status" field.
func LastTestStatusLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldLastTestStatus, v))
}

// LastTestStatusLTE applies the LTE predicate on the "last_test_status" field.
func LastTestStatusLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldLastTestStatus, v))
}

// LastTestStatusContains applies the Contains predicate on the "last_test_status" field.
func LastTestStatusContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldLastTestStatus, v))
}

// LastTestStatusHasPrefix applies the HasPrefix predicate on the "last_test_status" field.
func LastTestStatusHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldLastTestStatus, v))
}

// LastTestStatusHasSuffix applies the HasSuffix predicate on the "last_test_status" field.
func LastTestStatusHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldLastTestStatus, v))
}

// LastTestStatusEqualFold applies the EqualFold predicate on the "last_test_status" field.
func LastTestStatusEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldLastTestStatus, v))
}

// LastTestStatusContainsFold applies the ContainsFold predicate on the "last_test_status" field.
func LastTestStatusContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldLastTestStatus, v))
}

// LastTestErrorEQ applies the EQ predicate on the "last_test_error" field.
func LastTestErrorEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastTestError, v))
}

// LastTestErrorNEQ applies the NEQ predicate on the "last_test_error" field.
func LastTestErrorNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldLastTestError, v))
}

// LastTestErrorIn applies the In predicate on the "last_test_error" field.
func LastTestErrorIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldLastTestError, vs...))
}

// LastTestErrorNotIn applies the NotIn predicate on the "last_test_error" field.
func LastTestErrorNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldLastTestError, vs...))
}

// LastTestErrorGT applies the GT predicate on the "last_test_error" field.
func LastTestErrorGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldLastTestError, v))
}

// LastTestErrorGTE applies the GTE predicate on the "last_test_error" field.
func LastTestErrorGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldLastTestError, v))
}

// LastTestErrorLT applies the LT predicate on the "last_test_error" field.
func LastTestErrorLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldLastTestError, v))
}

// LastTestErrorLTE applies the LTE predicate on the "last_test_error" field.
func LastTestErrorLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldLastTestError, v))
}

// LastTestErrorContains applies the Contains predicate on the "last_test_error" field.
func LastTestErrorContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldLastTestError, v))
}

// LastTestErrorHasPrefix applies the HasPrefix predicate on the "last_test_error" field.
func LastTestErrorHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldLastTestError, v))
}

// LastTestErrorHasSuffix applies the HasSuffix predicate on the "last_test_error" field.
func LastTestErrorHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldLastTestError, v))
}

// LastTestErrorIsNil applies the IsNil predicate on the "last_test_error" field.
func LastTestErrorIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldLastTestError))
}

// LastTestErrorNotNil applies the NotNil predicate on the "last_test_error" field.
func LastTestErrorNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldLastTestError))
}

// LastTestErrorEqualFold applies the EqualFold predicate on the "last_test_error" field.
func LastTestErrorEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldLastTestError, v))
}

// LastTestErrorContainsFold applies the ContainsFold predicate on the "last_test_error" field.
func LastTestErrorContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldLastTestError, v))
}

// LastTestAtEQ applies the EQ predicate on the "last_test_at" field.
func LastTestAtEQ(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldLastTestAt, v))
}

// LastTestAtNEQ applies the NEQ predicate on the "last_test_at" field.
func LastTestAtNEQ(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldLastTestAt, v))
}

// LastTestAtIn applies the In predicate on the "last_test_at" field.
func LastTestAtIn(vs ...time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldLastTestAt, vs...))
}

// LastTestAtNotIn applies the NotIn predicate on the "last_test_at" field.
func LastTestAtNotIn(vs ...time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldLastTestAt, vs...))
}

// LastTestAtGT applies the GT predicate on the "last_test_at" field.
func LastTestAtGT(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldLastTestAt, v))
}

// LastTestAtGTE applies the GTE predicate on the "last_test_at" field.
func LastTestAtGTE(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldLastTestAt, v))
}

// LastTestAtLT applies the LT predicate on the "last_test_at" field.
func LastTestAtLT(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldLastTestAt, v))
}

// LastTestAtLTE applies the LTE predicate on the "last_test_at" field.
func LastTestAtLTE(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldLastTestAt, v))
}

// LastTestAtIsNil applies the IsNil predicate on the "last_test_at" field.
func LastTestAtIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldLastTestAt))
}

// LastTestAtNotNil applies the NotNil predicate on the "last_test_at" field.
func LastTestAtNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldLastTestAt))
}

// WebdavURLEQ applies the EQ predicate on the "webdav_url" field.
func WebdavURLEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldWebdavURL, v))
}

// WebdavURLNEQ applies the NEQ predicate on the "webdav_url" field.
func WebdavURLNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldWebdavURL, v))
}

// WebdavURLIn applies the In predicate on the "webdav_url" field.
func WebdavURLIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldWebdavURL, vs...))
}

// WebdavURLNotIn applies the NotIn predicate on the "webdav_url" field.
func WebdavURLNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldWebdavURL, vs...))
}

// WebdavURLGT applies the GT predicate on the "webdav_url" field.
func WebdavURLGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldWebdavURL, v))
}

// WebdavURLGTE applies the GTE predicate on the "webdav_url" field.
func WebdavURLGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldWebdavURL, v))
}

// WebdavURLLT applies the LT predicate on the "webdav_url" field.
func WebdavURLLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldWebdavURL, v))
}

// WebdavURLLTE applies the LTE predicate on the "webdav_url" field.
func WebdavURLLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldWebdavURL, v))
}

// WebdavURLContains applies the Contains predicate on the "webdav_url" field.
func WebdavURLContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldWebdavURL, v))
}

// WebdavURLHasPrefix applies the HasPrefix predicate on the "webdav_url" field.
func WebdavURLHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldWebdavURL, v))
}

// WebdavURLHasSuffix applies the HasSuffix predicate on the "webdav_url" field.
func WebdavURLHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldWebdavURL, v))
}

// WebdavURLIsNil applies the IsNil predicate on the "webdav_url" field.
func WebdavURLIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldWebdavURL))
}

// WebdavURLNotNil applies the NotNil predicate on the "webdav_url" field.
func WebdavURLNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldWebdavURL))
}

// WebdavURLEqualFold applies the EqualFold predicate on the "webdav_url" field.
func WebdavURLEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldWebdavURL, v))
}

// WebdavURLContainsFold applies the ContainsFold predicate on the "webdav_url" field.
func WebdavURLContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldWebdavURL, v))
}

// WebdavUserEQ applies the EQ predicate on the "webdav_user" field.
func WebdavUserEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldWebdavUser, v))
}

// WebdavUserNEQ applies the NEQ predicate on the "webdav_user" field.
func WebdavUserNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldWebdavUser, v))
}

// WebdavUserIn applies the In predicate on the "webdav_user" field.
func WebdavUserIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldWebdavUser, vs...))
}

// WebdavUserNotIn applies the NotIn predicate on the "webdav_user" field.
func WebdavUserNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldWebdavUser, vs...))
}

// WebdavUserGT applies the GT predicate on the "webdav_user" field.
func WebdavUserGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldWebdavUser, v))
}

// WebdavUserGTE applies the GTE predicate on the "webdav_user" field.
func WebdavUserGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldWebdavUser, v))
}

// WebdavUserLT applies the LT predicate on the "webdav_user" field.
func WebdavUserLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldWebdavUser, v))
}

// WebdavUserLTE applies the LTE predicate on the "webdav_user" field.
func WebdavUserLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldWebdavUser, v))
}

// WebdavUserContains applies the Contains predicate on the "webdav_user" field.
func WebdavUserContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldWebdavUser, v))
}

// WebdavUserHasPrefix applies the HasPrefix predicate on the "webdav_user" field.
func WebdavUserHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldWebdavUser, v))
}

// WebdavUserHasSuffix applies the HasSuffix predicate on the "webdav_user" field.
func WebdavUserHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldWebdavUser, v))
}

// WebdavUserIsNil applies the IsNil predicate on the "webdav_user" field.
func WebdavUserIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldWebdavUser))
}

// WebdavUserNotNil applies the NotNil predicate on the "webdav_user" field.
func WebdavUserNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldWebdavUser))
}

// WebdavUserEqualFold applies the EqualFold predicate on the "webdav_user" field.
func WebdavUserEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldWebdavUser, v))
}

// WebdavUserContainsFold applies the ContainsFold predicate on the "webdav_user" field.
func WebdavUserContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldWebdavUser, v))
}

// WebdavPasswordEQ applies the EQ predicate on the "webdav_password" field.
func WebdavPasswordEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldWebdavPassword, v))
}

// WebdavPasswordNEQ applies the NEQ predicate on the "webdav_password" field.
func WebdavPasswordNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldWebdavPassword, v))
}

// WebdavPasswordIn applies the In predicate on the "webdav_password" field.
func WebdavPasswordIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldWebdavPassword, vs...))
}

// WebdavPasswordNotIn applies the NotIn predicate on the "webdav_password" field.
func WebdavPasswordNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldWebdavPassword, vs...))
}

// WebdavPasswordGT applies the GT predicate on the "webdav_password" field.
func WebdavPasswordGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldWebdavPassword, v))
}

// WebdavPasswordGTE applies the GTE predicate on the "webdav_password" field.
func WebdavPasswordGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldWebdavPassword, v))
}

// WebdavPasswordLT applies the LT predicate on the "webdav_password" field.
func WebdavPasswordLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldWebdavPassword, v))
}

// WebdavPasswordLTE applies the LTE predicate on the "webdav_password" field.
func WebdavPasswordLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldWebdavPassword, v))
}

// WebdavPasswordContains applies the Contains predicate on the "webdav_password" field.
func WebdavPasswordContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldWebdavPassword, v))
}

// WebdavPasswordHasPrefix applies the HasPrefix predicate on the "webdav_password" field.
func WebdavPasswordHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldWebdavPassword, v))
}

// WebdavPasswordHasSuffix applies the HasSuffix predicate on the "webdav_password" field.
func WebdavPasswordHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldWebdavPassword, v))
}

// WebdavPasswordIsNil applies the IsNil predicate on the "webdav_password" field.
func WebdavPasswordIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldWebdavPassword))
}

// WebdavPasswordNotNil applies the NotNil predicate on the "webdav_password" field.
func WebdavPasswordNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldWebdavPassword))
}

// WebdavPasswordEqualFold applies the EqualFold predicate on the "webdav_password" field.
func WebdavPasswordEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldWebdavPassword, v))
}

// WebdavPasswordContainsFold applies the ContainsFold predicate on the "webdav_password" field.
func WebdavPasswordContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldWebdavPassword, v))
}

// S3EndpointEQ applies the EQ predicate on the "s3_endpoint" field.
func S3EndpointEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3Endpoint, v))
}

// S3EndpointNEQ applies the NEQ predicate on the "s3_endpoint" field.
func S3EndpointNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldS3Endpoint, v))
}

// S3EndpointIn applies the In predicate on the "s3_endpoint" field.
func S3EndpointIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldS3Endpoint, vs...))
}

// S3EndpointNotIn applies the NotIn predicate on the "s3_endpoint" field.
func S3EndpointNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldS3Endpoint, vs...))
}

// S3EndpointGT applies the GT predicate on the "s3_endpoint" field.
func S3EndpointGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldS3Endpoint, v))
}

// S3EndpointGTE applies the GTE predicate on the "s3_endpoint" field.
func S3EndpointGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldS3Endpoint, v))
}

// S3EndpointLT applies the LT predicate on the "s3_endpoint" field.
func S3EndpointLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldS3Endpoint, v))
}

// S3EndpointLTE applies the LTE predicate on the "s3_endpoint" field.
func S3EndpointLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldS3Endpoint, v))
}

// S3EndpointContains applies the Contains predicate on the "s3_endpoint" field.
func S3EndpointContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldS3Endpoint, v))
}

// S3EndpointHasPrefix applies the HasPrefix predicate on the "s3_endpoint" field.
func S3EndpointHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldS3Endpoint, v))
}

// S3EndpointHasSuffix applies the HasSuffix predicate on the "s3_endpoint" field.
func S3EndpointHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldS3Endpoint, v))
}

// S3EndpointIsNil applies the IsNil predicate on the "s3_endpoint" field.
func S3EndpointIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldS3Endpoint))
}

// S3EndpointNotNil applies the NotNil predicate on the "s3_endpoint" field.
func S3EndpointNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldS3Endpoint))
}

// S3EndpointEqualFold applies the EqualFold predicate on the "s3_endpoint" field.
func S3EndpointEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldS3Endpoint, v))
}

// S3EndpointContainsFold applies the ContainsFold predicate on the "s3_endpoint" field.
func S3EndpointContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldS3Endpoint, v))
}

// S3RegionEQ applies the EQ predicate on the "s3_region" field.
func S3RegionEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3Region, v))
}

// S3RegionNEQ applies the NEQ predicate on the "s3_region" field.
func S3RegionNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldS3Region, v))
}

// S3RegionIn applies the In predicate on the "s3_region" field.
func S3RegionIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldS3Region, vs...))
}

// S3RegionNotIn applies the NotIn predicate on the "s3_region" field.
func S3RegionNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldS3Region, vs...))
}

// S3RegionGT applies the GT predicate on the "s3_region" field.
func S3RegionGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldS3Region, v))
}

// S3RegionGTE applies the GTE predicate on the "s3_region" field.
func S3RegionGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldS3Region, v))
}

// S3RegionLT applies the LT predicate on the "s3_region" field.
func S3RegionLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldS3Region, v))
}

// S3RegionLTE applies the LTE predicate on the "s3_region" field.
func S3RegionLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldS3Region, v))
}

// S3RegionContains applies the Contains predicate on the "s3_region" field.
func S3RegionContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldS3Region, v))
}

// S3RegionHasPrefix applies the HasPrefix predicate on the "s3_region" field.
func S3RegionHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldS3Region, v))
}

// S3RegionHasSuffix applies the HasSuffix predicate on the "s3_region" field.
func S3RegionHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldS3Region, v))
}

// S3RegionIsNil applies the IsNil predicate on the "s3_region" field.
func S3RegionIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldS3Region))
}

// S3RegionNotNil applies the NotNil predicate on the "s3_region" field.
func S3RegionNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldS3Region))
}

// S3RegionEqualFold applies the EqualFold predicate on the "s3_region" field.
func S3RegionEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldS3Region, v))
}

// S3RegionContainsFold applies the ContainsFold predicate on the "s3_region" field.
func S3RegionContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldS3Region, v))
}

// S3BucketEQ applies the EQ predicate on the "s3_bucket" field.
func S3BucketEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3Bucket, v))
}

// S3BucketNEQ applies the NEQ predicate on the "s3_bucket" field.
func S3BucketNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldS3Bucket, v))
}

// S3BucketIn applies the In predicate on the "s3_bucket" field.
func S3BucketIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldS3Bucket, vs...))
}

// S3BucketNotIn applies the NotIn predicate on the "s3_bucket" field.
func S3BucketNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldS3Bucket, vs...))
}

// S3BucketGT applies the GT predicate on the "s3_bucket" field.
func S3BucketGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldS3Bucket, v))
}

// S3BucketGTE applies the GTE predicate on the "s3_bucket" field.
func S3BucketGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldS3Bucket, v))
}

// S3BucketLT applies the LT predicate on the "s3_bucket" field.
func S3BucketLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldS3Bucket, v))
}

// S3BucketLTE applies the LTE predicate on the "s3_bucket" field.
func S3BucketLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldS3Bucket, v))
}

// S3BucketContains applies the Contains predicate on the "s3_bucket" field.
func S3BucketContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldS3Bucket, v))
}

// S3BucketHasPrefix applies the HasPrefix predicate on the "s3_bucket" field.
func S3BucketHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldS3Bucket, v))
}

// S3BucketHasSuffix applies the HasSuffix predicate on the "s3_bucket" field.
func S3BucketHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldS3Bucket, v))
}

// S3BucketIsNil applies the IsNil predicate on the "s3_bucket" field.
func S3BucketIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldS3Bucket))
}

// S3BucketNotNil applies the NotNil predicate on the "s3_bucket" field.
func S3BucketNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldS3Bucket))
}

// S3BucketEqualFold applies the EqualFold predicate on the "s3_bucket" field.
func S3BucketEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldS3Bucket, v))
}

// S3BucketContainsFold applies the ContainsFold predicate on the "s3_bucket" field.
func S3BucketContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldS3Bucket, v))
}

// S3AccessKeyEQ applies the EQ predicate on the "s3_access_key" field.
func S3AccessKeyEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3AccessKey, v))
}

// S3AccessKeyNEQ applies the NEQ predicate on the "s3_access_key" field.
func S3AccessKeyNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldS3AccessKey, v))
}

// S3AccessKeyIn applies the In predicate on the "s3_access_key" field.
func S3AccessKeyIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldS3AccessKey, vs...))
}

// S3AccessKeyNotIn applies the NotIn predicate on the "s3_access_key" field.
func S3AccessKeyNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldS3AccessKey, vs...))
}

// S3AccessKeyGT applies the GT predicate on the "s3_access_key" field.
func S3AccessKeyGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldS3AccessKey, v))
}

// S3AccessKeyGTE applies the GTE predicate on the "s3_access_key" field.
func S3AccessKeyGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldS3AccessKey, v))
}

// S3AccessKeyLT applies the LT predicate on the "s3_access_key" field.
func S3AccessKeyLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldS3AccessKey, v))
}

// S3AccessKeyLTE applies the LTE predicate on the "s3_access_key" field.
func S3AccessKeyLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldS3AccessKey, v))
}

// S3AccessKeyContains applies the Contains predicate on the "s3_access_key" field.
func S3AccessKeyContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldS3AccessKey, v))
}

// S3AccessKeyHasPrefix applies the HasPrefix predicate on the "s3_access_key" field.
func S3AccessKeyHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldS3AccessKey, v))
}

// S3AccessKeyHasSuffix applies the HasSuffix predicate on the "s3_access_key" field.
func S3AccessKeyHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldS3AccessKey, v))
}

// S3AccessKeyIsNil applies the IsNil predicate on the "s3_access_key" field.
func S3AccessKeyIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldS3AccessKey))
}

// S3AccessKeyNotNil applies the NotNil predicate on the "s3_access_key" field.
func S3AccessKeyNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldS3AccessKey))
}

// S3AccessKeyEqualFold applies the EqualFold predicate on the "s3_access_key" field.
func S3AccessKeyEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldS3AccessKey, v))
}

// S3AccessKeyContainsFold applies the ContainsFold predicate on the "s3_access_key" field.
func S3AccessKeyContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldS3AccessKey, v))
}

// S3SecretKeyEQ applies the EQ predicate on the "s3_secret_key" field.
func S3SecretKeyEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldS3SecretKey, v))
}

// S3SecretKeyNEQ applies the NEQ predicate on the "s3_secret_key" field.
func S3SecretKeyNEQ(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldS3SecretKey, v))
}

// S3SecretKeyIn applies the In predicate on the "s3_secret_key" field.
func S3SecretKeyIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldS3SecretKey, vs...))
}

// S3SecretKeyNotIn applies the NotIn predicate on the "s3_secret_key" field.
func S3SecretKeyNotIn(vs ...string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldS3SecretKey, vs...))
}

// S3SecretKeyGT applies the GT predicate on the "s3_secret_key" field.
func S3SecretKeyGT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldS3SecretKey, v))
}

// S3SecretKeyGTE applies the GTE predicate on the "s3_secret_key" field.
func S3SecretKeyGTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldS3SecretKey, v))
}

// S3SecretKeyLT applies the LT predicate on the "s3_secret_key" field.
func S3SecretKeyLT(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldS3SecretKey, v))
}

// S3SecretKeyLTE applies the LTE predicate on the "s3_secret_key" field.
func S3SecretKeyLTE(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldS3SecretKey, v))
}

// S3SecretKeyContains applies the Contains predicate on the "s3_secret_key" field.
func S3SecretKeyContains(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContains(FieldS3SecretKey, v))
}

// S3SecretKeyHasPrefix applies the HasPrefix predicate on the "s3_secret_key" field.
func S3SecretKeyHasPrefix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasPrefix(FieldS3SecretKey, v))
}

// S3SecretKeyHasSuffix applies the HasSuffix predicate on the "s3_secret_key" field.
func S3SecretKeyHasSuffix(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldHasSuffix(FieldS3SecretKey, v))
}

// S3SecretKeyIsNil applies the IsNil predicate on the "s3_secret_key" field.
func S3SecretKeyIsNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIsNull(FieldS3SecretKey))
}

// S3SecretKeyNotNil applies the NotNil predicate on the "s3_secret_key" field.
func S3SecretKeyNotNil() predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotNull(FieldS3SecretKey))
}

// S3SecretKeyEqualFold applies the EqualFold predicate on the "s3_secret_key" field.
func S3SecretKeyEqualFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEqualFold(FieldS3SecretKey, v))
}

// S3SecretKeyContainsFold applies the ContainsFold predicate on the "s3_secret_key" field.
func S3SecretKeyContainsFold(v string) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldContainsFold(FieldS3SecretKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BackupTarget {
	return predicate.BackupTarget(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.BackupTarget {
	return predicate.BackupTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, TasksTable, TasksPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.BackupTask) predicate.BackupTarget {
	return predicate.BackupTarget(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BackupTarget) predicate.BackupTarget {
	return predicate.BackupTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BackupTarget) predicate.BackupTarget {
	return predicate.BackupTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BackupTarget) predicate.BackupTarget {
	return predicate.BackupTarget(sql.NotPredicates(p))
}
