// Code generated by ent, DO NOT EDIT.

package noteconnectionaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the noteconnectionaccount type in the database.
	Label = "note_connection_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldAuthType holds the string denoting the auth_type field in the database.
	FieldAuthType = "auth_type"
	// FieldEncryptedCredentials holds the string denoting the encrypted_credentials field in the database.
	FieldEncryptedCredentials = "encrypted_credentials"
	// FieldCredentialAlg holds the string denoting the credential_alg field in the database.
	FieldCredentialAlg = "credential_alg"
	// FieldDefaultTargetID holds the string denoting the default_target_id field in the database.
	FieldDefaultTargetID = "default_target_id"
	// FieldDefaultTargetName holds the string denoting the default_target_name field in the database.
	FieldDefaultTargetName = "default_target_name"
	// FieldMetadataJSON holds the string denoting the metadata_json field in the database.
	FieldMetadataJSON = "metadata_json"
	// FieldLastTestStatus holds the string denoting the last_test_status field in the database.
	FieldLastTestStatus = "last_test_status"
	// FieldLastTestError holds the string denoting the last_test_error field in the database.
	FieldLastTestError = "last_test_error"
	// FieldLastTestAt holds the string denoting the last_test_at field in the database.
	FieldLastTestAt = "last_test_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeItemMaps holds the string denoting the item_maps edge name in mutations.
	EdgeItemMaps = "item_maps"
	// EdgeJobs holds the string denoting the jobs edge name in mutations.
	EdgeJobs = "jobs"
	// Table holds the table name of the noteconnectionaccount in the database.
	Table = "note_connection_accounts"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "note_connection_accounts"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ItemMapsTable is the table that holds the item_maps relation/edge.
	ItemMapsTable = "note_connection_item_maps"
	// ItemMapsInverseTable is the table name for the NoteConnectionItemMap entity.
	// It exists in this package in order to avoid circular dependency with the "noteconnectionitemmap" package.
	ItemMapsInverseTable = "note_connection_item_maps"
	// ItemMapsColumn is the table column denoting the item_maps relation/edge.
	ItemMapsColumn = "account_id"
	// JobsTable is the table that holds the jobs relation/edge.
	JobsTable = "note_connection_jobs"
	// JobsInverseTable is the table name for the NoteConnectionJob entity.
	// It exists in this package in order to avoid circular dependency with the "noteconnectionjob" package.
	JobsInverseTable = "note_connection_jobs"
	// JobsColumn is the table column denoting the jobs relation/edge.
	JobsColumn = "account_id"
)

// Columns holds all SQL columns for noteconnectionaccount fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldProvider,
	FieldUserID,
	FieldEndpoint,
	FieldEnabled,
	FieldAuthType,
	FieldEncryptedCredentials,
	FieldCredentialAlg,
	FieldDefaultTargetID,
	FieldDefaultTargetName,
	FieldMetadataJSON,
	FieldLastTestStatus,
	FieldLastTestError,
	FieldLastTestAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultAuthType holds the default value on creation for the "auth_type" field.
	DefaultAuthType string
	// DefaultLastTestStatus holds the default value on creation for the "last_test_status" field.
	DefaultLastTestStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the NoteConnectionAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByAuthType orders the results by the auth_type field.
func ByAuthType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthType, opts...).ToFunc()
}

// ByEncryptedCredentials orders the results by the encrypted_credentials field.
func ByEncryptedCredentials(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedCredentials, opts...).ToFunc()
}

// ByCredentialAlg orders the results by the credential_alg field.
func ByCredentialAlg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialAlg, opts...).ToFunc()
}

// ByDefaultTargetID orders the results by the default_target_id field.
func ByDefaultTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultTargetID, opts...).ToFunc()
}

// ByDefaultTargetName orders the results by the default_target_name field.
func ByDefaultTargetName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultTargetName, opts...).ToFunc()
}

// ByMetadataJSON orders the results by the metadata_json field.
func ByMetadataJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataJSON, opts...).ToFunc()
}

// ByLastTestStatus orders the results by the last_test_status field.
func ByLastTestStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTestStatus, opts...).ToFunc()
}

// ByLastTestError orders the results by the last_test_error field.
func ByLastTestError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTestError, opts...).ToFunc()
}

// ByLastTestAt orders the results by the last_test_at field.
func ByLastTestAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTestAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByItemMapsCount orders the results by item_maps count.
func ByItemMapsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newItemMapsStep(), opts...)
	}
}

// ByItemMaps orders the results by item_maps terms.
func ByItemMaps(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemMapsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByJobsCount orders the results by jobs count.
func ByJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJobsStep(), opts...)
	}
}

// ByJobs orders the results by jobs terms.
func ByJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newItemMapsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemMapsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ItemMapsTable, ItemMapsColumn),
	)
}
func newJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JobsTable, JobsColumn),
	)
}
