// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"smarticky/ent/backuptask"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BackupTask is the model entity for the BackupTask schema.
type BackupTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// manual, daily, weekly, monthly
	Schedule string `json:"schedule,omitempty"`
	// Number of days to retain backup files (0 = no limit)
	RetentionDays int `json:"retention_days,omitempty"`
	// Maximum number of backup files to keep (0 = no limit)
	MaxCount int `json:"max_count,omitempty"`
	// never, success, failed
	LastBackupStatus string `json:"last_backup_status,omitempty"`
	// LastBackupError holds the value of the "last_backup_error" field.
	LastBackupError string `json:"last_backup_error,omitempty"`
	// LastBackupAt holds the value of the "last_backup_at" field.
	LastBackupAt time.Time `json:"last_backup_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BackupTaskQuery when eager-loading is set.
	Edges        BackupTaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BackupTaskEdges holds the relations/edges for other nodes in the graph.
type BackupTaskEdges struct {
	// Targets holds the value of the targets edge.
	Targets []*BackupTarget `json:"targets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TargetsOrErr returns the Targets value or an error if the edge
// was not loaded in eager-loading.
func (e BackupTaskEdges) TargetsOrErr() ([]*BackupTarget, error) {
	if e.loadedTypes[0] {
		return e.Targets, nil
	}
	return nil, &NotLoadedError{edge: "targets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BackupTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backuptask.FieldEnabled:
			values[i] = new(sql.NullBool)
		case backuptask.FieldID, backuptask.FieldRetentionDays, backuptask.FieldMaxCount:
			values[i] = new(sql.NullInt64)
		case backuptask.FieldName, backuptask.FieldSchedule, backuptask.FieldLastBackupStatus, backuptask.FieldLastBackupError:
			values[i] = new(sql.NullString)
		case backuptask.FieldLastBackupAt, backuptask.FieldCreatedAt, backuptask.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BackupTask fields.
func (_m *BackupTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backuptask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case backuptask.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case backuptask.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case backuptask.FieldSchedule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field schedule", values[i])
			} else if value.Valid {
				_m.Schedule = value.String
			}
		case backuptask.FieldRetentionDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retention_days", values[i])
			} else if value.Valid {
				_m.RetentionDays = int(value.Int64)
			}
		case backuptask.FieldMaxCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_count", values[i])
			} else if value.Valid {
				_m.MaxCount = int(value.Int64)
			}
		case backuptask.FieldLastBackupStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_backup_status", values[i])
			} else if value.Valid {
				_m.LastBackupStatus = value.String
			}
		case backuptask.FieldLastBackupError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_backup_error", values[i])
			} else if value.Valid {
				_m.LastBackupError = value.String
			}
		case backuptask.FieldLastBackupAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_backup_at", values[i])
			} else if value.Valid {
				_m.LastBackupAt = value.Time
			}
		case backuptask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case backuptask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BackupTask.
// This includes values selected through modifiers, order, etc.
func (_m *BackupTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTargets queries the "targets" edge of the BackupTask entity.
func (_m *BackupTask) QueryTargets() *BackupTargetQuery {
	return NewBackupTaskClient(_m.config).QueryTargets(_m)
}

// Update returns a builder for updating this BackupTask.
// Note that you need to call BackupTask.Unwrap() before calling this method if this BackupTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BackupTask) Update() *BackupTaskUpdateOne {
	return NewBackupTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BackupTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BackupTask) Unwrap() *BackupTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BackupTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BackupTask) String() string {
	var builder strings.Builder
	builder.WriteString("BackupTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("schedule=")
	builder.WriteString(_m.Schedule)
	builder.WriteString(", ")
	builder.WriteString("retention_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetentionDays))
	builder.WriteString(", ")
	builder.WriteString("max_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxCount))
	builder.WriteString(", ")
	builder.WriteString("last_backup_status=")
	builder.WriteString(_m.LastBackupStatus)
	builder.WriteString(", ")
	builder.WriteString("last_backup_error=")
	builder.WriteString(_m.LastBackupError)
	builder.WriteString(", ")
	builder.WriteString("last_backup_at=")
	builder.WriteString(_m.LastBackupAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BackupTasks is a parsable slice of BackupTask.
type BackupTasks []*BackupTask
