// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"smarticky/ent/migrate"

	"smarticky/ent/attachment"
	"smarticky/ent/backupconfig"
	"smarticky/ent/font"
	"smarticky/ent/importitem"
	"smarticky/ent/importjob"
	"smarticky/ent/mcpimage"
	"smarticky/ent/mcptoken"
	"smarticky/ent/note"
	"smarticky/ent/tag"
	"smarticky/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Attachment is the client for interacting with the Attachment builders.
	Attachment *AttachmentClient
	// BackupConfig is the client for interacting with the BackupConfig builders.
	BackupConfig *BackupConfigClient
	// Font is the client for interacting with the Font builders.
	Font *FontClient
	// ImportItem is the client for interacting with the ImportItem builders.
	ImportItem *ImportItemClient
	// ImportJob is the client for interacting with the ImportJob builders.
	ImportJob *ImportJobClient
	// MCPImage is the client for interacting with the MCPImage builders.
	MCPImage *MCPImageClient
	// MCPToken is the client for interacting with the MCPToken builders.
	MCPToken *MCPTokenClient
	// Note is the client for interacting with the Note builders.
	Note *NoteClient
	// Tag is the client for interacting with the Tag builders.
	Tag *TagClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Attachment = NewAttachmentClient(c.config)
	c.BackupConfig = NewBackupConfigClient(c.config)
	c.Font = NewFontClient(c.config)
	c.ImportItem = NewImportItemClient(c.config)
	c.ImportJob = NewImportJobClient(c.config)
	c.MCPImage = NewMCPImageClient(c.config)
	c.MCPToken = NewMCPTokenClient(c.config)
	c.Note = NewNoteClient(c.config)
	c.Tag = NewTagClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Attachment:   NewAttachmentClient(cfg),
		BackupConfig: NewBackupConfigClient(cfg),
		Font:         NewFontClient(cfg),
		ImportItem:   NewImportItemClient(cfg),
		ImportJob:    NewImportJobClient(cfg),
		MCPImage:     NewMCPImageClient(cfg),
		MCPToken:     NewMCPTokenClient(cfg),
		Note:         NewNoteClient(cfg),
		Tag:          NewTagClient(cfg),
		User:         NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Attachment:   NewAttachmentClient(cfg),
		BackupConfig: NewBackupConfigClient(cfg),
		Font:         NewFontClient(cfg),
		ImportItem:   NewImportItemClient(cfg),
		ImportJob:    NewImportJobClient(cfg),
		MCPImage:     NewMCPImageClient(cfg),
		MCPToken:     NewMCPTokenClient(cfg),
		Note:         NewNoteClient(cfg),
		Tag:          NewTagClient(cfg),
		User:         NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Attachment.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Attachment, c.BackupConfig, c.Font, c.ImportItem, c.ImportJob, c.MCPImage,
		c.MCPToken, c.Note, c.Tag, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Attachment, c.BackupConfig, c.Font, c.ImportItem, c.ImportJob, c.MCPImage,
		c.MCPToken, c.Note, c.Tag, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AttachmentMutation:
		return c.Attachment.mutate(ctx, m)
	case *BackupConfigMutation:
		return c.BackupConfig.mutate(ctx, m)
	case *FontMutation:
		return c.Font.mutate(ctx, m)
	case *ImportItemMutation:
		return c.ImportItem.mutate(ctx, m)
	case *ImportJobMutation:
		return c.ImportJob.mutate(ctx, m)
	case *MCPImageMutation:
		return c.MCPImage.mutate(ctx, m)
	case *MCPTokenMutation:
		return c.MCPToken.mutate(ctx, m)
	case *NoteMutation:
		return c.Note.mutate(ctx, m)
	case *TagMutation:
		return c.Tag.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AttachmentClient is a client for the Attachment schema.
type AttachmentClient struct {
	config
}

// NewAttachmentClient returns a client for the Attachment from the given config.
func NewAttachmentClient(c config) *AttachmentClient {
	return &AttachmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `attachment.Hooks(f(g(h())))`.
func (c *AttachmentClient) Use(hooks ...Hook) {
	c.hooks.Attachment = append(c.hooks.Attachment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `attachment.Intercept(f(g(h())))`.
func (c *AttachmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Attachment = append(c.inters.Attachment, interceptors...)
}

// Create returns a builder for creating a Attachment entity.
func (c *AttachmentClient) Create() *AttachmentCreate {
	mutation := newAttachmentMutation(c.config, OpCreate)
	return &AttachmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Attachment entities.
func (c *AttachmentClient) CreateBulk(builders ...*AttachmentCreate) *AttachmentCreateBulk {
	return &AttachmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AttachmentClient) MapCreateBulk(slice any, setFunc func(*AttachmentCreate, int)) *AttachmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AttachmentCreateBulk{err: fmt.Errorf("calling to AttachmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AttachmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AttachmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Attachment.
func (c *AttachmentClient) Update() *AttachmentUpdate {
	mutation := newAttachmentMutation(c.config, OpUpdate)
	return &AttachmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AttachmentClient) UpdateOne(_m *Attachment) *AttachmentUpdateOne {
	mutation := newAttachmentMutation(c.config, OpUpdateOne, withAttachment(_m))
	return &AttachmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AttachmentClient) UpdateOneID(id int) *AttachmentUpdateOne {
	mutation := newAttachmentMutation(c.config, OpUpdateOne, withAttachmentID(id))
	return &AttachmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Attachment.
func (c *AttachmentClient) Delete() *AttachmentDelete {
	mutation := newAttachmentMutation(c.config, OpDelete)
	return &AttachmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AttachmentClient) DeleteOne(_m *Attachment) *AttachmentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AttachmentClient) DeleteOneID(id int) *AttachmentDeleteOne {
	builder := c.Delete().Where(attachment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AttachmentDeleteOne{builder}
}

// Query returns a query builder for Attachment.
func (c *AttachmentClient) Query() *AttachmentQuery {
	return &AttachmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAttachment},
		inters: c.Interceptors(),
	}
}

// Get returns a Attachment entity by its id.
func (c *AttachmentClient) Get(ctx context.Context, id int) (*Attachment, error) {
	return c.Query().Where(attachment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AttachmentClient) GetX(ctx context.Context, id int) *Attachment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNote queries the note edge of a Attachment.
func (c *AttachmentClient) QueryNote(_m *Attachment) *NoteQuery {
	query := (&NoteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attachment.Table, attachment.FieldID, id),
			sqlgraph.To(note.Table, note.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attachment.NoteTable, attachment.NoteColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a Attachment.
func (c *AttachmentClient) QueryUser(_m *Attachment) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attachment.Table, attachment.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attachment.UserTable, attachment.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AttachmentClient) Hooks() []Hook {
	return c.hooks.Attachment
}

// Interceptors returns the client interceptors.
func (c *AttachmentClient) Interceptors() []Interceptor {
	return c.inters.Attachment
}

func (c *AttachmentClient) mutate(ctx context.Context, m *AttachmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AttachmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AttachmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AttachmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AttachmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Attachment mutation op: %q", m.Op())
	}
}

// BackupConfigClient is a client for the BackupConfig schema.
type BackupConfigClient struct {
	config
}

// NewBackupConfigClient returns a client for the BackupConfig from the given config.
func NewBackupConfigClient(c config) *BackupConfigClient {
	return &BackupConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `backupconfig.Hooks(f(g(h())))`.
func (c *BackupConfigClient) Use(hooks ...Hook) {
	c.hooks.BackupConfig = append(c.hooks.BackupConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `backupconfig.Intercept(f(g(h())))`.
func (c *BackupConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.BackupConfig = append(c.inters.BackupConfig, interceptors...)
}

// Create returns a builder for creating a BackupConfig entity.
func (c *BackupConfigClient) Create() *BackupConfigCreate {
	mutation := newBackupConfigMutation(c.config, OpCreate)
	return &BackupConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BackupConfig entities.
func (c *BackupConfigClient) CreateBulk(builders ...*BackupConfigCreate) *BackupConfigCreateBulk {
	return &BackupConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BackupConfigClient) MapCreateBulk(slice any, setFunc func(*BackupConfigCreate, int)) *BackupConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BackupConfigCreateBulk{err: fmt.Errorf("calling to BackupConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BackupConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BackupConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BackupConfig.
func (c *BackupConfigClient) Update() *BackupConfigUpdate {
	mutation := newBackupConfigMutation(c.config, OpUpdate)
	return &BackupConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BackupConfigClient) UpdateOne(_m *BackupConfig) *BackupConfigUpdateOne {
	mutation := newBackupConfigMutation(c.config, OpUpdateOne, withBackupConfig(_m))
	return &BackupConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BackupConfigClient) UpdateOneID(id int) *BackupConfigUpdateOne {
	mutation := newBackupConfigMutation(c.config, OpUpdateOne, withBackupConfigID(id))
	return &BackupConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BackupConfig.
func (c *BackupConfigClient) Delete() *BackupConfigDelete {
	mutation := newBackupConfigMutation(c.config, OpDelete)
	return &BackupConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BackupConfigClient) DeleteOne(_m *BackupConfig) *BackupConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BackupConfigClient) DeleteOneID(id int) *BackupConfigDeleteOne {
	builder := c.Delete().Where(backupconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BackupConfigDeleteOne{builder}
}

// Query returns a query builder for BackupConfig.
func (c *BackupConfigClient) Query() *BackupConfigQuery {
	return &BackupConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBackupConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a BackupConfig entity by its id.
func (c *BackupConfigClient) Get(ctx context.Context, id int) (*BackupConfig, error) {
	return c.Query().Where(backupconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BackupConfigClient) GetX(ctx context.Context, id int) *BackupConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BackupConfigClient) Hooks() []Hook {
	return c.hooks.BackupConfig
}

// Interceptors returns the client interceptors.
func (c *BackupConfigClient) Interceptors() []Interceptor {
	return c.inters.BackupConfig
}

func (c *BackupConfigClient) mutate(ctx context.Context, m *BackupConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BackupConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BackupConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BackupConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BackupConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BackupConfig mutation op: %q", m.Op())
	}
}

// FontClient is a client for the Font schema.
type FontClient struct {
	config
}

// NewFontClient returns a client for the Font from the given config.
func NewFontClient(c config) *FontClient {
	return &FontClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `font.Hooks(f(g(h())))`.
func (c *FontClient) Use(hooks ...Hook) {
	c.hooks.Font = append(c.hooks.Font, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `font.Intercept(f(g(h())))`.
func (c *FontClient) Intercept(interceptors ...Interceptor) {
	c.inters.Font = append(c.inters.Font, interceptors...)
}

// Create returns a builder for creating a Font entity.
func (c *FontClient) Create() *FontCreate {
	mutation := newFontMutation(c.config, OpCreate)
	return &FontCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Font entities.
func (c *FontClient) CreateBulk(builders ...*FontCreate) *FontCreateBulk {
	return &FontCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FontClient) MapCreateBulk(slice any, setFunc func(*FontCreate, int)) *FontCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FontCreateBulk{err: fmt.Errorf("calling to FontClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FontCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FontCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Font.
func (c *FontClient) Update() *FontUpdate {
	mutation := newFontMutation(c.config, OpUpdate)
	return &FontUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FontClient) UpdateOne(_m *Font) *FontUpdateOne {
	mutation := newFontMutation(c.config, OpUpdateOne, withFont(_m))
	return &FontUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FontClient) UpdateOneID(id uuid.UUID) *FontUpdateOne {
	mutation := newFontMutation(c.config, OpUpdateOne, withFontID(id))
	return &FontUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Font.
func (c *FontClient) Delete() *FontDelete {
	mutation := newFontMutation(c.config, OpDelete)
	return &FontDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FontClient) DeleteOne(_m *Font) *FontDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FontClient) DeleteOneID(id uuid.UUID) *FontDeleteOne {
	builder := c.Delete().Where(font.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FontDeleteOne{builder}
}

// Query returns a query builder for Font.
func (c *FontClient) Query() *FontQuery {
	return &FontQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFont},
		inters: c.Interceptors(),
	}
}

// Get returns a Font entity by its id.
func (c *FontClient) Get(ctx context.Context, id uuid.UUID) (*Font, error) {
	return c.Query().Where(font.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FontClient) GetX(ctx context.Context, id uuid.UUID) *Font {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUploadedBy queries the uploaded_by edge of a Font.
func (c *FontClient) QueryUploadedBy(_m *Font) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(font.Table, font.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, font.UploadedByTable, font.UploadedByColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FontClient) Hooks() []Hook {
	return c.hooks.Font
}

// Interceptors returns the client interceptors.
func (c *FontClient) Interceptors() []Interceptor {
	return c.inters.Font
}

func (c *FontClient) mutate(ctx context.Context, m *FontMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FontCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FontUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FontUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FontDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Font mutation op: %q", m.Op())
	}
}

// ImportItemClient is a client for the ImportItem schema.
type ImportItemClient struct {
	config
}

// NewImportItemClient returns a client for the ImportItem from the given config.
func NewImportItemClient(c config) *ImportItemClient {
	return &ImportItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `importitem.Hooks(f(g(h())))`.
func (c *ImportItemClient) Use(hooks ...Hook) {
	c.hooks.ImportItem = append(c.hooks.ImportItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `importitem.Intercept(f(g(h())))`.
func (c *ImportItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.ImportItem = append(c.inters.ImportItem, interceptors...)
}

// Create returns a builder for creating a ImportItem entity.
func (c *ImportItemClient) Create() *ImportItemCreate {
	mutation := newImportItemMutation(c.config, OpCreate)
	return &ImportItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ImportItem entities.
func (c *ImportItemClient) CreateBulk(builders ...*ImportItemCreate) *ImportItemCreateBulk {
	return &ImportItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ImportItemClient) MapCreateBulk(slice any, setFunc func(*ImportItemCreate, int)) *ImportItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ImportItemCreateBulk{err: fmt.Errorf("calling to ImportItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ImportItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ImportItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ImportItem.
func (c *ImportItemClient) Update() *ImportItemUpdate {
	mutation := newImportItemMutation(c.config, OpUpdate)
	return &ImportItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ImportItemClient) UpdateOne(_m *ImportItem) *ImportItemUpdateOne {
	mutation := newImportItemMutation(c.config, OpUpdateOne, withImportItem(_m))
	return &ImportItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ImportItemClient) UpdateOneID(id int) *ImportItemUpdateOne {
	mutation := newImportItemMutation(c.config, OpUpdateOne, withImportItemID(id))
	return &ImportItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ImportItem.
func (c *ImportItemClient) Delete() *ImportItemDelete {
	mutation := newImportItemMutation(c.config, OpDelete)
	return &ImportItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ImportItemClient) DeleteOne(_m *ImportItem) *ImportItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ImportItemClient) DeleteOneID(id int) *ImportItemDeleteOne {
	builder := c.Delete().Where(importitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ImportItemDeleteOne{builder}
}

// Query returns a query builder for ImportItem.
func (c *ImportItemClient) Query() *ImportItemQuery {
	return &ImportItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeImportItem},
		inters: c.Interceptors(),
	}
}

// Get returns a ImportItem entity by its id.
func (c *ImportItemClient) Get(ctx context.Context, id int) (*ImportItem, error) {
	return c.Query().Where(importitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ImportItemClient) GetX(ctx context.Context, id int) *ImportItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryJob queries the job edge of a ImportItem.
func (c *ImportItemClient) QueryJob(_m *ImportItem) *ImportJobQuery {
	query := (&ImportJobClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(importitem.Table, importitem.FieldID, id),
			sqlgraph.To(importjob.Table, importjob.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, importitem.JobTable, importitem.JobColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ImportItemClient) Hooks() []Hook {
	return c.hooks.ImportItem
}

// Interceptors returns the client interceptors.
func (c *ImportItemClient) Interceptors() []Interceptor {
	return c.inters.ImportItem
}

func (c *ImportItemClient) mutate(ctx context.Context, m *ImportItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ImportItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ImportItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ImportItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ImportItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ImportItem mutation op: %q", m.Op())
	}
}

// ImportJobClient is a client for the ImportJob schema.
type ImportJobClient struct {
	config
}

// NewImportJobClient returns a client for the ImportJob from the given config.
func NewImportJobClient(c config) *ImportJobClient {
	return &ImportJobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `importjob.Hooks(f(g(h())))`.
func (c *ImportJobClient) Use(hooks ...Hook) {
	c.hooks.ImportJob = append(c.hooks.ImportJob, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `importjob.Intercept(f(g(h())))`.
func (c *ImportJobClient) Intercept(interceptors ...Interceptor) {
	c.inters.ImportJob = append(c.inters.ImportJob, interceptors...)
}

// Create returns a builder for creating a ImportJob entity.
func (c *ImportJobClient) Create() *ImportJobCreate {
	mutation := newImportJobMutation(c.config, OpCreate)
	return &ImportJobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ImportJob entities.
func (c *ImportJobClient) CreateBulk(builders ...*ImportJobCreate) *ImportJobCreateBulk {
	return &ImportJobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ImportJobClient) MapCreateBulk(slice any, setFunc func(*ImportJobCreate, int)) *ImportJobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ImportJobCreateBulk{err: fmt.Errorf("calling to ImportJobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ImportJobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ImportJobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ImportJob.
func (c *ImportJobClient) Update() *ImportJobUpdate {
	mutation := newImportJobMutation(c.config, OpUpdate)
	return &ImportJobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ImportJobClient) UpdateOne(_m *ImportJob) *ImportJobUpdateOne {
	mutation := newImportJobMutation(c.config, OpUpdateOne, withImportJob(_m))
	return &ImportJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ImportJobClient) UpdateOneID(id int) *ImportJobUpdateOne {
	mutation := newImportJobMutation(c.config, OpUpdateOne, withImportJobID(id))
	return &ImportJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ImportJob.
func (c *ImportJobClient) Delete() *ImportJobDelete {
	mutation := newImportJobMutation(c.config, OpDelete)
	return &ImportJobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ImportJobClient) DeleteOne(_m *ImportJob) *ImportJobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ImportJobClient) DeleteOneID(id int) *ImportJobDeleteOne {
	builder := c.Delete().Where(importjob.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ImportJobDeleteOne{builder}
}

// Query returns a query builder for ImportJob.
func (c *ImportJobClient) Query() *ImportJobQuery {
	return &ImportJobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeImportJob},
		inters: c.Interceptors(),
	}
}

// Get returns a ImportJob entity by its id.
func (c *ImportJobClient) Get(ctx context.Context, id int) (*ImportJob, error) {
	return c.Query().Where(importjob.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ImportJobClient) GetX(ctx context.Context, id int) *ImportJob {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a ImportJob.
func (c *ImportJobClient) QueryUser(_m *ImportJob) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(importjob.Table, importjob.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, importjob.UserTable, importjob.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryItems queries the items edge of a ImportJob.
func (c *ImportJobClient) QueryItems(_m *ImportJob) *ImportItemQuery {
	query := (&ImportItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(importjob.Table, importjob.FieldID, id),
			sqlgraph.To(importitem.Table, importitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, importjob.ItemsTable, importjob.ItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ImportJobClient) Hooks() []Hook {
	return c.hooks.ImportJob
}

// Interceptors returns the client interceptors.
func (c *ImportJobClient) Interceptors() []Interceptor {
	return c.inters.ImportJob
}

func (c *ImportJobClient) mutate(ctx context.Context, m *ImportJobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ImportJobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ImportJobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ImportJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ImportJobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ImportJob mutation op: %q", m.Op())
	}
}

// MCPImageClient is a client for the MCPImage schema.
type MCPImageClient struct {
	config
}

// NewMCPImageClient returns a client for the MCPImage from the given config.
func NewMCPImageClient(c config) *MCPImageClient {
	return &MCPImageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mcpimage.Hooks(f(g(h())))`.
func (c *MCPImageClient) Use(hooks ...Hook) {
	c.hooks.MCPImage = append(c.hooks.MCPImage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mcpimage.Intercept(f(g(h())))`.
func (c *MCPImageClient) Intercept(interceptors ...Interceptor) {
	c.inters.MCPImage = append(c.inters.MCPImage, interceptors...)
}

// Create returns a builder for creating a MCPImage entity.
func (c *MCPImageClient) Create() *MCPImageCreate {
	mutation := newMCPImageMutation(c.config, OpCreate)
	return &MCPImageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MCPImage entities.
func (c *MCPImageClient) CreateBulk(builders ...*MCPImageCreate) *MCPImageCreateBulk {
	return &MCPImageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MCPImageClient) MapCreateBulk(slice any, setFunc func(*MCPImageCreate, int)) *MCPImageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MCPImageCreateBulk{err: fmt.Errorf("calling to MCPImageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MCPImageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MCPImageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MCPImage.
func (c *MCPImageClient) Update() *MCPImageUpdate {
	mutation := newMCPImageMutation(c.config, OpUpdate)
	return &MCPImageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MCPImageClient) UpdateOne(_m *MCPImage) *MCPImageUpdateOne {
	mutation := newMCPImageMutation(c.config, OpUpdateOne, withMCPImage(_m))
	return &MCPImageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MCPImageClient) UpdateOneID(id int) *MCPImageUpdateOne {
	mutation := newMCPImageMutation(c.config, OpUpdateOne, withMCPImageID(id))
	return &MCPImageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MCPImage.
func (c *MCPImageClient) Delete() *MCPImageDelete {
	mutation := newMCPImageMutation(c.config, OpDelete)
	return &MCPImageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MCPImageClient) DeleteOne(_m *MCPImage) *MCPImageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MCPImageClient) DeleteOneID(id int) *MCPImageDeleteOne {
	builder := c.Delete().Where(mcpimage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MCPImageDeleteOne{builder}
}

// Query returns a query builder for MCPImage.
func (c *MCPImageClient) Query() *MCPImageQuery {
	return &MCPImageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMCPImage},
		inters: c.Interceptors(),
	}
}

// Get returns a MCPImage entity by its id.
func (c *MCPImageClient) Get(ctx context.Context, id int) (*MCPImage, error) {
	return c.Query().Where(mcpimage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MCPImageClient) GetX(ctx context.Context, id int) *MCPImage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a MCPImage.
func (c *MCPImageClient) QueryUser(_m *MCPImage) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(mcpimage.Table, mcpimage.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mcpimage.UserTable, mcpimage.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MCPImageClient) Hooks() []Hook {
	return c.hooks.MCPImage
}

// Interceptors returns the client interceptors.
func (c *MCPImageClient) Interceptors() []Interceptor {
	return c.inters.MCPImage
}

func (c *MCPImageClient) mutate(ctx context.Context, m *MCPImageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MCPImageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MCPImageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MCPImageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MCPImageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MCPImage mutation op: %q", m.Op())
	}
}

// MCPTokenClient is a client for the MCPToken schema.
type MCPTokenClient struct {
	config
}

// NewMCPTokenClient returns a client for the MCPToken from the given config.
func NewMCPTokenClient(c config) *MCPTokenClient {
	return &MCPTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mcptoken.Hooks(f(g(h())))`.
func (c *MCPTokenClient) Use(hooks ...Hook) {
	c.hooks.MCPToken = append(c.hooks.MCPToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mcptoken.Intercept(f(g(h())))`.
func (c *MCPTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.MCPToken = append(c.inters.MCPToken, interceptors...)
}

// Create returns a builder for creating a MCPToken entity.
func (c *MCPTokenClient) Create() *MCPTokenCreate {
	mutation := newMCPTokenMutation(c.config, OpCreate)
	return &MCPTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MCPToken entities.
func (c *MCPTokenClient) CreateBulk(builders ...*MCPTokenCreate) *MCPTokenCreateBulk {
	return &MCPTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MCPTokenClient) MapCreateBulk(slice any, setFunc func(*MCPTokenCreate, int)) *MCPTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MCPTokenCreateBulk{err: fmt.Errorf("calling to MCPTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MCPTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MCPTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MCPToken.
func (c *MCPTokenClient) Update() *MCPTokenUpdate {
	mutation := newMCPTokenMutation(c.config, OpUpdate)
	return &MCPTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MCPTokenClient) UpdateOne(_m *MCPToken) *MCPTokenUpdateOne {
	mutation := newMCPTokenMutation(c.config, OpUpdateOne, withMCPToken(_m))
	return &MCPTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MCPTokenClient) UpdateOneID(id int) *MCPTokenUpdateOne {
	mutation := newMCPTokenMutation(c.config, OpUpdateOne, withMCPTokenID(id))
	return &MCPTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MCPToken.
func (c *MCPTokenClient) Delete() *MCPTokenDelete {
	mutation := newMCPTokenMutation(c.config, OpDelete)
	return &MCPTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MCPTokenClient) DeleteOne(_m *MCPToken) *MCPTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MCPTokenClient) DeleteOneID(id int) *MCPTokenDeleteOne {
	builder := c.Delete().Where(mcptoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MCPTokenDeleteOne{builder}
}

// Query returns a query builder for MCPToken.
func (c *MCPTokenClient) Query() *MCPTokenQuery {
	return &MCPTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMCPToken},
		inters: c.Interceptors(),
	}
}

// Get returns a MCPToken entity by its id.
func (c *MCPTokenClient) Get(ctx context.Context, id int) (*MCPToken, error) {
	return c.Query().Where(mcptoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MCPTokenClient) GetX(ctx context.Context, id int) *MCPToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a MCPToken.
func (c *MCPTokenClient) QueryUser(_m *MCPToken) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(mcptoken.Table, mcptoken.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mcptoken.UserTable, mcptoken.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MCPTokenClient) Hooks() []Hook {
	return c.hooks.MCPToken
}

// Interceptors returns the client interceptors.
func (c *MCPTokenClient) Interceptors() []Interceptor {
	return c.inters.MCPToken
}

func (c *MCPTokenClient) mutate(ctx context.Context, m *MCPTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MCPTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MCPTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MCPTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MCPTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MCPToken mutation op: %q", m.Op())
	}
}

// NoteClient is a client for the Note schema.
type NoteClient struct {
	config
}

// NewNoteClient returns a client for the Note from the given config.
func NewNoteClient(c config) *NoteClient {
	return &NoteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `note.Hooks(f(g(h())))`.
func (c *NoteClient) Use(hooks ...Hook) {
	c.hooks.Note = append(c.hooks.Note, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `note.Intercept(f(g(h())))`.
func (c *NoteClient) Intercept(interceptors ...Interceptor) {
	c.inters.Note = append(c.inters.Note, interceptors...)
}

// Create returns a builder for creating a Note entity.
func (c *NoteClient) Create() *NoteCreate {
	mutation := newNoteMutation(c.config, OpCreate)
	return &NoteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Note entities.
func (c *NoteClient) CreateBulk(builders ...*NoteCreate) *NoteCreateBulk {
	return &NoteCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NoteClient) MapCreateBulk(slice any, setFunc func(*NoteCreate, int)) *NoteCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NoteCreateBulk{err: fmt.Errorf("calling to NoteClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NoteCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NoteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Note.
func (c *NoteClient) Update() *NoteUpdate {
	mutation := newNoteMutation(c.config, OpUpdate)
	return &NoteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NoteClient) UpdateOne(_m *Note) *NoteUpdateOne {
	mutation := newNoteMutation(c.config, OpUpdateOne, withNote(_m))
	return &NoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NoteClient) UpdateOneID(id uuid.UUID) *NoteUpdateOne {
	mutation := newNoteMutation(c.config, OpUpdateOne, withNoteID(id))
	return &NoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Note.
func (c *NoteClient) Delete() *NoteDelete {
	mutation := newNoteMutation(c.config, OpDelete)
	return &NoteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NoteClient) DeleteOne(_m *Note) *NoteDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NoteClient) DeleteOneID(id uuid.UUID) *NoteDeleteOne {
	builder := c.Delete().Where(note.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NoteDeleteOne{builder}
}

// Query returns a query builder for Note.
func (c *NoteClient) Query() *NoteQuery {
	return &NoteQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNote},
		inters: c.Interceptors(),
	}
}

// Get returns a Note entity by its id.
func (c *NoteClient) Get(ctx context.Context, id uuid.UUID) (*Note, error) {
	return c.Query().Where(note.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NoteClient) GetX(ctx context.Context, id uuid.UUID) *Note {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Note.
func (c *NoteClient) QueryUser(_m *Note) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(note.Table, note.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, note.UserTable, note.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAttachments queries the attachments edge of a Note.
func (c *NoteClient) QueryAttachments(_m *Note) *AttachmentQuery {
	query := (&AttachmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(note.Table, note.FieldID, id),
			sqlgraph.To(attachment.Table, attachment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, note.AttachmentsTable, note.AttachmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTags queries the tags edge of a Note.
func (c *NoteClient) QueryTags(_m *Note) *TagQuery {
	query := (&TagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(note.Table, note.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, note.TagsTable, note.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NoteClient) Hooks() []Hook {
	return c.hooks.Note
}

// Interceptors returns the client interceptors.
func (c *NoteClient) Interceptors() []Interceptor {
	return c.inters.Note
}

func (c *NoteClient) mutate(ctx context.Context, m *NoteMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NoteCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NoteUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NoteDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Note mutation op: %q", m.Op())
	}
}

// TagClient is a client for the Tag schema.
type TagClient struct {
	config
}

// NewTagClient returns a client for the Tag from the given config.
func NewTagClient(c config) *TagClient {
	return &TagClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tag.Hooks(f(g(h())))`.
func (c *TagClient) Use(hooks ...Hook) {
	c.hooks.Tag = append(c.hooks.Tag, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tag.Intercept(f(g(h())))`.
func (c *TagClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tag = append(c.inters.Tag, interceptors...)
}

// Create returns a builder for creating a Tag entity.
func (c *TagClient) Create() *TagCreate {
	mutation := newTagMutation(c.config, OpCreate)
	return &TagCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tag entities.
func (c *TagClient) CreateBulk(builders ...*TagCreate) *TagCreateBulk {
	return &TagCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TagClient) MapCreateBulk(slice any, setFunc func(*TagCreate, int)) *TagCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TagCreateBulk{err: fmt.Errorf("calling to TagClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TagCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TagCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tag.
func (c *TagClient) Update() *TagUpdate {
	mutation := newTagMutation(c.config, OpUpdate)
	return &TagUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TagClient) UpdateOne(_m *Tag) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTag(_m))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TagClient) UpdateOneID(id uuid.UUID) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTagID(id))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tag.
func (c *TagClient) Delete() *TagDelete {
	mutation := newTagMutation(c.config, OpDelete)
	return &TagDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TagClient) DeleteOne(_m *Tag) *TagDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TagClient) DeleteOneID(id uuid.UUID) *TagDeleteOne {
	builder := c.Delete().Where(tag.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TagDeleteOne{builder}
}

// Query returns a query builder for Tag.
func (c *TagClient) Query() *TagQuery {
	return &TagQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTag},
		inters: c.Interceptors(),
	}
}

// Get returns a Tag entity by its id.
func (c *TagClient) Get(ctx context.Context, id uuid.UUID) (*Tag, error) {
	return c.Query().Where(tag.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TagClient) GetX(ctx context.Context, id uuid.UUID) *Tag {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNotes queries the notes edge of a Tag.
func (c *TagClient) QueryNotes(_m *Tag) *NoteQuery {
	query := (&NoteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(note.Table, note.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tag.NotesTable, tag.NotesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a Tag.
func (c *TagClient) QueryUser(_m *Tag) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tag.UserTable, tag.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TagClient) Hooks() []Hook {
	return c.hooks.Tag
}

// Interceptors returns the client interceptors.
func (c *TagClient) Interceptors() []Interceptor {
	return c.inters.Tag
}

func (c *TagClient) mutate(ctx context.Context, m *TagMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TagCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TagUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TagDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tag mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNotes queries the notes edge of a User.
func (c *UserClient) QueryNotes(_m *User) *NoteQuery {
	query := (&NoteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(note.Table, note.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.NotesTable, user.NotesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAttachments queries the attachments edge of a User.
func (c *UserClient) QueryAttachments(_m *User) *AttachmentQuery {
	query := (&AttachmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(attachment.Table, attachment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.AttachmentsTable, user.AttachmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTags queries the tags edge of a User.
func (c *UserClient) QueryTags(_m *User) *TagQuery {
	query := (&TagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.TagsTable, user.TagsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFonts queries the fonts edge of a User.
func (c *UserClient) QueryFonts(_m *User) *FontQuery {
	query := (&FontClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(font.Table, font.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.FontsTable, user.FontsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryImportJobs queries the import_jobs edge of a User.
func (c *UserClient) QueryImportJobs(_m *User) *ImportJobQuery {
	query := (&ImportJobClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(importjob.Table, importjob.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.ImportJobsTable, user.ImportJobsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMcpTokens queries the mcp_tokens edge of a User.
func (c *UserClient) QueryMcpTokens(_m *User) *MCPTokenQuery {
	query := (&MCPTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(mcptoken.Table, mcptoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.McpTokensTable, user.McpTokensColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMcpImages queries the mcp_images edge of a User.
func (c *UserClient) QueryMcpImages(_m *User) *MCPImageQuery {
	query := (&MCPImageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(mcpimage.Table, mcpimage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.McpImagesTable, user.McpImagesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Attachment, BackupConfig, Font, ImportItem, ImportJob, MCPImage, MCPToken, Note,
		Tag, User []ent.Hook
	}
	inters struct {
		Attachment, BackupConfig, Font, ImportItem, ImportJob, MCPImage, MCPToken, Note,
		Tag, User []ent.Interceptor
	}
)
