// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"smarticky/ent/font"
	"smarticky/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Font is the model entity for the Font schema.
type Font struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Font family name (e.g., 'MyCustomFont')
	Name string `json:"name,omitempty"`
	// Display name shown to users
	DisplayName string `json:"display_name,omitempty"`
	// Path to the font file
	FilePath string `json:"file_path,omitempty"`
	// File size in bytes
	FileSize int64 `json:"file_size,omitempty"`
	// Font file format
	Format font.Format `json:"format,omitempty"`
	// Text used for font preview
	PreviewText string `json:"preview_text,omitempty"`
	// Whether the font is shared with all users
	IsShared bool `json:"is_shared,omitempty"`
	// Upload time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FontQuery when eager-loading is set.
	Edges        FontEdges `json:"edges"`
	user_fonts   *int
	selectValues sql.SelectValues
}

// FontEdges holds the relations/edges for other nodes in the graph.
type FontEdges struct {
	// User who uploaded this font
	UploadedBy *User `json:"uploaded_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UploadedByOrErr returns the UploadedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FontEdges) UploadedByOrErr() (*User, error) {
	if e.UploadedBy != nil {
		return e.UploadedBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "uploaded_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Font) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case font.FieldIsShared:
			values[i] = new(sql.NullBool)
		case font.FieldFileSize:
			values[i] = new(sql.NullInt64)
		case font.FieldName, font.FieldDisplayName, font.FieldFilePath, font.FieldFormat, font.FieldPreviewText:
			values[i] = new(sql.NullString)
		case font.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case font.FieldID:
			values[i] = new(uuid.UUID)
		case font.ForeignKeys[0]: // user_fonts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Font fields.
func (_m *Font) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case font.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case font.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case font.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case font.FieldFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_path", values[i])
			} else if value.Valid {
				_m.FilePath = value.String
			}
		case font.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case font.FieldFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field format", values[i])
			} else if value.Valid {
				_m.Format = font.Format(value.String)
			}
		case font.FieldPreviewText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preview_text", values[i])
			} else if value.Valid {
				_m.PreviewText = value.String
			}
		case font.FieldIsShared:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_shared", values[i])
			} else if value.Valid {
				_m.IsShared = value.Bool
			}
		case font.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case font.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_fonts", value)
			} else if value.Valid {
				_m.user_fonts = new(int)
				*_m.user_fonts = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Font.
// This includes values selected through modifiers, order, etc.
func (_m *Font) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUploadedBy queries the "uploaded_by" edge of the Font entity.
func (_m *Font) QueryUploadedBy() *UserQuery {
	return NewFontClient(_m.config).QueryUploadedBy(_m)
}

// Update returns a builder for updating this Font.
// Note that you need to call Font.Unwrap() before calling this method if this Font
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Font) Update() *FontUpdateOne {
	return NewFontClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Font entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Font) Unwrap() *Font {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Font is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Font) String() string {
	var builder strings.Builder
	builder.WriteString("Font(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("file_path=")
	builder.WriteString(_m.FilePath)
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("format=")
	builder.WriteString(fmt.Sprintf("%v", _m.Format))
	builder.WriteString(", ")
	builder.WriteString("preview_text=")
	builder.WriteString(_m.PreviewText)
	builder.WriteString(", ")
	builder.WriteString("is_shared=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsShared))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Fonts is a parsable slice of Font.
type Fonts []*Font
