// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"smarticky/ent/importitem"
	"smarticky/ent/importjob"
	"smarticky/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ImportItemUpdate is the builder for updating ImportItem entities.
type ImportItemUpdate struct {
	config
	hooks    []Hook
	mutation *ImportItemMutation
}

// Where appends a list predicates to the ImportItemUpdate builder.
func (_u *ImportItemUpdate) Where(ps ...predicate.ImportItem) *ImportItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceNoteKey sets the "source_note_key" field.
func (_u *ImportItemUpdate) SetSourceNoteKey(v string) *ImportItemUpdate {
	_u.mutation.SetSourceNoteKey(v)
	return _u
}

// SetNillableSourceNoteKey sets the "source_note_key" field if the given value is not nil.
func (_u *ImportItemUpdate) SetNillableSourceNoteKey(v *string) *ImportItemUpdate {
	if v != nil {
		_u.SetSourceNoteKey(*v)
	}
	return _u
}

// SetNoteID sets the "note_id" field.
func (_u *ImportItemUpdate) SetNoteID(v uuid.UUID) *ImportItemUpdate {
	_u.mutation.SetNoteID(v)
	return _u
}

// SetNillableNoteID sets the "note_id" field if the given value is not nil.
func (_u *ImportItemUpdate) SetNillableNoteID(v *uuid.UUID) *ImportItemUpdate {
	if v != nil {
		_u.SetNoteID(*v)
	}
	return _u
}

// ClearNoteID clears the value of the "note_id" field.
func (_u *ImportItemUpdate) ClearNoteID() *ImportItemUpdate {
	_u.mutation.ClearNoteID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *ImportItemUpdate) SetTitle(v string) *ImportItemUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ImportItemUpdate) SetNillableTitle(v *string) *ImportItemUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImportItemUpdate) SetStatus(v string) *ImportItemUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImportItemUpdate) SetNillableStatus(v *string) *ImportItemUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ImportItemUpdate) SetMessage(v string) *ImportItemUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ImportItemUpdate) SetNillableMessage(v *string) *ImportItemUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *ImportItemUpdate) ClearMessage() *ImportItemUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetJobID sets the "job" edge to the ImportJob entity by ID.
func (_u *ImportItemUpdate) SetJobID(id int) *ImportItemUpdate {
	_u.mutation.SetJobID(id)
	return _u
}

// SetJob sets the "job" edge to the ImportJob entity.
func (_u *ImportItemUpdate) SetJob(v *ImportJob) *ImportItemUpdate {
	return _u.SetJobID(v.ID)
}

// Mutation returns the ImportItemMutation object of the builder.
func (_u *ImportItemUpdate) Mutation() *ImportItemMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the ImportJob entity.
func (_u *ImportItemUpdate) ClearJob() *ImportItemUpdate {
	_u.mutation.ClearJob()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImportItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImportItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImportItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImportItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImportItemUpdate) check() error {
	if v, ok := _u.mutation.SourceNoteKey(); ok {
		if err := importitem.SourceNoteKeyValidator(v); err != nil {
			return &ValidationError{Name: "source_note_key", err: fmt.Errorf(`ent: validator failed for field "ImportItem.source_note_key": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImportItem.job"`)
	}
	return nil
}

func (_u *ImportItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(importitem.Table, importitem.Columns, sqlgraph.NewFieldSpec(importitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceNoteKey(); ok {
		_spec.SetField(importitem.FieldSourceNoteKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.NoteID(); ok {
		_spec.SetField(importitem.FieldNoteID, field.TypeUUID, value)
	}
	if _u.mutation.NoteIDCleared() {
		_spec.ClearField(importitem.FieldNoteID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(importitem.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(importitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(importitem.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(importitem.FieldMessage, field.TypeString)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   importitem.JobTable,
			Columns: []string{importitem.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(importjob.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   importitem.JobTable,
			Columns: []string{importitem.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(importjob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{importitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImportItemUpdateOne is the builder for updating a single ImportItem entity.
type ImportItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImportItemMutation
}

// SetSourceNoteKey sets the "source_note_key" field.
func (_u *ImportItemUpdateOne) SetSourceNoteKey(v string) *ImportItemUpdateOne {
	_u.mutation.SetSourceNoteKey(v)
	return _u
}

// SetNillableSourceNoteKey sets the "source_note_key" field if the given value is not nil.
func (_u *ImportItemUpdateOne) SetNillableSourceNoteKey(v *string) *ImportItemUpdateOne {
	if v != nil {
		_u.SetSourceNoteKey(*v)
	}
	return _u
}

// SetNoteID sets the "note_id" field.
func (_u *ImportItemUpdateOne) SetNoteID(v uuid.UUID) *ImportItemUpdateOne {
	_u.mutation.SetNoteID(v)
	return _u
}

// SetNillableNoteID sets the "note_id" field if the given value is not nil.
func (_u *ImportItemUpdateOne) SetNillableNoteID(v *uuid.UUID) *ImportItemUpdateOne {
	if v != nil {
		_u.SetNoteID(*v)
	}
	return _u
}

// ClearNoteID clears the value of the "note_id" field.
func (_u *ImportItemUpdateOne) ClearNoteID() *ImportItemUpdateOne {
	_u.mutation.ClearNoteID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *ImportItemUpdateOne) SetTitle(v string) *ImportItemUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ImportItemUpdateOne) SetNillableTitle(v *string) *ImportItemUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImportItemUpdateOne) SetStatus(v string) *ImportItemUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImportItemUpdateOne) SetNillableStatus(v *string) *ImportItemUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *ImportItemUpdateOne) SetMessage(v string) *ImportItemUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *ImportItemUpdateOne) SetNillableMessage(v *string) *ImportItemUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *ImportItemUpdateOne) ClearMessage() *ImportItemUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetJobID sets the "job" edge to the ImportJob entity by ID.
func (_u *ImportItemUpdateOne) SetJobID(id int) *ImportItemUpdateOne {
	_u.mutation.SetJobID(id)
	return _u
}

// SetJob sets the "job" edge to the ImportJob entity.
func (_u *ImportItemUpdateOne) SetJob(v *ImportJob) *ImportItemUpdateOne {
	return _u.SetJobID(v.ID)
}

// Mutation returns the ImportItemMutation object of the builder.
func (_u *ImportItemUpdateOne) Mutation() *ImportItemMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the ImportJob entity.
func (_u *ImportItemUpdateOne) ClearJob() *ImportItemUpdateOne {
	_u.mutation.ClearJob()
	return _u
}

// Where appends a list predicates to the ImportItemUpdate builder.
func (_u *ImportItemUpdateOne) Where(ps ...predicate.ImportItem) *ImportItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImportItemUpdateOne) Select(field string, fields ...string) *ImportItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImportItem entity.
func (_u *ImportItemUpdateOne) Save(ctx context.Context) (*ImportItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImportItemUpdateOne) SaveX(ctx context.Context) *ImportItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImportItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImportItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImportItemUpdateOne) check() error {
	if v, ok := _u.mutation.SourceNoteKey(); ok {
		if err := importitem.SourceNoteKeyValidator(v); err != nil {
			return &ValidationError{Name: "source_note_key", err: fmt.Errorf(`ent: validator failed for field "ImportItem.source_note_key": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImportItem.job"`)
	}
	return nil
}

func (_u *ImportItemUpdateOne) sqlSave(ctx context.Context) (_node *ImportItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(importitem.Table, importitem.Columns, sqlgraph.NewFieldSpec(importitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImportItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, importitem.FieldID)
		for _, f := range fields {
			if !importitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != importitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceNoteKey(); ok {
		_spec.SetField(importitem.FieldSourceNoteKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.NoteID(); ok {
		_spec.SetField(importitem.FieldNoteID, field.TypeUUID, value)
	}
	if _u.mutation.NoteIDCleared() {
		_spec.ClearField(importitem.FieldNoteID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(importitem.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(importitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(importitem.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(importitem.FieldMessage, field.TypeString)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   importitem.JobTable,
			Columns: []string{importitem.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(importjob.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   importitem.JobTable,
			Columns: []string{importitem.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(importjob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ImportItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{importitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
