// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"smarticky/ent/mcpimage"
	"smarticky/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MCPImageDelete is the builder for deleting a MCPImage entity.
type MCPImageDelete struct {
	config
	hooks    []Hook
	mutation *MCPImageMutation
}

// Where appends a list predicates to the MCPImageDelete builder.
func (_d *MCPImageDelete) Where(ps ...predicate.MCPImage) *MCPImageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MCPImageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MCPImageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MCPImageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mcpimage.Table, sqlgraph.NewFieldSpec(mcpimage.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MCPImageDeleteOne is the builder for deleting a single MCPImage entity.
type MCPImageDeleteOne struct {
	_d *MCPImageDelete
}

// Where appends a list predicates to the MCPImageDelete builder.
func (_d *MCPImageDeleteOne) Where(ps ...predicate.MCPImage) *MCPImageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MCPImageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mcpimage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MCPImageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
