// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"smarticky/ent/attachment"
	"smarticky/ent/folder"
	"smarticky/ent/note"
	"smarticky/ent/noteconnectionitemmap"
	"smarticky/ent/noteconnectionjob"
	"smarticky/ent/notelink"
	"smarticky/ent/predicate"
	"smarticky/ent/tag"
	"smarticky/ent/user"
	"smarticky/ent/whiteboard"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NoteUpdate is the builder for updating Note entities.
type NoteUpdate struct {
	config
	hooks    []Hook
	mutation *NoteMutation
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdate) Where(ps ...predicate.Note) *NoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *NoteUpdate) SetTitle(v string) *NoteUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableTitle(v *string) *NoteUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NoteUpdate) SetContent(v string) *NoteUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableContent(v *string) *NoteUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *NoteUpdate) ClearContent() *NoteUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetColor sets the "color" field.
func (_u *NoteUpdate) SetColor(v string) *NoteUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableColor(v *string) *NoteUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *NoteUpdate) ClearColor() *NoteUpdate {
	_u.mutation.ClearColor()
	return _u
}

// SetProtectionMode sets the "protection_mode" field.
func (_u *NoteUpdate) SetProtectionMode(v note.ProtectionMode) *NoteUpdate {
	_u.mutation.SetProtectionMode(v)
	return _u
}

// SetNillableProtectionMode sets the "protection_mode" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableProtectionMode(v *note.ProtectionMode) *NoteUpdate {
	if v != nil {
		_u.SetProtectionMode(*v)
	}
	return _u
}

// SetProtectionPasswordHash sets the "protection_password_hash" field.
func (_u *NoteUpdate) SetProtectionPasswordHash(v string) *NoteUpdate {
	_u.mutation.SetProtectionPasswordHash(v)
	return _u
}

// SetNillableProtectionPasswordHash sets the "protection_password_hash" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableProtectionPasswordHash(v *string) *NoteUpdate {
	if v != nil {
		_u.SetProtectionPasswordHash(*v)
	}
	return _u
}

// ClearProtectionPasswordHash clears the value of the "protection_password_hash" field.
func (_u *NoteUpdate) ClearProtectionPasswordHash() *NoteUpdate {
	_u.mutation.ClearProtectionPasswordHash()
	return _u
}

// SetEncryptedContent sets the "encrypted_content" field.
func (_u *NoteUpdate) SetEncryptedContent(v string) *NoteUpdate {
	_u.mutation.SetEncryptedContent(v)
	return _u
}

// SetNillableEncryptedContent sets the "encrypted_content" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableEncryptedContent(v *string) *NoteUpdate {
	if v != nil {
		_u.SetEncryptedContent(*v)
	}
	return _u
}

// ClearEncryptedContent clears the value of the "encrypted_content" field.
func (_u *NoteUpdate) ClearEncryptedContent() *NoteUpdate {
	_u.mutation.ClearEncryptedContent()
	return _u
}

// SetEncryptionAlg sets the "encryption_alg" field.
func (_u *NoteUpdate) SetEncryptionAlg(v string) *NoteUpdate {
	_u.mutation.SetEncryptionAlg(v)
	return _u
}

// SetNillableEncryptionAlg sets the "encryption_alg" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableEncryptionAlg(v *string) *NoteUpdate {
	if v != nil {
		_u.SetEncryptionAlg(*v)
	}
	return _u
}

// ClearEncryptionAlg clears the value of the "encryption_alg" field.
func (_u *NoteUpdate) ClearEncryptionAlg() *NoteUpdate {
	_u.mutation.ClearEncryptionAlg()
	return _u
}

// SetEncryptionKdf sets the "encryption_kdf" field.
func (_u *NoteUpdate) SetEncryptionKdf(v string) *NoteUpdate {
	_u.mutation.SetEncryptionKdf(v)
	return _u
}

// SetNillableEncryptionKdf sets the "encryption_kdf" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableEncryptionKdf(v *string) *NoteUpdate {
	if v != nil {
		_u.SetEncryptionKdf(*v)
	}
	return _u
}

// ClearEncryptionKdf clears the value of the "encryption_kdf" field.
func (_u *NoteUpdate) ClearEncryptionKdf() *NoteUpdate {
	_u.mutation.ClearEncryptionKdf()
	return _u
}

// SetEncryptionSalt sets the "encryption_salt" field.
func (_u *NoteUpdate) SetEncryptionSalt(v string) *NoteUpdate {
	_u.mutation.SetEncryptionSalt(v)
	return _u
}

// SetNillableEncryptionSalt sets the "encryption_salt" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableEncryptionSalt(v *string) *NoteUpdate {
	if v != nil {
		_u.SetEncryptionSalt(*v)
	}
	return _u
}

// ClearEncryptionSalt clears the value of the "encryption_salt" field.
func (_u *NoteUpdate) ClearEncryptionSalt() *NoteUpdate {
	_u.mutation.ClearEncryptionSalt()
	return _u
}

// SetEncryptionNonce sets the "encryption_nonce" field.
func (_u *NoteUpdate) SetEncryptionNonce(v string) *NoteUpdate {
	_u.mutation.SetEncryptionNonce(v)
	return _u
}

// SetNillableEncryptionNonce sets the "encryption_nonce" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableEncryptionNonce(v *string) *NoteUpdate {
	if v != nil {
		_u.SetEncryptionNonce(*v)
	}
	return _u
}

// ClearEncryptionNonce clears the value of the "encryption_nonce" field.
func (_u *NoteUpdate) ClearEncryptionNonce() *NoteUpdate {
	_u.mutation.ClearEncryptionNonce()
	return _u
}

// SetIsStarred sets the "is_starred" field.
func (_u *NoteUpdate) SetIsStarred(v bool) *NoteUpdate {
	_u.mutation.SetIsStarred(v)
	return _u
}

// SetNillableIsStarred sets the "is_starred" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableIsStarred(v *bool) *NoteUpdate {
	if v != nil {
		_u.SetIsStarred(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *NoteUpdate) SetIsDeleted(v bool) *NoteUpdate {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableIsDeleted(v *bool) *NoteUpdate {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NoteUpdate) SetCreatedAt(v time.Time) *NoteUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableCreatedAt(v *time.Time) *NoteUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NoteUpdate) SetUpdatedAt(v time.Time) *NoteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *NoteUpdate) SetUserID(id int) *NoteUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *NoteUpdate) SetNillableUserID(id *int) *NoteUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NoteUpdate) SetUser(v *User) *NoteUpdate {
	return _u.SetUserID(v.ID)
}

// SetFolderID sets the "folder" edge to the Folder entity by ID.
func (_u *NoteUpdate) SetFolderID(id uuid.UUID) *NoteUpdate {
	_u.mutation.SetFolderID(id)
	return _u
}

// SetNillableFolderID sets the "folder" edge to the Folder entity by ID if the given value is not nil.
func (_u *NoteUpdate) SetNillableFolderID(id *uuid.UUID) *NoteUpdate {
	if id != nil {
		_u = _u.SetFolderID(*id)
	}
	return _u
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_u *NoteUpdate) SetFolder(v *Folder) *NoteUpdate {
	return _u.SetFolderID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *NoteUpdate) AddAttachmentIDs(ids ...int) *NoteUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *NoteUpdate) AddAttachments(v ...*Attachment) *NoteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddWhiteboardIDs adds the "whiteboards" edge to the Whiteboard entity by IDs.
func (_u *NoteUpdate) AddWhiteboardIDs(ids ...uuid.UUID) *NoteUpdate {
	_u.mutation.AddWhiteboardIDs(ids...)
	return _u
}

// AddWhiteboards adds the "whiteboards" edges to the Whiteboard entity.
func (_u *NoteUpdate) AddWhiteboards(v ...*Whiteboard) *NoteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWhiteboardIDs(ids...)
}

// AddOutgoingLinkIDs adds the "outgoing_links" edge to the NoteLink entity by IDs.
func (_u *NoteUpdate) AddOutgoingLinkIDs(ids ...uuid.UUID) *NoteUpdate {
	_u.mutation.AddOutgoingLinkIDs(ids...)
	return _u
}

// AddOutgoingLinks adds the "outgoing_links" edges to the NoteLink entity.
func (_u *NoteUpdate) AddOutgoingLinks(v ...*NoteLink) *NoteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutgoingLinkIDs(ids...)
}

// AddBacklinkIDs adds the "backlinks" edge to the NoteLink entity by IDs.
func (_u *NoteUpdate) AddBacklinkIDs(ids ...uuid.UUID) *NoteUpdate {
	_u.mutation.AddBacklinkIDs(ids...)
	return _u
}

// AddBacklinks adds the "backlinks" edges to the NoteLink entity.
func (_u *NoteUpdate) AddBacklinks(v ...*NoteLink) *NoteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBacklinkIDs(ids...)
}

// AddConnectionMapIDs adds the "connection_maps" edge to the NoteConnectionItemMap entity by IDs.
func (_u *NoteUpdate) AddConnectionMapIDs(ids ...int) *NoteUpdate {
	_u.mutation.AddConnectionMapIDs(ids...)
	return _u
}

// AddConnectionMaps adds the "connection_maps" edges to the NoteConnectionItemMap entity.
func (_u *NoteUpdate) AddConnectionMaps(v ...*NoteConnectionItemMap) *NoteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConnectionMapIDs(ids...)
}

// AddConnectionJobIDs adds the "connection_jobs" edge to the NoteConnectionJob entity by IDs.
func (_u *NoteUpdate) AddConnectionJobIDs(ids ...int) *NoteUpdate {
	_u.mutation.AddConnectionJobIDs(ids...)
	return _u
}

// AddConnectionJobs adds the "connection_jobs" edges to the NoteConnectionJob entity.
func (_u *NoteUpdate) AddConnectionJobs(v ...*NoteConnectionJob) *NoteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConnectionJobIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *NoteUpdate) AddTagIDs(ids ...uuid.UUID) *NoteUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *NoteUpdate) AddTags(v ...*Tag) *NoteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdate) Mutation() *NoteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NoteUpdate) ClearUser() *NoteUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearFolder clears the "folder" edge to the Folder entity.
func (_u *NoteUpdate) ClearFolder() *NoteUpdate {
	_u.mutation.ClearFolder()
	return _u
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *NoteUpdate) ClearAttachments() *NoteUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *NoteUpdate) RemoveAttachmentIDs(ids ...int) *NoteUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *NoteUpdate) RemoveAttachments(v ...*Attachment) *NoteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearWhiteboards clears all "whiteboards" edges to the Whiteboard entity.
func (_u *NoteUpdate) ClearWhiteboards() *NoteUpdate {
	_u.mutation.ClearWhiteboards()
	return _u
}

// RemoveWhiteboardIDs removes the "whiteboards" edge to Whiteboard entities by IDs.
func (_u *NoteUpdate) RemoveWhiteboardIDs(ids ...uuid.UUID) *NoteUpdate {
	_u.mutation.RemoveWhiteboardIDs(ids...)
	return _u
}

// RemoveWhiteboards removes "whiteboards" edges to Whiteboard entities.
func (_u *NoteUpdate) RemoveWhiteboards(v ...*Whiteboard) *NoteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWhiteboardIDs(ids...)
}

// ClearOutgoingLinks clears all "outgoing_links" edges to the NoteLink entity.
func (_u *NoteUpdate) ClearOutgoingLinks() *NoteUpdate {
	_u.mutation.ClearOutgoingLinks()
	return _u
}

// RemoveOutgoingLinkIDs removes the "outgoing_links" edge to NoteLink entities by IDs.
func (_u *NoteUpdate) RemoveOutgoingLinkIDs(ids ...uuid.UUID) *NoteUpdate {
	_u.mutation.RemoveOutgoingLinkIDs(ids...)
	return _u
}

// RemoveOutgoingLinks removes "outgoing_links" edges to NoteLink entities.
func (_u *NoteUpdate) RemoveOutgoingLinks(v ...*NoteLink) *NoteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutgoingLinkIDs(ids...)
}

// ClearBacklinks clears all "backlinks" edges to the NoteLink entity.
func (_u *NoteUpdate) ClearBacklinks() *NoteUpdate {
	_u.mutation.ClearBacklinks()
	return _u
}

// RemoveBacklinkIDs removes the "backlinks" edge to NoteLink entities by IDs.
func (_u *NoteUpdate) RemoveBacklinkIDs(ids ...uuid.UUID) *NoteUpdate {
	_u.mutation.RemoveBacklinkIDs(ids...)
	return _u
}

// RemoveBacklinks removes "backlinks" edges to NoteLink entities.
func (_u *NoteUpdate) RemoveBacklinks(v ...*NoteLink) *NoteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBacklinkIDs(ids...)
}

// ClearConnectionMaps clears all "connection_maps" edges to the NoteConnectionItemMap entity.
func (_u *NoteUpdate) ClearConnectionMaps() *NoteUpdate {
	_u.mutation.ClearConnectionMaps()
	return _u
}

// RemoveConnectionMapIDs removes the "connection_maps" edge to NoteConnectionItemMap entities by IDs.
func (_u *NoteUpdate) RemoveConnectionMapIDs(ids ...int) *NoteUpdate {
	_u.mutation.RemoveConnectionMapIDs(ids...)
	return _u
}

// RemoveConnectionMaps removes "connection_maps" edges to NoteConnectionItemMap entities.
func (_u *NoteUpdate) RemoveConnectionMaps(v ...*NoteConnectionItemMap) *NoteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConnectionMapIDs(ids...)
}

// ClearConnectionJobs clears all "connection_jobs" edges to the NoteConnectionJob entity.
func (_u *NoteUpdate) ClearConnectionJobs() *NoteUpdate {
	_u.mutation.ClearConnectionJobs()
	return _u
}

// RemoveConnectionJobIDs removes the "connection_jobs" edge to NoteConnectionJob entities by IDs.
func (_u *NoteUpdate) RemoveConnectionJobIDs(ids ...int) *NoteUpdate {
	_u.mutation.RemoveConnectionJobIDs(ids...)
	return _u
}

// RemoveConnectionJobs removes "connection_jobs" edges to NoteConnectionJob entities.
func (_u *NoteUpdate) RemoveConnectionJobs(v ...*NoteConnectionJob) *NoteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConnectionJobIDs(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *NoteUpdate) ClearTags() *NoteUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *NoteUpdate) RemoveTagIDs(ids ...uuid.UUID) *NoteUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *NoteUpdate) RemoveTags(v ...*Tag) *NoteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NoteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NoteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := note.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteUpdate) check() error {
	if v, ok := _u.mutation.ProtectionMode(); ok {
		if err := note.ProtectionModeValidator(v); err != nil {
			return &ValidationError{Name: "protection_mode", err: fmt.Errorf(`ent: validator failed for field "Note.protection_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *NoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(note.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(note.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(note.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(note.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(note.FieldColor, field.TypeString)
	}
	if value, ok := _u.mutation.ProtectionMode(); ok {
		_spec.SetField(note.FieldProtectionMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProtectionPasswordHash(); ok {
		_spec.SetField(note.FieldProtectionPasswordHash, field.TypeString, value)
	}
	if _u.mutation.ProtectionPasswordHashCleared() {
		_spec.ClearField(note.FieldProtectionPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptedContent(); ok {
		_spec.SetField(note.FieldEncryptedContent, field.TypeString, value)
	}
	if _u.mutation.EncryptedContentCleared() {
		_spec.ClearField(note.FieldEncryptedContent, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptionAlg(); ok {
		_spec.SetField(note.FieldEncryptionAlg, field.TypeString, value)
	}
	if _u.mutation.EncryptionAlgCleared() {
		_spec.ClearField(note.FieldEncryptionAlg, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptionKdf(); ok {
		_spec.SetField(note.FieldEncryptionKdf, field.TypeString, value)
	}
	if _u.mutation.EncryptionKdfCleared() {
		_spec.ClearField(note.FieldEncryptionKdf, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptionSalt(); ok {
		_spec.SetField(note.FieldEncryptionSalt, field.TypeString, value)
	}
	if _u.mutation.EncryptionSaltCleared() {
		_spec.ClearField(note.FieldEncryptionSalt, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptionNonce(); ok {
		_spec.SetField(note.FieldEncryptionNonce, field.TypeString, value)
	}
	if _u.mutation.EncryptionNonceCleared() {
		_spec.ClearField(note.FieldEncryptionNonce, field.TypeString)
	}
	if value, ok := _u.mutation.IsStarred(); ok {
		_spec.SetField(note.FieldIsStarred, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(note.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(note.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(note.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.UserTable,
			Columns: []string{note.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.UserTable,
			Columns: []string{note.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FolderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.FolderTable,
			Columns: []string{note.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.FolderTable,
			Columns: []string{note.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.AttachmentsTable,
			Columns: []string{note.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.AttachmentsTable,
			Columns: []string{note.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.AttachmentsTable,
			Columns: []string{note.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WhiteboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.WhiteboardsTable,
			Columns: []string{note.WhiteboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(whiteboard.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWhiteboardsIDs(); len(nodes) > 0 && !_u.mutation.WhiteboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.WhiteboardsTable,
			Columns: []string{note.WhiteboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(whiteboard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WhiteboardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.WhiteboardsTable,
			Columns: []string{note.WhiteboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(whiteboard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutgoingLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.OutgoingLinksTable,
			Columns: []string{note.OutgoingLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutgoingLinksIDs(); len(nodes) > 0 && !_u.mutation.OutgoingLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.OutgoingLinksTable,
			Columns: []string{note.OutgoingLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutgoingLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.OutgoingLinksTable,
			Columns: []string{note.OutgoingLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BacklinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.BacklinksTable,
			Columns: []string{note.BacklinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBacklinksIDs(); len(nodes) > 0 && !_u.mutation.BacklinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.BacklinksTable,
			Columns: []string{note.BacklinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BacklinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.BacklinksTable,
			Columns: []string{note.BacklinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConnectionMapsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionMapsTable,
			Columns: []string{note.ConnectionMapsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionitemmap.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConnectionMapsIDs(); len(nodes) > 0 && !_u.mutation.ConnectionMapsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionMapsTable,
			Columns: []string{note.ConnectionMapsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionitemmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionMapsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionMapsTable,
			Columns: []string{note.ConnectionMapsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionitemmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConnectionJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionJobsTable,
			Columns: []string{note.ConnectionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionjob.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConnectionJobsIDs(); len(nodes) > 0 && !_u.mutation.ConnectionJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionJobsTable,
			Columns: []string{note.ConnectionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionjob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionJobsTable,
			Columns: []string{note.ConnectionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionjob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   note.TagsTable,
			Columns: note.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   note.TagsTable,
			Columns: note.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   note.TagsTable,
			Columns: note.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NoteUpdateOne is the builder for updating a single Note entity.
type NoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoteMutation
}

// SetTitle sets the "title" field.
func (_u *NoteUpdateOne) SetTitle(v string) *NoteUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableTitle(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NoteUpdateOne) SetContent(v string) *NoteUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableContent(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *NoteUpdateOne) ClearContent() *NoteUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetColor sets the "color" field.
func (_u *NoteUpdateOne) SetColor(v string) *NoteUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableColor(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *NoteUpdateOne) ClearColor() *NoteUpdateOne {
	_u.mutation.ClearColor()
	return _u
}

// SetProtectionMode sets the "protection_mode" field.
func (_u *NoteUpdateOne) SetProtectionMode(v note.ProtectionMode) *NoteUpdateOne {
	_u.mutation.SetProtectionMode(v)
	return _u
}

// SetNillableProtectionMode sets the "protection_mode" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableProtectionMode(v *note.ProtectionMode) *NoteUpdateOne {
	if v != nil {
		_u.SetProtectionMode(*v)
	}
	return _u
}

// SetProtectionPasswordHash sets the "protection_password_hash" field.
func (_u *NoteUpdateOne) SetProtectionPasswordHash(v string) *NoteUpdateOne {
	_u.mutation.SetProtectionPasswordHash(v)
	return _u
}

// SetNillableProtectionPasswordHash sets the "protection_password_hash" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableProtectionPasswordHash(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetProtectionPasswordHash(*v)
	}
	return _u
}

// ClearProtectionPasswordHash clears the value of the "protection_password_hash" field.
func (_u *NoteUpdateOne) ClearProtectionPasswordHash() *NoteUpdateOne {
	_u.mutation.ClearProtectionPasswordHash()
	return _u
}

// SetEncryptedContent sets the "encrypted_content" field.
func (_u *NoteUpdateOne) SetEncryptedContent(v string) *NoteUpdateOne {
	_u.mutation.SetEncryptedContent(v)
	return _u
}

// SetNillableEncryptedContent sets the "encrypted_content" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableEncryptedContent(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetEncryptedContent(*v)
	}
	return _u
}

// ClearEncryptedContent clears the value of the "encrypted_content" field.
func (_u *NoteUpdateOne) ClearEncryptedContent() *NoteUpdateOne {
	_u.mutation.ClearEncryptedContent()
	return _u
}

// SetEncryptionAlg sets the "encryption_alg" field.
func (_u *NoteUpdateOne) SetEncryptionAlg(v string) *NoteUpdateOne {
	_u.mutation.SetEncryptionAlg(v)
	return _u
}

// SetNillableEncryptionAlg sets the "encryption_alg" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableEncryptionAlg(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetEncryptionAlg(*v)
	}
	return _u
}

// ClearEncryptionAlg clears the value of the "encryption_alg" field.
func (_u *NoteUpdateOne) ClearEncryptionAlg() *NoteUpdateOne {
	_u.mutation.ClearEncryptionAlg()
	return _u
}

// SetEncryptionKdf sets the "encryption_kdf" field.
func (_u *NoteUpdateOne) SetEncryptionKdf(v string) *NoteUpdateOne {
	_u.mutation.SetEncryptionKdf(v)
	return _u
}

// SetNillableEncryptionKdf sets the "encryption_kdf" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableEncryptionKdf(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetEncryptionKdf(*v)
	}
	return _u
}

// ClearEncryptionKdf clears the value of the "encryption_kdf" field.
func (_u *NoteUpdateOne) ClearEncryptionKdf() *NoteUpdateOne {
	_u.mutation.ClearEncryptionKdf()
	return _u
}

// SetEncryptionSalt sets the "encryption_salt" field.
func (_u *NoteUpdateOne) SetEncryptionSalt(v string) *NoteUpdateOne {
	_u.mutation.SetEncryptionSalt(v)
	return _u
}

// SetNillableEncryptionSalt sets the "encryption_salt" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableEncryptionSalt(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetEncryptionSalt(*v)
	}
	return _u
}

// ClearEncryptionSalt clears the value of the "encryption_salt" field.
func (_u *NoteUpdateOne) ClearEncryptionSalt() *NoteUpdateOne {
	_u.mutation.ClearEncryptionSalt()
	return _u
}

// SetEncryptionNonce sets the "encryption_nonce" field.
func (_u *NoteUpdateOne) SetEncryptionNonce(v string) *NoteUpdateOne {
	_u.mutation.SetEncryptionNonce(v)
	return _u
}

// SetNillableEncryptionNonce sets the "encryption_nonce" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableEncryptionNonce(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetEncryptionNonce(*v)
	}
	return _u
}

// ClearEncryptionNonce clears the value of the "encryption_nonce" field.
func (_u *NoteUpdateOne) ClearEncryptionNonce() *NoteUpdateOne {
	_u.mutation.ClearEncryptionNonce()
	return _u
}

// SetIsStarred sets the "is_starred" field.
func (_u *NoteUpdateOne) SetIsStarred(v bool) *NoteUpdateOne {
	_u.mutation.SetIsStarred(v)
	return _u
}

// SetNillableIsStarred sets the "is_starred" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableIsStarred(v *bool) *NoteUpdateOne {
	if v != nil {
		_u.SetIsStarred(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *NoteUpdateOne) SetIsDeleted(v bool) *NoteUpdateOne {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableIsDeleted(v *bool) *NoteUpdateOne {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NoteUpdateOne) SetCreatedAt(v time.Time) *NoteUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableCreatedAt(v *time.Time) *NoteUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NoteUpdateOne) SetUpdatedAt(v time.Time) *NoteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *NoteUpdateOne) SetUserID(id int) *NoteUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableUserID(id *int) *NoteUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NoteUpdateOne) SetUser(v *User) *NoteUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetFolderID sets the "folder" edge to the Folder entity by ID.
func (_u *NoteUpdateOne) SetFolderID(id uuid.UUID) *NoteUpdateOne {
	_u.mutation.SetFolderID(id)
	return _u
}

// SetNillableFolderID sets the "folder" edge to the Folder entity by ID if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableFolderID(id *uuid.UUID) *NoteUpdateOne {
	if id != nil {
		_u = _u.SetFolderID(*id)
	}
	return _u
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_u *NoteUpdateOne) SetFolder(v *Folder) *NoteUpdateOne {
	return _u.SetFolderID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *NoteUpdateOne) AddAttachmentIDs(ids ...int) *NoteUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *NoteUpdateOne) AddAttachments(v ...*Attachment) *NoteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddWhiteboardIDs adds the "whiteboards" edge to the Whiteboard entity by IDs.
func (_u *NoteUpdateOne) AddWhiteboardIDs(ids ...uuid.UUID) *NoteUpdateOne {
	_u.mutation.AddWhiteboardIDs(ids...)
	return _u
}

// AddWhiteboards adds the "whiteboards" edges to the Whiteboard entity.
func (_u *NoteUpdateOne) AddWhiteboards(v ...*Whiteboard) *NoteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWhiteboardIDs(ids...)
}

// AddOutgoingLinkIDs adds the "outgoing_links" edge to the NoteLink entity by IDs.
func (_u *NoteUpdateOne) AddOutgoingLinkIDs(ids ...uuid.UUID) *NoteUpdateOne {
	_u.mutation.AddOutgoingLinkIDs(ids...)
	return _u
}

// AddOutgoingLinks adds the "outgoing_links" edges to the NoteLink entity.
func (_u *NoteUpdateOne) AddOutgoingLinks(v ...*NoteLink) *NoteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutgoingLinkIDs(ids...)
}

// AddBacklinkIDs adds the "backlinks" edge to the NoteLink entity by IDs.
func (_u *NoteUpdateOne) AddBacklinkIDs(ids ...uuid.UUID) *NoteUpdateOne {
	_u.mutation.AddBacklinkIDs(ids...)
	return _u
}

// AddBacklinks adds the "backlinks" edges to the NoteLink entity.
func (_u *NoteUpdateOne) AddBacklinks(v ...*NoteLink) *NoteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBacklinkIDs(ids...)
}

// AddConnectionMapIDs adds the "connection_maps" edge to the NoteConnectionItemMap entity by IDs.
func (_u *NoteUpdateOne) AddConnectionMapIDs(ids ...int) *NoteUpdateOne {
	_u.mutation.AddConnectionMapIDs(ids...)
	return _u
}

// AddConnectionMaps adds the "connection_maps" edges to the NoteConnectionItemMap entity.
func (_u *NoteUpdateOne) AddConnectionMaps(v ...*NoteConnectionItemMap) *NoteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConnectionMapIDs(ids...)
}

// AddConnectionJobIDs adds the "connection_jobs" edge to the NoteConnectionJob entity by IDs.
func (_u *NoteUpdateOne) AddConnectionJobIDs(ids ...int) *NoteUpdateOne {
	_u.mutation.AddConnectionJobIDs(ids...)
	return _u
}

// AddConnectionJobs adds the "connection_jobs" edges to the NoteConnectionJob entity.
func (_u *NoteUpdateOne) AddConnectionJobs(v ...*NoteConnectionJob) *NoteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConnectionJobIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *NoteUpdateOne) AddTagIDs(ids ...uuid.UUID) *NoteUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *NoteUpdateOne) AddTags(v ...*Tag) *NoteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdateOne) Mutation() *NoteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NoteUpdateOne) ClearUser() *NoteUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearFolder clears the "folder" edge to the Folder entity.
func (_u *NoteUpdateOne) ClearFolder() *NoteUpdateOne {
	_u.mutation.ClearFolder()
	return _u
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *NoteUpdateOne) ClearAttachments() *NoteUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *NoteUpdateOne) RemoveAttachmentIDs(ids ...int) *NoteUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *NoteUpdateOne) RemoveAttachments(v ...*Attachment) *NoteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearWhiteboards clears all "whiteboards" edges to the Whiteboard entity.
func (_u *NoteUpdateOne) ClearWhiteboards() *NoteUpdateOne {
	_u.mutation.ClearWhiteboards()
	return _u
}

// RemoveWhiteboardIDs removes the "whiteboards" edge to Whiteboard entities by IDs.
func (_u *NoteUpdateOne) RemoveWhiteboardIDs(ids ...uuid.UUID) *NoteUpdateOne {
	_u.mutation.RemoveWhiteboardIDs(ids...)
	return _u
}

// RemoveWhiteboards removes "whiteboards" edges to Whiteboard entities.
func (_u *NoteUpdateOne) RemoveWhiteboards(v ...*Whiteboard) *NoteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWhiteboardIDs(ids...)
}

// ClearOutgoingLinks clears all "outgoing_links" edges to the NoteLink entity.
func (_u *NoteUpdateOne) ClearOutgoingLinks() *NoteUpdateOne {
	_u.mutation.ClearOutgoingLinks()
	return _u
}

// RemoveOutgoingLinkIDs removes the "outgoing_links" edge to NoteLink entities by IDs.
func (_u *NoteUpdateOne) RemoveOutgoingLinkIDs(ids ...uuid.UUID) *NoteUpdateOne {
	_u.mutation.RemoveOutgoingLinkIDs(ids...)
	return _u
}

// RemoveOutgoingLinks removes "outgoing_links" edges to NoteLink entities.
func (_u *NoteUpdateOne) RemoveOutgoingLinks(v ...*NoteLink) *NoteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutgoingLinkIDs(ids...)
}

// ClearBacklinks clears all "backlinks" edges to the NoteLink entity.
func (_u *NoteUpdateOne) ClearBacklinks() *NoteUpdateOne {
	_u.mutation.ClearBacklinks()
	return _u
}

// RemoveBacklinkIDs removes the "backlinks" edge to NoteLink entities by IDs.
func (_u *NoteUpdateOne) RemoveBacklinkIDs(ids ...uuid.UUID) *NoteUpdateOne {
	_u.mutation.RemoveBacklinkIDs(ids...)
	return _u
}

// RemoveBacklinks removes "backlinks" edges to NoteLink entities.
func (_u *NoteUpdateOne) RemoveBacklinks(v ...*NoteLink) *NoteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBacklinkIDs(ids...)
}

// ClearConnectionMaps clears all "connection_maps" edges to the NoteConnectionItemMap entity.
func (_u *NoteUpdateOne) ClearConnectionMaps() *NoteUpdateOne {
	_u.mutation.ClearConnectionMaps()
	return _u
}

// RemoveConnectionMapIDs removes the "connection_maps" edge to NoteConnectionItemMap entities by IDs.
func (_u *NoteUpdateOne) RemoveConnectionMapIDs(ids ...int) *NoteUpdateOne {
	_u.mutation.RemoveConnectionMapIDs(ids...)
	return _u
}

// RemoveConnectionMaps removes "connection_maps" edges to NoteConnectionItemMap entities.
func (_u *NoteUpdateOne) RemoveConnectionMaps(v ...*NoteConnectionItemMap) *NoteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConnectionMapIDs(ids...)
}

// ClearConnectionJobs clears all "connection_jobs" edges to the NoteConnectionJob entity.
func (_u *NoteUpdateOne) ClearConnectionJobs() *NoteUpdateOne {
	_u.mutation.ClearConnectionJobs()
	return _u
}

// RemoveConnectionJobIDs removes the "connection_jobs" edge to NoteConnectionJob entities by IDs.
func (_u *NoteUpdateOne) RemoveConnectionJobIDs(ids ...int) *NoteUpdateOne {
	_u.mutation.RemoveConnectionJobIDs(ids...)
	return _u
}

// RemoveConnectionJobs removes "connection_jobs" edges to NoteConnectionJob entities.
func (_u *NoteUpdateOne) RemoveConnectionJobs(v ...*NoteConnectionJob) *NoteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConnectionJobIDs(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *NoteUpdateOne) ClearTags() *NoteUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *NoteUpdateOne) RemoveTagIDs(ids ...uuid.UUID) *NoteUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *NoteUpdateOne) RemoveTags(v ...*Tag) *NoteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdateOne) Where(ps ...predicate.Note) *NoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NoteUpdateOne) Select(field string, fields ...string) *NoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Note entity.
func (_u *NoteUpdateOne) Save(ctx context.Context) (*Note, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdateOne) SaveX(ctx context.Context) *Note {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NoteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := note.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteUpdateOne) check() error {
	if v, ok := _u.mutation.ProtectionMode(); ok {
		if err := note.ProtectionModeValidator(v); err != nil {
			return &ValidationError{Name: "protection_mode", err: fmt.Errorf(`ent: validator failed for field "Note.protection_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *NoteUpdateOne) sqlSave(ctx context.Context) (_node *Note, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Note.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, note.FieldID)
		for _, f := range fields {
			if !note.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != note.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(note.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(note.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(note.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(note.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(note.FieldColor, field.TypeString)
	}
	if value, ok := _u.mutation.ProtectionMode(); ok {
		_spec.SetField(note.FieldProtectionMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProtectionPasswordHash(); ok {
		_spec.SetField(note.FieldProtectionPasswordHash, field.TypeString, value)
	}
	if _u.mutation.ProtectionPasswordHashCleared() {
		_spec.ClearField(note.FieldProtectionPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptedContent(); ok {
		_spec.SetField(note.FieldEncryptedContent, field.TypeString, value)
	}
	if _u.mutation.EncryptedContentCleared() {
		_spec.ClearField(note.FieldEncryptedContent, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptionAlg(); ok {
		_spec.SetField(note.FieldEncryptionAlg, field.TypeString, value)
	}
	if _u.mutation.EncryptionAlgCleared() {
		_spec.ClearField(note.FieldEncryptionAlg, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptionKdf(); ok {
		_spec.SetField(note.FieldEncryptionKdf, field.TypeString, value)
	}
	if _u.mutation.EncryptionKdfCleared() {
		_spec.ClearField(note.FieldEncryptionKdf, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptionSalt(); ok {
		_spec.SetField(note.FieldEncryptionSalt, field.TypeString, value)
	}
	if _u.mutation.EncryptionSaltCleared() {
		_spec.ClearField(note.FieldEncryptionSalt, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptionNonce(); ok {
		_spec.SetField(note.FieldEncryptionNonce, field.TypeString, value)
	}
	if _u.mutation.EncryptionNonceCleared() {
		_spec.ClearField(note.FieldEncryptionNonce, field.TypeString)
	}
	if value, ok := _u.mutation.IsStarred(); ok {
		_spec.SetField(note.FieldIsStarred, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(note.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(note.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(note.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.UserTable,
			Columns: []string{note.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.UserTable,
			Columns: []string{note.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FolderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.FolderTable,
			Columns: []string{note.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.FolderTable,
			Columns: []string{note.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.AttachmentsTable,
			Columns: []string{note.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.AttachmentsTable,
			Columns: []string{note.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.AttachmentsTable,
			Columns: []string{note.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WhiteboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.WhiteboardsTable,
			Columns: []string{note.WhiteboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(whiteboard.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWhiteboardsIDs(); len(nodes) > 0 && !_u.mutation.WhiteboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.WhiteboardsTable,
			Columns: []string{note.WhiteboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(whiteboard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WhiteboardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.WhiteboardsTable,
			Columns: []string{note.WhiteboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(whiteboard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutgoingLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.OutgoingLinksTable,
			Columns: []string{note.OutgoingLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutgoingLinksIDs(); len(nodes) > 0 && !_u.mutation.OutgoingLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.OutgoingLinksTable,
			Columns: []string{note.OutgoingLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutgoingLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.OutgoingLinksTable,
			Columns: []string{note.OutgoingLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BacklinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.BacklinksTable,
			Columns: []string{note.BacklinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBacklinksIDs(); len(nodes) > 0 && !_u.mutation.BacklinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.BacklinksTable,
			Columns: []string{note.BacklinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BacklinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.BacklinksTable,
			Columns: []string{note.BacklinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notelink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConnectionMapsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionMapsTable,
			Columns: []string{note.ConnectionMapsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionitemmap.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConnectionMapsIDs(); len(nodes) > 0 && !_u.mutation.ConnectionMapsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionMapsTable,
			Columns: []string{note.ConnectionMapsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionitemmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionMapsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionMapsTable,
			Columns: []string{note.ConnectionMapsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionitemmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConnectionJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionJobsTable,
			Columns: []string{note.ConnectionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionjob.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConnectionJobsIDs(); len(nodes) > 0 && !_u.mutation.ConnectionJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionJobsTable,
			Columns: []string{note.ConnectionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionjob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   note.ConnectionJobsTable,
			Columns: []string{note.ConnectionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionjob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   note.TagsTable,
			Columns: note.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   note.TagsTable,
			Columns: note.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   note.TagsTable,
			Columns: note.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Note{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
