// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"smarticky/ent/note"
	"smarticky/ent/noteconnectionaccount"
	"smarticky/ent/noteconnectionitemmap"
	"smarticky/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NoteConnectionItemMapUpdate is the builder for updating NoteConnectionItemMap entities.
type NoteConnectionItemMapUpdate struct {
	config
	hooks    []Hook
	mutation *NoteConnectionItemMapMutation
}

// Where appends a list predicates to the NoteConnectionItemMapUpdate builder.
func (_u *NoteConnectionItemMapUpdate) Where(ps ...predicate.NoteConnectionItemMap) *NoteConnectionItemMapUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *NoteConnectionItemMapUpdate) SetProvider(v string) *NoteConnectionItemMapUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableProvider(v *string) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *NoteConnectionItemMapUpdate) SetExternalID(v string) *NoteConnectionItemMapUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableExternalID(v *string) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *NoteConnectionItemMapUpdate) SetAccountID(v int) *NoteConnectionItemMapUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableAccountID(v *int) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetNoteID sets the "note_id" field.
func (_u *NoteConnectionItemMapUpdate) SetNoteID(v uuid.UUID) *NoteConnectionItemMapUpdate {
	_u.mutation.SetNoteID(v)
	return _u
}

// SetNillableNoteID sets the "note_id" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableNoteID(v *uuid.UUID) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetNoteID(*v)
	}
	return _u
}

// SetExternalTargetID sets the "external_target_id" field.
func (_u *NoteConnectionItemMapUpdate) SetExternalTargetID(v string) *NoteConnectionItemMapUpdate {
	_u.mutation.SetExternalTargetID(v)
	return _u
}

// SetNillableExternalTargetID sets the "external_target_id" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableExternalTargetID(v *string) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetExternalTargetID(*v)
	}
	return _u
}

// ClearExternalTargetID clears the value of the "external_target_id" field.
func (_u *NoteConnectionItemMapUpdate) ClearExternalTargetID() *NoteConnectionItemMapUpdate {
	_u.mutation.ClearExternalTargetID()
	return _u
}

// SetExternalPath sets the "external_path" field.
func (_u *NoteConnectionItemMapUpdate) SetExternalPath(v string) *NoteConnectionItemMapUpdate {
	_u.mutation.SetExternalPath(v)
	return _u
}

// SetNillableExternalPath sets the "external_path" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableExternalPath(v *string) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetExternalPath(*v)
	}
	return _u
}

// ClearExternalPath clears the value of the "external_path" field.
func (_u *NoteConnectionItemMapUpdate) ClearExternalPath() *NoteConnectionItemMapUpdate {
	_u.mutation.ClearExternalPath()
	return _u
}

// SetExternalURL sets the "external_url" field.
func (_u *NoteConnectionItemMapUpdate) SetExternalURL(v string) *NoteConnectionItemMapUpdate {
	_u.mutation.SetExternalURL(v)
	return _u
}

// SetNillableExternalURL sets the "external_url" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableExternalURL(v *string) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetExternalURL(*v)
	}
	return _u
}

// ClearExternalURL clears the value of the "external_url" field.
func (_u *NoteConnectionItemMapUpdate) ClearExternalURL() *NoteConnectionItemMapUpdate {
	_u.mutation.ClearExternalURL()
	return _u
}

// SetLastSyncDirection sets the "last_sync_direction" field.
func (_u *NoteConnectionItemMapUpdate) SetLastSyncDirection(v string) *NoteConnectionItemMapUpdate {
	_u.mutation.SetLastSyncDirection(v)
	return _u
}

// SetNillableLastSyncDirection sets the "last_sync_direction" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableLastSyncDirection(v *string) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetLastSyncDirection(*v)
	}
	return _u
}

// ClearLastSyncDirection clears the value of the "last_sync_direction" field.
func (_u *NoteConnectionItemMapUpdate) ClearLastSyncDirection() *NoteConnectionItemMapUpdate {
	_u.mutation.ClearLastSyncDirection()
	return _u
}

// SetLastImportedAt sets the "last_imported_at" field.
func (_u *NoteConnectionItemMapUpdate) SetLastImportedAt(v time.Time) *NoteConnectionItemMapUpdate {
	_u.mutation.SetLastImportedAt(v)
	return _u
}

// SetNillableLastImportedAt sets the "last_imported_at" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableLastImportedAt(v *time.Time) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetLastImportedAt(*v)
	}
	return _u
}

// ClearLastImportedAt clears the value of the "last_imported_at" field.
func (_u *NoteConnectionItemMapUpdate) ClearLastImportedAt() *NoteConnectionItemMapUpdate {
	_u.mutation.ClearLastImportedAt()
	return _u
}

// SetLastPushedAt sets the "last_pushed_at" field.
func (_u *NoteConnectionItemMapUpdate) SetLastPushedAt(v time.Time) *NoteConnectionItemMapUpdate {
	_u.mutation.SetLastPushedAt(v)
	return _u
}

// SetNillableLastPushedAt sets the "last_pushed_at" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableLastPushedAt(v *time.Time) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetLastPushedAt(*v)
	}
	return _u
}

// ClearLastPushedAt clears the value of the "last_pushed_at" field.
func (_u *NoteConnectionItemMapUpdate) ClearLastPushedAt() *NoteConnectionItemMapUpdate {
	_u.mutation.ClearLastPushedAt()
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *NoteConnectionItemMapUpdate) SetMetadataJSON(v string) *NoteConnectionItemMapUpdate {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdate) SetNillableMetadataJSON(v *string) *NoteConnectionItemMapUpdate {
	if v != nil {
		_u.SetMetadataJSON(*v)
	}
	return _u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (_u *NoteConnectionItemMapUpdate) ClearMetadataJSON() *NoteConnectionItemMapUpdate {
	_u.mutation.ClearMetadataJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NoteConnectionItemMapUpdate) SetUpdatedAt(v time.Time) *NoteConnectionItemMapUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the NoteConnectionAccount entity.
func (_u *NoteConnectionItemMapUpdate) SetAccount(v *NoteConnectionAccount) *NoteConnectionItemMapUpdate {
	return _u.SetAccountID(v.ID)
}

// SetNote sets the "note" edge to the Note entity.
func (_u *NoteConnectionItemMapUpdate) SetNote(v *Note) *NoteConnectionItemMapUpdate {
	return _u.SetNoteID(v.ID)
}

// Mutation returns the NoteConnectionItemMapMutation object of the builder.
func (_u *NoteConnectionItemMapUpdate) Mutation() *NoteConnectionItemMapMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the NoteConnectionAccount entity.
func (_u *NoteConnectionItemMapUpdate) ClearAccount() *NoteConnectionItemMapUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearNote clears the "note" edge to the Note entity.
func (_u *NoteConnectionItemMapUpdate) ClearNote() *NoteConnectionItemMapUpdate {
	_u.mutation.ClearNote()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NoteConnectionItemMapUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteConnectionItemMapUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NoteConnectionItemMapUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteConnectionItemMapUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NoteConnectionItemMapUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := noteconnectionitemmap.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteConnectionItemMapUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := noteconnectionitemmap.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "NoteConnectionItemMap.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := noteconnectionitemmap.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "NoteConnectionItemMap.external_id": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NoteConnectionItemMap.account"`)
	}
	if _u.mutation.NoteCleared() && len(_u.mutation.NoteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NoteConnectionItemMap.note"`)
	}
	return nil
}

func (_u *NoteConnectionItemMapUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(noteconnectionitemmap.Table, noteconnectionitemmap.Columns, sqlgraph.NewFieldSpec(noteconnectionitemmap.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(noteconnectionitemmap.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(noteconnectionitemmap.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalTargetID(); ok {
		_spec.SetField(noteconnectionitemmap.FieldExternalTargetID, field.TypeString, value)
	}
	if _u.mutation.ExternalTargetIDCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldExternalTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalPath(); ok {
		_spec.SetField(noteconnectionitemmap.FieldExternalPath, field.TypeString, value)
	}
	if _u.mutation.ExternalPathCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldExternalPath, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalURL(); ok {
		_spec.SetField(noteconnectionitemmap.FieldExternalURL, field.TypeString, value)
	}
	if _u.mutation.ExternalURLCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldExternalURL, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncDirection(); ok {
		_spec.SetField(noteconnectionitemmap.FieldLastSyncDirection, field.TypeString, value)
	}
	if _u.mutation.LastSyncDirectionCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldLastSyncDirection, field.TypeString)
	}
	if value, ok := _u.mutation.LastImportedAt(); ok {
		_spec.SetField(noteconnectionitemmap.FieldLastImportedAt, field.TypeTime, value)
	}
	if _u.mutation.LastImportedAtCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldLastImportedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPushedAt(); ok {
		_spec.SetField(noteconnectionitemmap.FieldLastPushedAt, field.TypeTime, value)
	}
	if _u.mutation.LastPushedAtCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldLastPushedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(noteconnectionitemmap.FieldMetadataJSON, field.TypeString, value)
	}
	if _u.mutation.MetadataJSONCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldMetadataJSON, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(noteconnectionitemmap.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteconnectionitemmap.AccountTable,
			Columns: []string{noteconnectionitemmap.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionaccount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteconnectionitemmap.AccountTable,
			Columns: []string{noteconnectionitemmap.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionaccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NoteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteconnectionitemmap.NoteTable,
			Columns: []string{noteconnectionitemmap.NoteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NoteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteconnectionitemmap.NoteTable,
			Columns: []string{noteconnectionitemmap.NoteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{noteconnectionitemmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NoteConnectionItemMapUpdateOne is the builder for updating a single NoteConnectionItemMap entity.
type NoteConnectionItemMapUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoteConnectionItemMapMutation
}

// SetProvider sets the "provider" field.
func (_u *NoteConnectionItemMapUpdateOne) SetProvider(v string) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableProvider(v *string) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *NoteConnectionItemMapUpdateOne) SetExternalID(v string) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableExternalID(v *string) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *NoteConnectionItemMapUpdateOne) SetAccountID(v int) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableAccountID(v *int) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetNoteID sets the "note_id" field.
func (_u *NoteConnectionItemMapUpdateOne) SetNoteID(v uuid.UUID) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetNoteID(v)
	return _u
}

// SetNillableNoteID sets the "note_id" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableNoteID(v *uuid.UUID) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetNoteID(*v)
	}
	return _u
}

// SetExternalTargetID sets the "external_target_id" field.
func (_u *NoteConnectionItemMapUpdateOne) SetExternalTargetID(v string) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetExternalTargetID(v)
	return _u
}

// SetNillableExternalTargetID sets the "external_target_id" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableExternalTargetID(v *string) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetExternalTargetID(*v)
	}
	return _u
}

// ClearExternalTargetID clears the value of the "external_target_id" field.
func (_u *NoteConnectionItemMapUpdateOne) ClearExternalTargetID() *NoteConnectionItemMapUpdateOne {
	_u.mutation.ClearExternalTargetID()
	return _u
}

// SetExternalPath sets the "external_path" field.
func (_u *NoteConnectionItemMapUpdateOne) SetExternalPath(v string) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetExternalPath(v)
	return _u
}

// SetNillableExternalPath sets the "external_path" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableExternalPath(v *string) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetExternalPath(*v)
	}
	return _u
}

// ClearExternalPath clears the value of the "external_path" field.
func (_u *NoteConnectionItemMapUpdateOne) ClearExternalPath() *NoteConnectionItemMapUpdateOne {
	_u.mutation.ClearExternalPath()
	return _u
}

// SetExternalURL sets the "external_url" field.
func (_u *NoteConnectionItemMapUpdateOne) SetExternalURL(v string) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetExternalURL(v)
	return _u
}

// SetNillableExternalURL sets the "external_url" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableExternalURL(v *string) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetExternalURL(*v)
	}
	return _u
}

// ClearExternalURL clears the value of the "external_url" field.
func (_u *NoteConnectionItemMapUpdateOne) ClearExternalURL() *NoteConnectionItemMapUpdateOne {
	_u.mutation.ClearExternalURL()
	return _u
}

// SetLastSyncDirection sets the "last_sync_direction" field.
func (_u *NoteConnectionItemMapUpdateOne) SetLastSyncDirection(v string) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetLastSyncDirection(v)
	return _u
}

// SetNillableLastSyncDirection sets the "last_sync_direction" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableLastSyncDirection(v *string) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetLastSyncDirection(*v)
	}
	return _u
}

// ClearLastSyncDirection clears the value of the "last_sync_direction" field.
func (_u *NoteConnectionItemMapUpdateOne) ClearLastSyncDirection() *NoteConnectionItemMapUpdateOne {
	_u.mutation.ClearLastSyncDirection()
	return _u
}

// SetLastImportedAt sets the "last_imported_at" field.
func (_u *NoteConnectionItemMapUpdateOne) SetLastImportedAt(v time.Time) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetLastImportedAt(v)
	return _u
}

// SetNillableLastImportedAt sets the "last_imported_at" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableLastImportedAt(v *time.Time) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetLastImportedAt(*v)
	}
	return _u
}

// ClearLastImportedAt clears the value of the "last_imported_at" field.
func (_u *NoteConnectionItemMapUpdateOne) ClearLastImportedAt() *NoteConnectionItemMapUpdateOne {
	_u.mutation.ClearLastImportedAt()
	return _u
}

// SetLastPushedAt sets the "last_pushed_at" field.
func (_u *NoteConnectionItemMapUpdateOne) SetLastPushedAt(v time.Time) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetLastPushedAt(v)
	return _u
}

// SetNillableLastPushedAt sets the "last_pushed_at" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableLastPushedAt(v *time.Time) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetLastPushedAt(*v)
	}
	return _u
}

// ClearLastPushedAt clears the value of the "last_pushed_at" field.
func (_u *NoteConnectionItemMapUpdateOne) ClearLastPushedAt() *NoteConnectionItemMapUpdateOne {
	_u.mutation.ClearLastPushedAt()
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *NoteConnectionItemMapUpdateOne) SetMetadataJSON(v string) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_u *NoteConnectionItemMapUpdateOne) SetNillableMetadataJSON(v *string) *NoteConnectionItemMapUpdateOne {
	if v != nil {
		_u.SetMetadataJSON(*v)
	}
	return _u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (_u *NoteConnectionItemMapUpdateOne) ClearMetadataJSON() *NoteConnectionItemMapUpdateOne {
	_u.mutation.ClearMetadataJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NoteConnectionItemMapUpdateOne) SetUpdatedAt(v time.Time) *NoteConnectionItemMapUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the NoteConnectionAccount entity.
func (_u *NoteConnectionItemMapUpdateOne) SetAccount(v *NoteConnectionAccount) *NoteConnectionItemMapUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetNote sets the "note" edge to the Note entity.
func (_u *NoteConnectionItemMapUpdateOne) SetNote(v *Note) *NoteConnectionItemMapUpdateOne {
	return _u.SetNoteID(v.ID)
}

// Mutation returns the NoteConnectionItemMapMutation object of the builder.
func (_u *NoteConnectionItemMapUpdateOne) Mutation() *NoteConnectionItemMapMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the NoteConnectionAccount entity.
func (_u *NoteConnectionItemMapUpdateOne) ClearAccount() *NoteConnectionItemMapUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearNote clears the "note" edge to the Note entity.
func (_u *NoteConnectionItemMapUpdateOne) ClearNote() *NoteConnectionItemMapUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// Where appends a list predicates to the NoteConnectionItemMapUpdate builder.
func (_u *NoteConnectionItemMapUpdateOne) Where(ps ...predicate.NoteConnectionItemMap) *NoteConnectionItemMapUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NoteConnectionItemMapUpdateOne) Select(field string, fields ...string) *NoteConnectionItemMapUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NoteConnectionItemMap entity.
func (_u *NoteConnectionItemMapUpdateOne) Save(ctx context.Context) (*NoteConnectionItemMap, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteConnectionItemMapUpdateOne) SaveX(ctx context.Context) *NoteConnectionItemMap {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NoteConnectionItemMapUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteConnectionItemMapUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NoteConnectionItemMapUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := noteconnectionitemmap.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteConnectionItemMapUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := noteconnectionitemmap.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "NoteConnectionItemMap.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := noteconnectionitemmap.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "NoteConnectionItemMap.external_id": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NoteConnectionItemMap.account"`)
	}
	if _u.mutation.NoteCleared() && len(_u.mutation.NoteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NoteConnectionItemMap.note"`)
	}
	return nil
}

func (_u *NoteConnectionItemMapUpdateOne) sqlSave(ctx context.Context) (_node *NoteConnectionItemMap, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(noteconnectionitemmap.Table, noteconnectionitemmap.Columns, sqlgraph.NewFieldSpec(noteconnectionitemmap.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NoteConnectionItemMap.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, noteconnectionitemmap.FieldID)
		for _, f := range fields {
			if !noteconnectionitemmap.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != noteconnectionitemmap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(noteconnectionitemmap.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(noteconnectionitemmap.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalTargetID(); ok {
		_spec.SetField(noteconnectionitemmap.FieldExternalTargetID, field.TypeString, value)
	}
	if _u.mutation.ExternalTargetIDCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldExternalTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalPath(); ok {
		_spec.SetField(noteconnectionitemmap.FieldExternalPath, field.TypeString, value)
	}
	if _u.mutation.ExternalPathCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldExternalPath, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalURL(); ok {
		_spec.SetField(noteconnectionitemmap.FieldExternalURL, field.TypeString, value)
	}
	if _u.mutation.ExternalURLCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldExternalURL, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncDirection(); ok {
		_spec.SetField(noteconnectionitemmap.FieldLastSyncDirection, field.TypeString, value)
	}
	if _u.mutation.LastSyncDirectionCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldLastSyncDirection, field.TypeString)
	}
	if value, ok := _u.mutation.LastImportedAt(); ok {
		_spec.SetField(noteconnectionitemmap.FieldLastImportedAt, field.TypeTime, value)
	}
	if _u.mutation.LastImportedAtCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldLastImportedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPushedAt(); ok {
		_spec.SetField(noteconnectionitemmap.FieldLastPushedAt, field.TypeTime, value)
	}
	if _u.mutation.LastPushedAtCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldLastPushedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(noteconnectionitemmap.FieldMetadataJSON, field.TypeString, value)
	}
	if _u.mutation.MetadataJSONCleared() {
		_spec.ClearField(noteconnectionitemmap.FieldMetadataJSON, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(noteconnectionitemmap.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteconnectionitemmap.AccountTable,
			Columns: []string{noteconnectionitemmap.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionaccount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteconnectionitemmap.AccountTable,
			Columns: []string{noteconnectionitemmap.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(noteconnectionaccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NoteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteconnectionitemmap.NoteTable,
			Columns: []string{noteconnectionitemmap.NoteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NoteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   noteconnectionitemmap.NoteTable,
			Columns: []string{noteconnectionitemmap.NoteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NoteConnectionItemMap{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{noteconnectionitemmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
