// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"smarticky/ent/note"
	"smarticky/ent/user"
	"smarticky/ent/whiteboard"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Whiteboard is the model entity for the Whiteboard schema.
type Whiteboard struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// SceneJSON holds the value of the "scene_json" field.
	SceneJSON string `json:"scene_json,omitempty"`
	// Thumbnail holds the value of the "thumbnail" field.
	Thumbnail string `json:"thumbnail,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WhiteboardQuery when eager-loading is set.
	Edges            WhiteboardEdges `json:"edges"`
	note_whiteboards *uuid.UUID
	user_whiteboards *int
	selectValues     sql.SelectValues
}

// WhiteboardEdges holds the relations/edges for other nodes in the graph.
type WhiteboardEdges struct {
	// Note holds the value of the note edge.
	Note *Note `json:"note,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// NoteOrErr returns the Note value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WhiteboardEdges) NoteOrErr() (*Note, error) {
	if e.Note != nil {
		return e.Note, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: note.Label}
	}
	return nil, &NotLoadedError{edge: "note"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WhiteboardEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Whiteboard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case whiteboard.FieldTitle, whiteboard.FieldSceneJSON, whiteboard.FieldThumbnail:
			values[i] = new(sql.NullString)
		case whiteboard.FieldCreatedAt, whiteboard.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case whiteboard.FieldID:
			values[i] = new(uuid.UUID)
		case whiteboard.ForeignKeys[0]: // note_whiteboards
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case whiteboard.ForeignKeys[1]: // user_whiteboards
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Whiteboard fields.
func (_m *Whiteboard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case whiteboard.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case whiteboard.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case whiteboard.FieldSceneJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scene_json", values[i])
			} else if value.Valid {
				_m.SceneJSON = value.String
			}
		case whiteboard.FieldThumbnail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail", values[i])
			} else if value.Valid {
				_m.Thumbnail = value.String
			}
		case whiteboard.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case whiteboard.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case whiteboard.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field note_whiteboards", values[i])
			} else if value.Valid {
				_m.note_whiteboards = new(uuid.UUID)
				*_m.note_whiteboards = *value.S.(*uuid.UUID)
			}
		case whiteboard.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_whiteboards", value)
			} else if value.Valid {
				_m.user_whiteboards = new(int)
				*_m.user_whiteboards = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Whiteboard.
// This includes values selected through modifiers, order, etc.
func (_m *Whiteboard) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNote queries the "note" edge of the Whiteboard entity.
func (_m *Whiteboard) QueryNote() *NoteQuery {
	return NewWhiteboardClient(_m.config).QueryNote(_m)
}

// QueryUser queries the "user" edge of the Whiteboard entity.
func (_m *Whiteboard) QueryUser() *UserQuery {
	return NewWhiteboardClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Whiteboard.
// Note that you need to call Whiteboard.Unwrap() before calling this method if this Whiteboard
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Whiteboard) Update() *WhiteboardUpdateOne {
	return NewWhiteboardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Whiteboard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Whiteboard) Unwrap() *Whiteboard {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Whiteboard is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Whiteboard) String() string {
	var builder strings.Builder
	builder.WriteString("Whiteboard(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("scene_json=")
	builder.WriteString(_m.SceneJSON)
	builder.WriteString(", ")
	builder.WriteString("thumbnail=")
	builder.WriteString(_m.Thumbnail)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Whiteboards is a parsable slice of Whiteboard.
type Whiteboards []*Whiteboard
