import { get, writable } from "svelte/store";

export type Language = "zh" | "en";
export type Theme = "light" | "dark";

interface PreferencesState {
  language: Language;
  sidebarCompact: boolean;
  theme: Theme;
}

const messages = {
  zh: {
    add: "添加",
    addAttachment: "添加附件",
    addTag: "添加标签",
    addTagFailed: "添加标签失败",
    actions: "操作",
    allNotes: "全部笔记",
    admin: "管理员",
    adminOnly: "仅管理员可访问",
    allUsers: "所有用户",
    apply: "应用",
    appVersion: "版本",
    assignTag: "归类到标签",
    attachments: "附件",
    availableTags: "可选标签",
    avatar: "头像",
    avatarFileTooLarge: "头像文件不能超过 2MB",
    avatarHint: "支持 JPG、PNG 或 GIF，最大 2MB",
    avatarUploadFailed: "头像上传失败",
    avatarUploaded: "头像已更新",
    backup: "备份",
    backupAutoEnable: "启用自动备份",
    backupConfirm: "开始备份到",
    backupConfigSaved: "备份配置已保存",
    backupDaily: "每天",
    backupDate: "日期",
    backupFailed: "备份失败",
    backupFilename: "文件名",
    backupFiles: "文件",
    backupLast: "上次备份",
    backupList: "查看备份",
    backupListTitle: "备份文件",
    backupManual: "手动",
    backupMaxCount: "最大备份数",
    backupMaxCountHelp: "仅保留最近的 N 个备份，0 表示不限制",
    backupNoFiles: "暂无备份文件",
    backupNow: "立即备份",
    backupRetentionDays: "保留天数",
    backupRetentionHelp: "删除超过指定天数的备份，0 表示不限制",
    backupSchedule: "备份计划",
    backupSettings: "设置",
    backupSize: "大小",
    backupSuccess: "备份成功",
    backupTitle: "备份与恢复",
    backupTotalSize: "总大小",
    backupVerify: "验证",
    backupVerifyConfirm: "验证备份",
    backupVerifyFailed: "备份验证失败",
    backupVerifySuccess: "备份有效",
    backupWeekly: "每周（周日）",
    buildTime: "编译时间",
    bold: "加粗",
    back: "返回",
    cancel: "取消",
    changePassword: "修改密码",
    closeSettings: "关闭设置面板",
    closeShareImage: "关闭生成图片",
    closeWhiteboard: "关闭白板",
    collapseSidebar: "收起侧栏",
    confirmNewPassword: "确认新密码",
    confirmPassword: "确认密码",
    contentEmpty: "没有正文",
    continueImport: "继续导入",
    copy: "复制",
    copyImage: "复制图片",
    copyImageFailed: "复制图片失败，请下载后分享",
    copyImageUnsupported: "当前浏览器不支持复制图片",
    copiedImage: "分享图片已复制",
    createNewUser: "创建新用户",
    createUser: "创建用户",
    createUserFailed: "创建用户失败",
    createdAt: "创建时间",
    currentTags: "当前标签",
    darkTheme: "深色",
    delete: "删除",
    deleteForever: "永久删除",
    deleteForeverFailed: "永久删除失败",
    deleteForeverMessage: "确认永久删除这篇笔记？此操作无法撤销。",
    deleteUser: "删除用户",
    deleteUserConfirm: "确认删除用户",
    deleteUserFailed: "删除用户失败",
    deletedNote: "笔记已永久删除",
    deleteForeverShort: "永久",
    details: "详情",
    done: "完成",
    displayNameRequired: "请输入显示名称",
    downloadPng: "下载 PNG",
    editor: "编辑器",
    email: "邮箱",
    emailAddress: "邮箱地址",
    emailInvalid: "请输入有效的邮箱地址",
    emptyNoteList: "写下你的第一篇笔记",
    emptyNoteListSubtitle: "记录想法，沉淀思考",
    emptyStarredTitle: "还没有收藏笔记",
    emptyStarredSubtitle: "把重要内容收藏起来，它们会出现在这里",
    emptyTrash: "清空废纸篓",
    emptyTrashFailed: "清空废纸篓失败",
    emptyTrashMessage: "确认永久删除废纸篓中的所有笔记？此操作无法撤销。",
    emptyTrashTitle: "废纸篓是空的",
    emptyTrashSubtitle: "移入废纸篓的笔记会在这里等待恢复或清空",
    emptiedTrash: "废纸篓已清空",
    enterEmail: "输入邮箱地址",
    enterFocus: "专注",
    enterNewPassword: "输入新密码（至少 6 个字符）",
    enterNickname: "输入昵称（可选）",
    enterOldPassword: "输入旧密码",
    enterPasswordMin: "输入密码（至少 6 个字符）",
    enterUsername: "输入用户名",
    expandSidebar: "展开侧栏",
    exitFocus: "退出",
    failed: "失败",
    fontDeleteConfirm: "确认删除字体",
    fontDeleteFailed: "字体删除失败",
    fontDeleteSuccess: "字体已删除",
    fontDisplayName: "显示名称",
    fontDisplayNamePlaceholder: "我的自定义字体",
    fontFile: "字体文件",
    fontFileHint: "支持 .ttf、.otf、.woff、.woff2，最大 30MB",
    fontFileRequired: "请选择字体文件",
    fontFileTooLarge: "字体文件不能超过 30MB",
    fontFormatInvalid: "不支持的字体格式",
    fontManagement: "字体管理",
    fontName: "字体名称",
    fontPreview: "字体预览",
    fontPrivateHint: "关闭后仅自己可见",
    fontUploadFailed: "字体上传失败",
    fontUploadSuccess: "字体已上传",
    format: "版式",
    generatedImage: "分享图片已生成",
    generateImage: "生成图片",
    generateImageShort: "出图",
    generateImageFailed: "生成图片失败",
    excalidrawLibraryImported: "Excalidraw 库已添加",
    excalidrawLibraryImportFailed: "添加 Excalidraw 库失败",
    gitCommit: "Git 提交",
    imageInsertAlt: "图片说明",
    imageLabel: "图",
    import: "导入",
    importCompleted: "导入完成",
    importCompletedPartial: "导入完成，部分条目失败",
    imported: "已导入",
    importing: "处理中",
    importFailed: "导入失败，请稍后重试",
    importStart: "开始导入",
    imageFileRequired: "请选择图片文件",
    language: "语言",
    drawioTemplateHint: "插入 draw.io XML 示例",
    insertDiagram: "插入图表",
    lazycatUid: "LazyCat 用户 ID",
    lazycatUidHint: "用于懒猫微服内应用委托访问 MCP 时映射到当前笔记用户。",
    lazycatUidPlaceholder: "例如：lazycat",
    lightTheme: "浅色",
    loadFailed: "加载失败",
    loadNotesFailed: "无法加载笔记，请稍后重试",
    loading: "加载中",
    loadingNotes: "正在加载笔记",
    logout: "退出登录",
    logoutConfirm: "确认退出当前账号？",
    chooseWritingMode: "选择排版模式",
    markdownMode: "Markdown 模式",
    markdownModeShort: "MD",
    markdownToolbar: "Markdown 工具栏",
    mermaidGroupAdvanced: "高级 / 实验",
    mermaidGroupData: "数据图",
    mermaidGroupFlow: "流程",
    mermaidGroupPlanning: "计划",
    mermaidGroupStructure: "结构",
    mermaidTemplates: "Mermaid 类型",
    mermaidTemplatesHint: "选择 Mermaid 后插入具体类型模板",
    moreActions: "更多操作",
    mcpAccess: "MCP 访问",
    mcpAccessHint: "外部客户端使用用户级 token 访问当前笔记账号的 MCP；懒猫微服内应用可通过用户映射访问。",
    mcpTokenCopied: "Token 已复制",
    mcpTokenCopyFailed: "Token 复制失败",
    mcpTokenCreate: "创建 Token",
    mcpTokenCreated: "MCP Token 已创建",
    mcpTokenCreateFailed: "创建 MCP Token 失败",
    mcpTokenDefaultName: "MCP Token",
    mcpTokenDeleteConfirm: "确认撤销这个 MCP Token？",
    mcpTokenDeleteFailed: "撤销 MCP Token 失败",
    mcpTokenDeleted: "MCP Token 已撤销",
    mcpTokenEmpty: "暂无 MCP Token",
    mcpTokenLastUsed: "上次使用",
    mcpTokenLoadFailed: "加载 MCP Token 失败",
    mcpTokenName: "Token 名称",
    mcpTokenNamePlaceholder: "例如：我的 Codex",
    mcpTokenOneTime: "请立即复制，此 token 只显示一次。",
    newNote: "新建笔记",
    noAttachments: "暂无附件",
    noFonts: "暂无字体",
    noTags: "暂无标签",
    noUsers: "暂无用户",
    no: "否",
    noteInfo: "笔记信息",
    noteList: "笔记列表",
    noteLocation: "笔记归类",
    notes: "笔记",
    noteTitle: "笔记标题",
    newPassword: "新密码",
    nickname: "昵称",
    oldPassword: "旧密码",
    insertImage: "插入图片",
    italic: "斜体",
    orderedList: "有序列表",
    password: "密码",
    passwordChangeFailed: "密码修改失败",
    passwordChanged: "密码已修改",
    passwordNotMatch: "两次密码不一致",
    passwordRequired: "请填写所有密码字段",
    passwordTooShort: "密码至少需要 6 个字符",
    personalProfile: "个人资料",
    plainTextMode: "纯文本模式",
    plainTextModeShort: "无",
    preparing: "正在准备笔记工作台",
    profileSaveFailed: "个人资料保存失败",
    profileSaved: "个人资料已保存",
    refresh: "刷新",
    restore: "恢复",
    restoreConfirm: "确认从备份恢复",
    restoreFailed: "恢复失败",
    restoreNote: "恢复笔记",
    restoreNoteMessage: "确认将这篇笔记恢复到普通列表？",
    restoredNote: "已恢复笔记",
    restoreSuccess: "恢复成功，请重启应用使数据完全生效",
    role: "角色",
    saveError: "保存失败",
    saveConfig: "保存配置",
    saveFailed: "保存失败",
    saveSettings: "保存设置",
    saved: "已保存",
    saving: "正在保存",
    searchNotes: "搜索笔记",
    selectFile: "选择 .enex 文件",
    selectFileFirst: "请先选择 .enex 文件",
    selectImportFile: "选择 Evernote ENEX 文件",
    selectOrCreate: "选择一篇笔记，或新建一篇",
    settings: "设置",
    sessionExpired: "登录已过期",
    shareClassic: "白底经典",
    shareDialogLabel: "生成分享图片",
    shareNight: "夜读",
    sharePaper: "暖纸长文",
    shareSignature: "导出图片默认落款",
    shareSignatureHint: "用于生成分享图片时底部的默认署名；每次导出前仍可临时修改。",
    shareSignaturePlaceholder: "例如：Smarticky / 你的名字",
    shareSignatureTemporary: "本次图片落款",
    shareSmartisanSubtitle: "Smartisan 风格排版",
    shareWithAllUsers: "与所有用户共享",
    showDetails: "信息",
    skipped: "已跳过",
    sourceMode: "源码编辑",
    squareImage: "方图",
    starred: "收藏",
    star: "收藏",
    starAdded: "已收藏",
    starRemoved: "已取消收藏",
    selectedFont: "编辑器字体",
    shared: "共享",
    size: "大小",
    s3AccessKey: "访问密钥",
    s3Bucket: "存储桶",
    s3Endpoint: "端点地址",
    s3Region: "区域",
    s3SecretKey: "密钥",
    systemDefault: "系统默认",
    systemFonts: "系统字体",
    tags: "标签",
    task: "待办",
    theme: "主题",
    today: "今天",
    trash: "废纸篓",
    trashFailed: "移动失败",
    trashNote: "移入废纸篓",
    trashNoteMessage: "确认将这篇笔记移入废纸篓？",
    trashedNote: "已移入废纸篓",
    untitled: "未命名",
    unknown: "未知",
    uploadAttachmentFailed: "上传附件失败",
    uploadAvatar: "上传头像",
    uploadFont: "上传字体",
    uploadFontButton: "上传字体",
    uploadedBy: "上传者",
    uploadedFonts: "已上传字体",
    unorderedList: "无序列表",
    userCreated: "用户已创建",
    userManagement: "用户管理",
    userDeleted: "用户已删除",
    username: "用户名",
    usernamePasswordRequired: "用户名和密码不能为空",
    userRole: "普通用户",
    currentUser: "当前用户",
    updateStarFailed: "更新收藏状态失败",
    versionUnavailable: "版本信息不可用",
    warnings: "提示",
    webdavPassword: "密码",
    webdavUrl: "WebDAV 地址",
    webdavUsername: "用户名",
    whiteboard: "白板",
    whiteboardCreateFailed: "创建白板失败",
    whiteboardDeleteConfirm: "删除白板",
    whiteboardDeleted: "白板已删除",
    whiteboardDeletedWithReference: "白板已删除，引用已移除",
    whiteboardDeleteFailed: "删除白板失败",
    whiteboardDeleteMessage: "确认删除这个白板？会同时移除笔记里的引用块，此操作无法撤销。",
    whiteboardLoadFailed: "加载白板失败",
    whiteboardSaveFailed: "保存白板失败",
    whiteboardTemplateHint: "创建可编辑白板并插入引用",
    whiteboardTitle: "白板标题",
    wideImage: "长图",
    wordUnit: "字",
    writingMode: "排版模式",
    wysiwygMode: "所见即所得",
    yes: "是",
    yesterday: "昨天",
  },
  en: {
    add: "Add",
    addAttachment: "Add attachment",
    addTag: "Add tag",
    addTagFailed: "Failed to add tag",
    actions: "Actions",
    allNotes: "All notes",
    admin: "Admin",
    adminOnly: "Admin only",
    allUsers: "All users",
    apply: "Apply",
    appVersion: "Version",
    assignTag: "Assign tag",
    attachments: "Attachments",
    availableTags: "Available tags",
    avatar: "Avatar",
    avatarFileTooLarge: "Avatar must be under 2MB",
    avatarHint: "JPG, PNG, or GIF, up to 2MB",
    avatarUploadFailed: "Avatar upload failed",
    avatarUploaded: "Avatar updated",
    backup: "Backup",
    backupAutoEnable: "Enable automatic backup",
    backupConfirm: "Start backup to",
    backupConfigSaved: "Backup configuration saved",
    backupDaily: "Daily",
    backupDate: "Date",
    backupFailed: "Backup failed",
    backupFilename: "Filename",
    backupFiles: "Files",
    backupLast: "Last backup",
    backupList: "View backups",
    backupListTitle: "Backup files",
    backupManual: "Manual",
    backupMaxCount: "Maximum backups",
    backupMaxCountHelp: "Keep only the most recent N backups. 0 means no limit",
    backupNoFiles: "No backup files found",
    backupNow: "Backup now",
    backupRetentionDays: "Retention days",
    backupRetentionHelp: "Delete backups older than this many days. 0 means no limit",
    backupSchedule: "Backup schedule",
    backupSettings: "Settings",
    backupSize: "Size",
    backupSuccess: "Backup successful",
    backupTitle: "Backup & Restore",
    backupTotalSize: "Total size",
    backupVerify: "Verify",
    backupVerifyConfirm: "Verify backup",
    backupVerifyFailed: "Backup verification failed",
    backupVerifySuccess: "Backup is valid",
    backupWeekly: "Weekly (Sunday)",
    buildTime: "Build time",
    bold: "Bold",
    back: "Back",
    cancel: "Cancel",
    changePassword: "Change password",
    closeSettings: "Close settings panel",
    closeShareImage: "Close image generator",
    closeWhiteboard: "Close whiteboard",
    collapseSidebar: "Collapse sidebar",
    confirmNewPassword: "Confirm new password",
    confirmPassword: "Confirm password",
    contentEmpty: "No body",
    continueImport: "Import another",
    copy: "Copy",
    copyImage: "Copy image",
    copyImageFailed: "Copy failed. Download the image instead",
    copyImageUnsupported: "This browser cannot copy images",
    copiedImage: "Image copied",
    createNewUser: "Create new user",
    createUser: "Create user",
    createUserFailed: "Failed to create user",
    createdAt: "Created",
    currentTags: "Current tags",
    darkTheme: "Dark",
    delete: "Delete",
    deleteForever: "Delete forever",
    deleteForeverFailed: "Permanent delete failed",
    deleteForeverMessage: "Delete this note forever? This cannot be undone.",
    deleteUser: "Delete user",
    deleteUserConfirm: "Delete user",
    deleteUserFailed: "Failed to delete user",
    deletedNote: "Note deleted forever",
    deleteForeverShort: "Delete",
    details: "Details",
    done: "Done",
    displayNameRequired: "Enter a display name",
    downloadPng: "Download PNG",
    editor: "Editor",
    email: "Email",
    emailAddress: "Email address",
    emailInvalid: "Enter a valid email address",
    emptyNoteList: "Write your first note",
    emptyNoteListSubtitle: "Capture thoughts and keep them clear",
    emptyStarredTitle: "No starred notes yet",
    emptyStarredSubtitle: "Star important notes and they will appear here",
    emptyTrash: "Empty trash",
    emptyTrashFailed: "Failed to empty trash",
    emptyTrashMessage: "Delete every note in trash forever? This cannot be undone.",
    emptyTrashTitle: "Trash is empty",
    emptyTrashSubtitle: "Deleted notes wait here until you restore or empty them",
    emptiedTrash: "Trash emptied",
    enterEmail: "Enter email address",
    enterFocus: "Focus",
    enterNewPassword: "Enter new password (min 6 characters)",
    enterNickname: "Enter nickname (optional)",
    enterOldPassword: "Enter old password",
    enterPasswordMin: "Enter password (min 6 characters)",
    enterUsername: "Enter username",
    expandSidebar: "Expand sidebar",
    exitFocus: "Exit",
    failed: "Failed",
    fontDeleteConfirm: "Delete font",
    fontDeleteFailed: "Font deletion failed",
    fontDeleteSuccess: "Font deleted",
    fontDisplayName: "Display name",
    fontDisplayNamePlaceholder: "My custom font",
    fontFile: "Font file",
    fontFileHint: "Supports .ttf, .otf, .woff, .woff2, up to 30MB",
    fontFileRequired: "Choose a font file",
    fontFileTooLarge: "Font must be under 30MB",
    fontFormatInvalid: "Unsupported font format",
    fontManagement: "Fonts",
    fontName: "Font name",
    fontPreview: "Preview",
    fontPrivateHint: "Turn off to keep this font private",
    fontUploadFailed: "Font upload failed",
    fontUploadSuccess: "Font uploaded",
    format: "Format",
    generatedImage: "Share image generated",
    generateImage: "Generate image",
    generateImageShort: "Image",
    generateImageFailed: "Image generation failed",
    excalidrawLibraryImported: "Excalidraw library added",
    excalidrawLibraryImportFailed: "Failed to add Excalidraw library",
    gitCommit: "Git commit",
    imageInsertAlt: "Image description",
    imageLabel: "Img",
    import: "Import",
    importCompleted: "Import completed",
    importCompletedPartial: "Import completed with some failures",
    imported: "Imported",
    importing: "Processing",
    importFailed: "Import failed. Try again later",
    importStart: "Start import",
    imageFileRequired: "Choose an image file",
    drawioTemplateHint: "Insert a draw.io XML example",
    insertDiagram: "Insert diagram",
    language: "Language",
    lazycatUid: "LazyCat user ID",
    lazycatUidHint: "Maps delegated LazyCat MCP access to this notes user.",
    lazycatUidPlaceholder: "Example: lazycat",
    lightTheme: "Light",
    loadFailed: "Load failed",
    loadNotesFailed: "Could not load notes. Try again later",
    loading: "Loading",
    loadingNotes: "Loading notes",
    logout: "Log out",
    logoutConfirm: "Log out of the current account?",
    chooseWritingMode: "Choose writing mode",
    markdownMode: "Markdown mode",
    markdownModeShort: "MD",
    markdownToolbar: "Markdown toolbar",
    mermaidGroupAdvanced: "Advanced / experimental",
    mermaidGroupData: "Data",
    mermaidGroupFlow: "Flow",
    mermaidGroupPlanning: "Planning",
    mermaidGroupStructure: "Structure",
    mermaidTemplates: "Mermaid types",
    mermaidTemplatesHint: "Choose Mermaid first, then insert a typed template",
    moreActions: "More actions",
    mcpAccess: "MCP access",
    mcpAccessHint: "External clients use user-level tokens for this notes account. LazyCat apps can use delegated user mapping.",
    mcpTokenCopied: "Token copied",
    mcpTokenCopyFailed: "Token copy failed",
    mcpTokenCreate: "Create token",
    mcpTokenCreated: "MCP token created",
    mcpTokenCreateFailed: "Failed to create MCP token",
    mcpTokenDefaultName: "MCP Token",
    mcpTokenDeleteConfirm: "Revoke this MCP token?",
    mcpTokenDeleteFailed: "Failed to revoke MCP token",
    mcpTokenDeleted: "MCP token revoked",
    mcpTokenEmpty: "No MCP tokens",
    mcpTokenLastUsed: "Last used",
    mcpTokenLoadFailed: "Failed to load MCP tokens",
    mcpTokenName: "Token name",
    mcpTokenNamePlaceholder: "Example: My Codex",
    mcpTokenOneTime: "Copy this token now. It is shown only once.",
    newNote: "New note",
    noAttachments: "No attachments",
    noFonts: "No fonts",
    noTags: "No tags",
    noUsers: "No users",
    no: "No",
    noteInfo: "Note info",
    noteList: "Note list",
    noteLocation: "Note location",
    notes: "Notes",
    noteTitle: "Note title",
    newPassword: "New password",
    nickname: "Nickname",
    oldPassword: "Old password",
    insertImage: "Insert image",
    italic: "Italic",
    orderedList: "Ordered list",
    password: "Password",
    passwordChangeFailed: "Password change failed",
    passwordChanged: "Password changed",
    passwordNotMatch: "Passwords do not match",
    passwordRequired: "Fill in all password fields",
    passwordTooShort: "Password must be at least 6 characters",
    personalProfile: "Profile",
    plainTextMode: "Plain text mode",
    plainTextModeShort: "Text",
    preparing: "Preparing your notes workspace",
    profileSaveFailed: "Profile save failed",
    profileSaved: "Profile saved",
    refresh: "Refresh",
    restore: "Restore",
    restoreConfirm: "Restore from backup",
    restoreFailed: "Restore failed",
    restoreNote: "Restore note",
    restoreNoteMessage: "Restore this note to the main list?",
    restoredNote: "Note restored",
    restoreSuccess: "Restore successful. Restart the app for changes to fully apply",
    role: "Role",
    saveConfig: "Save config",
    saveError: "Save failed",
    saveFailed: "Save failed",
    saveSettings: "Save settings",
    saved: "Saved",
    saving: "Saving",
    searchNotes: "Search notes",
    selectFile: "Choose .enex file",
    selectFileFirst: "Choose an .enex file first",
    selectImportFile: "Choose Evernote ENEX file",
    selectOrCreate: "Select a note or create one",
    settings: "Settings",
    sessionExpired: "Session expired",
    shareClassic: "Classic white",
    shareDialogLabel: "Generate share image",
    shareNight: "Night reading",
    sharePaper: "Warm paper",
    shareSignature: "Default image export signature",
    shareSignatureHint: "Used as the footer signature when generating share images. You can still override it before each export.",
    shareSignaturePlaceholder: "Example: Smarticky / your name",
    shareSignatureTemporary: "Signature for this image",
    shareSmartisanSubtitle: "Smartisan-style typography",
    shareWithAllUsers: "Share with all users",
    showDetails: "Info",
    skipped: "Skipped",
    sourceMode: "Source mode",
    squareImage: "Square",
    starred: "Starred",
    star: "Star",
    starAdded: "Starred",
    starRemoved: "Unstarred",
    selectedFont: "Editor font",
    shared: "Shared",
    size: "Size",
    s3AccessKey: "Access key",
    s3Bucket: "Bucket",
    s3Endpoint: "Endpoint",
    s3Region: "Region",
    s3SecretKey: "Secret key",
    systemDefault: "System default",
    systemFonts: "System fonts",
    tags: "Tags",
    task: "Task",
    theme: "Theme",
    today: "Today",
    trash: "Trash",
    trashFailed: "Move failed",
    trashNote: "Move to trash",
    trashNoteMessage: "Move this note to trash?",
    trashedNote: "Moved to trash",
    untitled: "Untitled",
    unknown: "Unknown",
    uploadAttachmentFailed: "Attachment upload failed",
    uploadAvatar: "Upload avatar",
    uploadFont: "Upload font",
    uploadFontButton: "Upload font",
    uploadedBy: "Uploaded by",
    uploadedFonts: "Uploaded fonts",
    unorderedList: "Bulleted list",
    userCreated: "User created",
    userDeleted: "User deleted",
    userManagement: "Users",
    username: "Username",
    usernamePasswordRequired: "Username and password are required",
    userRole: "User",
    currentUser: "Current user",
    updateStarFailed: "Failed to update star",
    versionUnavailable: "Version unavailable",
    warnings: "Warnings",
    webdavPassword: "Password",
    webdavUrl: "WebDAV URL",
    webdavUsername: "Username",
    whiteboard: "Whiteboard",
    whiteboardCreateFailed: "Failed to create whiteboard",
    whiteboardDeleteConfirm: "Delete whiteboard",
    whiteboardDeleted: "Whiteboard deleted",
    whiteboardDeletedWithReference: "Whiteboard deleted and reference removed",
    whiteboardDeleteFailed: "Failed to delete whiteboard",
    whiteboardDeleteMessage: "Delete this whiteboard? Its note reference block will be removed too. This cannot be undone.",
    whiteboardLoadFailed: "Failed to load whiteboard",
    whiteboardSaveFailed: "Failed to save whiteboard",
    whiteboardTemplateHint: "Create an editable whiteboard reference",
    whiteboardTitle: "Whiteboard title",
    wideImage: "Long image",
    wordUnit: "chars",
    writingMode: "Writing mode",
    wysiwygMode: "WYSIWYG mode",
    yes: "Yes",
    yesterday: "Yesterday",
  },
} satisfies Record<Language, Record<string, string>>;

export type MessageKey = keyof typeof messages.zh;

function storedLanguage(): Language {
  if (typeof localStorage !== "undefined") {
    const saved = localStorage.getItem("language");
    if (saved === "zh" || saved === "en") return saved;
  }
  if (typeof navigator !== "undefined" && navigator.language.startsWith("zh")) {
    return "zh";
  }
  return "en";
}

function storedTheme(): Theme {
  if (typeof localStorage !== "undefined") {
    const saved = localStorage.getItem("theme");
    if (saved === "light" || saved === "dark") return saved;
  }
  if (
    typeof window !== "undefined" &&
    window.matchMedia("(prefers-color-scheme: dark)").matches
  ) {
    return "dark";
  }
  return "light";
}

function storedSidebarCompact(): boolean {
  if (typeof localStorage !== "undefined") {
    return localStorage.getItem("sidebar-compact") === "true";
  }
  return false;
}

function applyPreferences(state: PreferencesState): void {
  if (typeof document === "undefined") return;
  document.documentElement.lang = state.language === "zh" ? "zh-CN" : "en";
  document.documentElement.dataset.sidebar = state.sidebarCompact
    ? "compact"
    : "wide";
  document.documentElement.dataset.theme = state.theme;
}

function createPreferencesStore() {
  const initial = {
    language: storedLanguage(),
    sidebarCompact: storedSidebarCompact(),
    theme: storedTheme(),
  };
  const { subscribe, set, update } = writable<PreferencesState>(initial);
  applyPreferences(initial);

  function commit(next: PreferencesState): PreferencesState {
    if (typeof localStorage !== "undefined") {
      localStorage.setItem("language", next.language);
      localStorage.setItem("sidebar-compact", String(next.sidebarCompact));
      localStorage.setItem("theme", next.theme);
    }
    applyPreferences(next);
    return next;
  }

  return {
    subscribe,
    hydrate() {
      set(
        commit({
          language: storedLanguage(),
          sidebarCompact: storedSidebarCompact(),
          theme: storedTheme(),
        }),
      );
    },
    setLanguage(language: Language) {
      update((state) => commit({ ...state, language }));
    },
    toggleLanguage() {
      update((state) =>
        commit({ ...state, language: state.language === "zh" ? "en" : "zh" }),
      );
    },
    toggleSidebarCompact() {
      update((state) =>
        commit({ ...state, sidebarCompact: !state.sidebarCompact }),
      );
    },
    setTheme(theme: Theme) {
      update((state) => commit({ ...state, theme }));
    },
    toggleTheme() {
      update((state) =>
        commit({ ...state, theme: state.theme === "light" ? "dark" : "light" }),
      );
    },
  };
}

export const preferencesStore = createPreferencesStore();

export function t(
  key: MessageKey,
  language: Language = get(preferencesStore).language,
): string {
  return messages[language][key] ?? messages.zh[key] ?? key;
}
