// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// FieldShareSignature holds the string denoting the share_signature field in the database.
	FieldShareSignature = "share_signature"
	// FieldTimeZone holds the string denoting the time_zone field in the database.
	FieldTimeZone = "time_zone"
	// FieldLazycatUID holds the string denoting the lazycat_uid field in the database.
	FieldLazycatUID = "lazycat_uid"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeNotes holds the string denoting the notes edge name in mutations.
	EdgeNotes = "notes"
	// EdgeFolders holds the string denoting the folders edge name in mutations.
	EdgeFolders = "folders"
	// EdgeAttachments holds the string denoting the attachments edge name in mutations.
	EdgeAttachments = "attachments"
	// EdgeExcalidrawLibrary holds the string denoting the excalidraw_library edge name in mutations.
	EdgeExcalidrawLibrary = "excalidraw_library"
	// EdgeWhiteboards holds the string denoting the whiteboards edge name in mutations.
	EdgeWhiteboards = "whiteboards"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// EdgeFonts holds the string denoting the fonts edge name in mutations.
	EdgeFonts = "fonts"
	// EdgeImportJobs holds the string denoting the import_jobs edge name in mutations.
	EdgeImportJobs = "import_jobs"
	// EdgeMcpTokens holds the string denoting the mcp_tokens edge name in mutations.
	EdgeMcpTokens = "mcp_tokens"
	// EdgeMcpImages holds the string denoting the mcp_images edge name in mutations.
	EdgeMcpImages = "mcp_images"
	// Table holds the table name of the user in the database.
	Table = "users"
	// NotesTable is the table that holds the notes relation/edge.
	NotesTable = "notes"
	// NotesInverseTable is the table name for the Note entity.
	// It exists in this package in order to avoid circular dependency with the "note" package.
	NotesInverseTable = "notes"
	// NotesColumn is the table column denoting the notes relation/edge.
	NotesColumn = "user_notes"
	// FoldersTable is the table that holds the folders relation/edge.
	FoldersTable = "folders"
	// FoldersInverseTable is the table name for the Folder entity.
	// It exists in this package in order to avoid circular dependency with the "folder" package.
	FoldersInverseTable = "folders"
	// FoldersColumn is the table column denoting the folders relation/edge.
	FoldersColumn = "user_folders"
	// AttachmentsTable is the table that holds the attachments relation/edge.
	AttachmentsTable = "attachments"
	// AttachmentsInverseTable is the table name for the Attachment entity.
	// It exists in this package in order to avoid circular dependency with the "attachment" package.
	AttachmentsInverseTable = "attachments"
	// AttachmentsColumn is the table column denoting the attachments relation/edge.
	AttachmentsColumn = "user_attachments"
	// ExcalidrawLibraryTable is the table that holds the excalidraw_library relation/edge.
	ExcalidrawLibraryTable = "excalidraw_libraries"
	// ExcalidrawLibraryInverseTable is the table name for the ExcalidrawLibrary entity.
	// It exists in this package in order to avoid circular dependency with the "excalidrawlibrary" package.
	ExcalidrawLibraryInverseTable = "excalidraw_libraries"
	// ExcalidrawLibraryColumn is the table column denoting the excalidraw_library relation/edge.
	ExcalidrawLibraryColumn = "user_excalidraw_library"
	// WhiteboardsTable is the table that holds the whiteboards relation/edge.
	WhiteboardsTable = "whiteboards"
	// WhiteboardsInverseTable is the table name for the Whiteboard entity.
	// It exists in this package in order to avoid circular dependency with the "whiteboard" package.
	WhiteboardsInverseTable = "whiteboards"
	// WhiteboardsColumn is the table column denoting the whiteboards relation/edge.
	WhiteboardsColumn = "user_whiteboards"
	// TagsTable is the table that holds the tags relation/edge.
	TagsTable = "tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
	// TagsColumn is the table column denoting the tags relation/edge.
	TagsColumn = "user_tags"
	// FontsTable is the table that holds the fonts relation/edge.
	FontsTable = "fonts"
	// FontsInverseTable is the table name for the Font entity.
	// It exists in this package in order to avoid circular dependency with the "font" package.
	FontsInverseTable = "fonts"
	// FontsColumn is the table column denoting the fonts relation/edge.
	FontsColumn = "user_fonts"
	// ImportJobsTable is the table that holds the import_jobs relation/edge.
	ImportJobsTable = "import_jobs"
	// ImportJobsInverseTable is the table name for the ImportJob entity.
	// It exists in this package in order to avoid circular dependency with the "importjob" package.
	ImportJobsInverseTable = "import_jobs"
	// ImportJobsColumn is the table column denoting the import_jobs relation/edge.
	ImportJobsColumn = "user_import_jobs"
	// McpTokensTable is the table that holds the mcp_tokens relation/edge.
	McpTokensTable = "mcp_tokens"
	// McpTokensInverseTable is the table name for the MCPToken entity.
	// It exists in this package in order to avoid circular dependency with the "mcptoken" package.
	McpTokensInverseTable = "mcp_tokens"
	// McpTokensColumn is the table column denoting the mcp_tokens relation/edge.
	McpTokensColumn = "user_mcp_tokens"
	// McpImagesTable is the table that holds the mcp_images relation/edge.
	McpImagesTable = "mcp_images"
	// McpImagesInverseTable is the table name for the MCPImage entity.
	// It exists in this package in order to avoid circular dependency with the "mcpimage" package.
	McpImagesInverseTable = "mcp_images"
	// McpImagesColumn is the table column denoting the mcp_images relation/edge.
	McpImagesColumn = "user_mcp_images"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPasswordHash,
	FieldEmail,
	FieldNickname,
	FieldRole,
	FieldAvatar,
	FieldShareSignature,
	FieldTimeZone,
	FieldLazycatUID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultNickname holds the default value on creation for the "nickname" field.
	DefaultNickname string
	// DefaultAvatar holds the default value on creation for the "avatar" field.
	DefaultAvatar string
	// DefaultShareSignature holds the default value on creation for the "share_signature" field.
	DefaultShareSignature string
	// DefaultTimeZone holds the default value on creation for the "time_zone" field.
	DefaultTimeZone string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Role defines the type for the "role" enum field.
type Role string

// RoleUser is the default value of the Role enum.
const DefaultRole = RoleUser

// Role values.
const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleAdmin, RoleUser:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByAvatar orders the results by the avatar field.
func ByAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatar, opts...).ToFunc()
}

// ByShareSignature orders the results by the share_signature field.
func ByShareSignature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShareSignature, opts...).ToFunc()
}

// ByTimeZone orders the results by the time_zone field.
func ByTimeZone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeZone, opts...).ToFunc()
}

// ByLazycatUID orders the results by the lazycat_uid field.
func ByLazycatUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLazycatUID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNotesCount orders the results by notes count.
func ByNotesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotesStep(), opts...)
	}
}

// ByNotes orders the results by notes terms.
func ByNotes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFoldersCount orders the results by folders count.
func ByFoldersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFoldersStep(), opts...)
	}
}

// ByFolders orders the results by folders terms.
func ByFolders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFoldersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAttachmentsCount orders the results by attachments count.
func ByAttachmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttachmentsStep(), opts...)
	}
}

// ByAttachments orders the results by attachments terms.
func ByAttachments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttachmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByExcalidrawLibraryField orders the results by excalidraw_library field.
func ByExcalidrawLibraryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExcalidrawLibraryStep(), sql.OrderByField(field, opts...))
	}
}

// ByWhiteboardsCount orders the results by whiteboards count.
func ByWhiteboardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWhiteboardsStep(), opts...)
	}
}

// ByWhiteboards orders the results by whiteboards terms.
func ByWhiteboards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWhiteboardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFontsCount orders the results by fonts count.
func ByFontsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFontsStep(), opts...)
	}
}

// ByFonts orders the results by fonts terms.
func ByFonts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFontsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByImportJobsCount orders the results by import_jobs count.
func ByImportJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newImportJobsStep(), opts...)
	}
}

// ByImportJobs orders the results by import_jobs terms.
func ByImportJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newImportJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMcpTokensCount orders the results by mcp_tokens count.
func ByMcpTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMcpTokensStep(), opts...)
	}
}

// ByMcpTokens orders the results by mcp_tokens terms.
func ByMcpTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMcpTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMcpImagesCount orders the results by mcp_images count.
func ByMcpImagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMcpImagesStep(), opts...)
	}
}

// ByMcpImages orders the results by mcp_images terms.
func ByMcpImages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMcpImagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNotesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotesTable, NotesColumn),
	)
}
func newFoldersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FoldersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FoldersTable, FoldersColumn),
	)
}
func newAttachmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttachmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
	)
}
func newExcalidrawLibraryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExcalidrawLibraryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ExcalidrawLibraryTable, ExcalidrawLibraryColumn),
	)
}
func newWhiteboardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WhiteboardsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WhiteboardsTable, WhiteboardsColumn),
	)
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TagsTable, TagsColumn),
	)
}
func newFontsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FontsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FontsTable, FontsColumn),
	)
}
func newImportJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ImportJobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ImportJobsTable, ImportJobsColumn),
	)
}
func newMcpTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(McpTokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, McpTokensTable, McpTokensColumn),
	)
}
func newMcpImagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(McpImagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, McpImagesTable, McpImagesColumn),
	)
}
